---
sidebar: sidebar 
permalink: rhhc/rhhc-sm-solution.html 
keywords: NetApp Solutions, redhat OpenShift, red hat OpenShift, redhat openshift container platform, ocp, openshift container platform, Advanced Cluster Management, ACM, Hub Cluster, containers, container workloads, VMware, customer managed storage, ONTAP 
summary:  
---
= Soluzione NetApp con carichi di lavoro della piattaforma container Red Hat OpenShift nel cloud ibrido
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
I clienti potrebbero trovarsi in un punto del loro percorso di modernizzazione quando sono pronti a spostare alcuni carichi di lavoro selezionati o tutti i carichi di lavoro dai data center al cloud. Possono scegliere di utilizzare container OpenShift autogestiti e storage NetApp autogestiti nel cloud per diversi motivi. Devono pianificare e implementare la piattaforma container Red Hat OpenShift (OCP) nel cloud per un ambiente pronto per la produzione di successo per la migrazione dei carichi di lavoro dei container dai data center. I loro cluster OCP possono essere implementati su VMware o bare metal nei loro data center e su AWS, Azure o Google Cloud nell'ambiente cloud.

Lo storage NetApp Cloud Volumes ONTAP offre protezione dei dati, affidabilità e flessibilità per le implementazioni di container in AWS, Azure e Google Cloud. Astra Trident funge da provider di storage dinamico per consumare lo storage Cloud Volumes ONTAP persistente per le applicazioni stateful dei clienti. Astra Control Center può essere utilizzato per orchestrare i numerosi requisiti di gestione dei dati delle applicazioni stateful come protezione dei dati, migrazione e business continuity.



== Soluzione per la migrazione e la protezione dei dati per i carichi di lavoro dei container OpenShift in un cloud ibrido con Astra Control Center

Immagine on-premise e AWS::rhhc-self-Managed-aws.png[]

Immagine on-premise e Google Cloud::rhhc-self-Managed-gcp.png[]

Immagine on-premise e cloud Azure::rhhc-self-managed-Azure.png[]
