---
sidebar: sidebar 
permalink: rhhc/rhhc-pm-solution.html 
keywords: NetApp Solutions, redhat OpenShift, red hat OpenShift, redhat openshift container platform, ocp, openshift container platform, Advanced Cluster Management, ACM, Hub Cluster, containers, container workloads, VMware, customer managed storage, ONTAP 
summary:  
---
= Soluzione NetApp con workload della piattaforma Red Hat OpenShift Container gestiti
:allow-uri-read: 




== Soluzione NetApp con workload della piattaforma Red Hat OpenShift Container gestiti

[role="lead"]
I clienti possono "nascere nel cloud" o trovarsi in un punto del loro percorso di modernizzazione quando sono pronti a spostare alcuni carichi di lavoro selezionati o tutti i carichi di lavoro dai data center al cloud. Possono scegliere di utilizzare container OpenShift gestiti da provider e storage NetApp gestito da provider nel cloud per l'esecuzione dei carichi di lavoro. È necessario pianificare e implementare i cluster di container Managed Red Hat OpenShift nel cloud per un ambiente pronto per la produzione di successo per i workload dei container. NetApp offre offerte di storage completamente gestite per soluzioni Red Hat gestite in tutti e tre i cloud pubblici leader.

*Amazon FSX per NetApp ONTAP (FSX ONTAP)*

FSX ONTAP offre data Protection, affidabilità e flessibilità per le implementazioni dei container in AWS. Trident funge da provisioner di storage dinamico per utilizzare lo storage FSX ONTAP persistente per le applicazioni stateful dei clienti.

Poiché ROSA può essere implementato in modalità ha con nodi del piano di controllo distribuiti in più zone di disponibilità, FSX ONTAP può anche essere fornito con l'opzione Multi-AZ che fornisce alta disponibilità e protegge dai guasti AZ.

*Google Cloud NetApp Volumes*

Red Hat OpenShift dedicato è una piattaforma applicativa completamente gestita che ti consente di costruire, implementare e scalare rapidamente le applicazioni nel cloud ibrido. Google Cloud NetApp Volumes fornisce volumi persistenti che offrono la suite completa delle funzionalità di Enterprise data management di ONTAP alle implementazioni di OpenShift in Google Cloud.
