---
sidebar: sidebar 
permalink: rhhc/rhhc-value-prop.html 
keywords: NetApp Solutions, hybrid cloud, container workloads, containers, Red Hat OpenShift, RedHat OpenShift, VMware, ROSA, ACC, Astra Control Center, Advanced Cluster Management, ACM, Hub Cluster 
summary:  
---
= Proposte a valore delle soluzioni NetApp ibride multicloud per i carichi di lavoro dei container Red Hat OpenShift
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
La maggior parte dei clienti non inizia a costruire ambienti basati su Kubernetes senza alcuna infrastruttura esistente. Forse si tratta di un negozio IT tradizionale che esegue la maggior parte delle applicazioni aziendali su macchine virtuali (ad esempio in ambienti VMware di grandi dimensioni). Quindi, iniziano a creare piccoli ambienti basati su container per soddisfare le esigenze dei moderni team di sviluppo delle applicazioni. Queste iniziative di solito iniziano a poco e iniziano a diventare più pervasive man mano che i team imparano queste nuove tecnologie e competenze, e iniziano a riconoscere i numerosi benefici derivanti dall'adozione di queste tecnologie. La buona notizia per i clienti è che NetApp può soddisfare le esigenze di entrambi gli ambienti. Questo set di soluzioni per il multicloud ibrido con Red Hat OpenShift consentirà ai clienti NetApp di adottare tecnologie e servizi cloud moderni senza dover rivedere l'intera infrastruttura e organizzazione. Sia che le applicazioni e i dati dei clienti siano ospitati on-premise, nel cloud, eseguiti su macchine virtuali o su container, NetApp è in grado di fornire gestione, protezione, sicurezza e portabilità dei dati coerenti. Con queste nuove soluzioni, lo stesso valore offerto da NetApp in ambienti di data center on-premise per decenni sarà disponibile nell'intero orizzonte dei dati dell'azienda, senza richiedere investimenti significativi per il ritool, l'acquisizione di nuove competenze o la creazione di nuovi team. NetApp è in grado di aiutare i clienti a risolvere queste sfide aziendali indipendentemente dalla fase del loro percorso cloud.

Multi-cloud ibrido NetApp con Red Hat OpenShift:

* Offre ai clienti design e pratiche validati che dimostrano i modi migliori per gestire, proteggere, proteggere e migrare i dati e le applicazioni quando utilizzano Red Hat OpenShift con le soluzioni di storage basate su NetApp.
* Presentare le Best practice per i clienti che utilizzano Red Hat OpenShift con lo storage NetApp in ambienti VMware, infrastruttura bare metal o una combinazione di entrambi.
* Dimostra strategie e opzioni per ambienti sia on-premise che cloud, nonché per ambienti ibridi in cui vengono utilizzati entrambi.

