---
sidebar: sidebar 
permalink: xcp/xcp-bp-high-performance-computing-to-ontap-nfs.html 
keywords: use case, gpfs, nfs 
summary: 'Abbiamo utilizzato NetApp XCP per migrare i dati da GPFS a NFS in modo che le GPU possano elaborare i dati. In genere, l"ai elabora i dati da un file system di rete.' 
---
= Calcolo dalle performance elevate per NFS ONTAP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Questo caso di utilizzo si basa sulle richieste delle organizzazioni sul campo. Alcuni clienti NetApp dispongono dei propri dati in un ambiente di calcolo dalle performance elevate, che fornisce analisi dei dati per i modelli di training e consente alle organizzazioni di ricerca di acquisire informazioni e comprendere una grande quantità di dati digitali. I tecnici sul campo di NetApp hanno bisogno di una procedura dettagliata per estrarre i dati dalla GPFS di IBM a NFS. Abbiamo utilizzato NetApp XCP per migrare i dati da GPFS a NFS in modo che le GPU possano elaborare i dati. In genere, l'ai elabora i dati da un file system di rete.

Per ulteriori informazioni sul caso d'utilizzo del software High Performance Computing to ONTAP NFS, su una demo registrata e sui risultati dei test, consulta la https://blog.netapp.com/data-migration-xcp["Utilizzo di XCP per spostare i dati da un data Lake e dall'elaborazione ad alte performance a NFS ONTAP"^] blog.

Per informazioni dettagliate sullo spostamento dei dati MapR-FS in NFS ONTAP utilizzando NetApp XCP, consultare l'Appendice A: GPF in NFS―procedure dettagliate in https://www.netapp.com/us/media/tr-4732.pdf["TR-4732: Dai dati di analisi dei big data all'intelligenza artificiale"^].
