---
sidebar: sidebar 
permalink: xcp/xcp-bp-using-the-xcp-data-mover-to-migrate-large-files.html 
keywords: migrate, large files, rman, ebs, pacemaker 
summary: 'Questo caso di utilizzo si basa su un cliente di rete televisiva. Il cliente desiderava migrare i file di backup di Oracle Recovery Manager (RMAN) nel cloud ed eseguire l"applicazione Oracle e-Business Suite (EBS) utilizzando Azure NetApp Files con il software Pacemaker. Il cliente desiderava inoltre migrare i file di backup del database nello storage cloud on-demand e trasferire file di grandi dimensioni (nell"intervallo da 25 GB a 50 GB ciascuno) in Azure.' 
---
= Utilizzo di XCP Data Mover per la migrazione di file di grandi dimensioni
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Questo caso di utilizzo si basa su un cliente di rete televisiva. Il cliente desiderava migrare i file di backup di Oracle Recovery Manager (RMAN) nel cloud ed eseguire l'applicazione Oracle e-Business Suite (EBS) utilizzando Azure NetApp Files con il software Pacemaker. Il cliente desiderava inoltre migrare i file di backup del database nello storage cloud on-demand e trasferire file di grandi dimensioni (nell'intervallo da 25 GB a 50 GB ciascuno) in Azure.

La figura seguente illustra la migrazione dei dati da on-premise a Azure NetApp Files per file di grandi dimensioni.

Per ulteriori informazioni, consultare https://blog.netapp.com/XCP-cloud-data-migration["Soluzione NetApp XCP Data Mover: On-premise per il cloud"^] blog.
