---
sidebar: sidebar 
permalink: data-analytics/apache-spark-conclusion.html 
keywords: conclusion 
summary: Questa sezione riassume questo documento relativo alle soluzioni di storage NetApp per Apache Spark. 
---
= Conclusione
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


link:apache-spark-python-scripts-for-each-major-use-case.html["Precedente: Script Python per ogni caso di utilizzo principale."]

[role="lead"]
In questo documento, discutiamo dell'architettura di Apache Spark, dei casi di utilizzo dei clienti e del portfolio di storage NetApp in relazione a big data, analytics moderni e ai, ML e DL. Nei nostri test di convalida delle performance basati su strumenti di benchmarking standard di settore e sulla domanda dei clienti, le soluzioni NetApp Spark hanno dimostrato performance superiori rispetto ai sistemi Hadoop nativi. Una combinazione dei casi di utilizzo dei clienti e dei risultati delle performance presentati in questo report può aiutarti a scegliere una soluzione Spark appropriata per la tua implementazione.

link:apache-spark-where-to-find-additional-information.html["Avanti: Dove trovare ulteriori informazioni."]
