---
sidebar: sidebar 
permalink: data-analytics/apache-spark-target-audience.html 
keywords: audience, data scientist, engineer, devops, cloud administrator, architect 
summary: In questa sezione vengono descritti gli utenti che potrebbero essere interessati al contenuto di questa soluzione. 
---
= Pubblico di riferimento
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
Il mondo dell'analytics e della scienza dei dati tocca diverse discipline nell'IT e nel business:

* Il data scientist ha bisogno della flessibilità necessaria per utilizzare i propri strumenti e le librerie preferite.
* Il data engineer deve sapere come i dati scorrono e dove risiedono.
* Un tecnico DevOps ha bisogno dei tool per integrare le nuove applicazioni ai e ML nelle pipeline ci e CD.
* Gli amministratori e gli architetti del cloud devono essere in grado di configurare e gestire le risorse del cloud ibrido.
* Gli utenti aziendali desiderano avere accesso alle applicazioni di analisi, ai, ML e DL.


In questo report tecnico, descriviamo come NetApp AFF, e-Series, StorageGRID, NFS direct access, Apache Spark, Horovod e keras aiutano ciascuno di questi ruoli a portare valore al business.
