---
sidebar: sidebar 
permalink: data-analytics/bda-ai-abstract.html 
keywords:  
summary:  
---
= Astratto
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Questo documento descrive come spostare i dati dai sistemi di analisi dei big data e di calcolo ad alte performance (HPC) in modo che possano essere utilizzati nei flussi di lavoro di intelligenza artificiale (ai). In genere, l'ai elabora i dati NFS attraverso le esportazioni NFS. Tuttavia, potresti avere i tuoi dati ai in una piattaforma di big data analytics e high performance computing (HPC). Potrebbe trattarsi di HDFS (Distributed file System) Hadoop, BLOB (Binary Large Object), S3 o GPFS (General Parallel file System) di IBM. In questo documento, descriviamo come spostare i dati da una piattaforma di analisi dei big data e GPFS a NFS utilizzando comandi nativi di Hadoop, NetApp in-place Analytics Module (NIPAM) e NetApp XCP. Questo documento illustra anche i vantaggi per il business derivanti dal trasferimento dei dati dai big data e dall'HPC all'ai.
