---
sidebar: sidebar 
permalink: data-analytics/bda-ai-customer-challenges.html 
keywords: customer, challenge, data lake, repository, syncing, moving data 
summary: Questa pagina illustra le sfide che un cliente potrebbe affrontare quando tenta di accedere ai dati dalle analisi dei big data per le operazioni di ai. 
---
= Sfide per i clienti
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


link:bda-ai-introduction.html["Precedente: Introduzione."]

[role="lead"]
I clienti potrebbero affrontare le seguenti sfide quando tentano di accedere ai dati dalle analisi dei big data per le operazioni di ai:

* I dati dei clienti si trovano in un repository di data Lake. Il data Lake può contenere diversi tipi di dati, ad esempio dati strutturati, non strutturati, semistrutturati, log e dati machine-to-machine. Tutti questi tipi di dati devono essere elaborati nei sistemi ai.
* Ai non è compatibile con i file system Hadoop. Un'architettura ai tipica non è in grado di accedere direttamente ai dati HDFS e HCFS, che devono essere spostati in un file system ai-understandable (NFS).
* Il trasferimento dei dati del data Lake all'ai richiede in genere processi specializzati. La quantità di dati nel data Lake può essere molto grande. Un cliente deve disporre di un modo efficiente, ad alto throughput e conveniente per trasferire i dati nei sistemi ai.
* Sincronizzazione dei dati. Se un cliente desidera sincronizzare i dati tra la piattaforma per big data e l'ai, a volte i dati elaborati tramite l'ai possono essere utilizzati con i big data per l'elaborazione analitica.


link:bda-ai-data-mover-solution.html["Avanti: Soluzione per il data mover."]
