---
sidebar: sidebar 
permalink: data-analytics/bda-ai-business-benefits.html 
keywords: business, benefits 
summary: Questa sezione descrive i vantaggi di questa soluzione per il business. 
---
= Benefici per il business
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Il trasferimento dei dati dall'analisi dei big data all'ai offre i seguenti vantaggi:

* Capacità di estrarre dati da diversi file system Hadoop e GPFS in un sistema storage NFS unificato
* Un metodo automatizzato e integrato con Hadoop per trasferire i dati
* Riduzione del costo dello sviluppo delle librerie per lo spostamento dei dati dai file system Hadoop
* Prestazioni massime grazie al throughput aggregato di più interfacce di rete da una singola origine di dati utilizzando NIPAM
* Metodi pianificati e on-demand per il trasferimento dei dati
* Efficienza dello storage e funzionalità di gestione aziendale per dati NFS unificati utilizzando il software di gestione dei dati ONTAP
* Nessun costo per lo spostamento dei dati con il metodo Hadoop per il trasferimento dei dati

