---
sidebar: sidebar 
permalink: data-analytics/cdm-fod-conclusion.html 
keywords: conclusion 
summary: In base a questa convalida, i data scientist e i tecnici possono accedere ai dati NFS dai notebook AWS SageMaker Jupyter tramite i bucket S3 di NetApp Cloud Volumes ONTAP. Questo approccio consente un facile accesso e condivisione degli stessi dati da NFS e S3 senza la necessità di software aggiuntivo. 
---
= Conclusione
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


link:cdm-fod-data-duality-for-data-scientists-and-other-applications.html["Precedente: Dualità dei dati per data scientist e altre applicazioni."]

[role="lead"]
In base a questa convalida, i data scientist e i tecnici possono accedere ai dati NFS dai notebook AWS SageMaker Jupyter tramite i bucket S3 di NetApp Cloud Volumes ONTAP. Questo approccio consente un facile accesso e condivisione degli stessi dati da NFS e S3 senza la necessità di software aggiuntivo.



== Dove trovare ulteriori informazioni

Per ulteriori informazioni sulle informazioni descritte in questo documento, consultare i seguenti documenti e/o siti Web:

* Classificazione del testo con SageMaker BlazingText
+
https://sagemaker-examples.readthedocs.io/en/latest/introduction_to_amazon_algorithms/blazingtext_text_classification_dbpedia/blazingtext_text_classification_dbpedia.html["https://sagemaker-examples.readthedocs.io/en/latest/introduction_to_amazon_algorithms/blazingtext_text_classification_dbpedia/blazingtext_text_classification_dbpedia.html"^]

* Supporto della versione di ONTAP per lo storage a oggetti S3
+
https://docs.netapp.com/us-en/ontap/s3-config/ontap-version-support-s3-concept.html["https://docs.netapp.com/us-en/ontap/s3-config/ontap-version-support-s3-concept.html"^]





== Cronologia delle versioni

|===
| Versione | Data | Cronologia delle versioni del documento 


| Versione 1.0 | Aprile 2023 | Release iniziale 
|===