---
sidebar: sidebar 
permalink: data-analytics/hdcs-sh-overview-of-hadoop-data-protection-use-cases.html 
keywords: summary, overview, backup, devtest, data protection 
summary: 'In questa sezione viene fornita una descrizione dettagliata dei casi di utilizzo della protezione dei dati, che costituiscono l"oggetto del presente documento. Le restanti sezioni forniscono ulteriori dettagli per ciascun caso di utilizzo, ad esempio il problema del cliente (scenario), i requisiti, le sfide e le soluzioni.' 
---
= Panoramica dei casi di utilizzo della protezione dei dati Hadoop
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
In questa sezione viene fornita una descrizione dettagliata dei casi di utilizzo della protezione dei dati, che costituiscono l'oggetto del presente documento. Le restanti sezioni forniscono ulteriori dettagli per ciascun caso di utilizzo, ad esempio il problema del cliente (scenario), i requisiti, le sfide e le soluzioni.



== Caso d'utilizzo 1: Backup dei dati Hadoop

Per questo caso d'utilizzo, il volume NFS di NetApp ha aiutato un grande istituto finanziario a ridurre l'estesa finestra di backup da più di 24 ore a poco meno di poche ore.



== Caso d'utilizzo 2: Backup e disaster recovery dal cloud all'on-premise

Utilizzando il data fabric basato su NetApp come elementi di base, una grande azienda di radiodiffusione è stata in grado di soddisfare il proprio requisito di backup dei dati cloud nel proprio data center on-premise, a seconda delle diverse modalità di trasferimento dei dati, come on-demand, istantaneo, O in base al carico del cluster Hadoop/Spark.



== Caso d'utilizzo 3: Abilitare DevTest sui dati Hadoop esistenti

Le soluzioni NetApp hanno aiutato un distributore di musica online a creare rapidamente più cluster Hadoop efficienti in termini di spazio in diverse filiali per creare report ed eseguire attività DevTest quotidiane utilizzando policy pianificate.



== Caso d'utilizzo 4: Protezione dei dati e connettività multicloud

Un grande provider di servizi ha utilizzato il data fabric basato su NetApp per fornire ai propri clienti analytics multicloud da diverse istanze di cloud.



== Caso d'utilizzo 5: Accelerare i carichi di lavoro di analisi

Una delle più grandi banche di investimento e servizi finanziari ha utilizzato la soluzione di storage NAS di NetApp per ridurre i tempi di attesa i/o e accelerare la piattaforma di analisi finanziaria quantitativa.
