---
sidebar: sidebar 
permalink: data-analytics/hdcs-sh-conclusion.html 
keywords: conclusion, summary, data protection, hadoop, more information, Acknowledgements 
summary: Questa sezione fornisce un riepilogo dei casi di utilizzo e delle soluzioni fornite da NetApp per soddisfare i vari requisiti di protezione dei dati Hadoop. 
---
= Conclusione
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Questa sezione fornisce un riepilogo dei casi di utilizzo e delle soluzioni fornite da NetApp per soddisfare i vari requisiti di protezione dei dati Hadoop. Utilizzando il data fabric basato su NetApp, i clienti possono:

* Avere la flessibilità di scegliere le giuste soluzioni per la protezione dei dati sfruttando le ricche funzionalità di gestione dei dati di NetApp e l'integrazione con i flussi di lavoro nativi di Hadoop.
* Ridurre i tempi di backup del cluster Hadoop di quasi il 70%.
* Elimina qualsiasi effetto sulle performance derivante dai backup del cluster Hadoop.
* Protezione dei dati multicloud e accesso ai dati da diversi cloud provider contemporaneamente a una singola fonte di dati di analisi.
* Crea copie cluster Hadoop veloci ed efficienti in termini di spazio utilizzando la tecnologia FlexClone.




== Dove trovare ulteriori informazioni

Per ulteriori informazioni sulle informazioni descritte in questo documento, consultare i seguenti documenti e/o siti Web:

* Soluzioni NetApp per l'analisi dei big data
+
https://www.netapp.com/us/solutions/applications/big-data-analytics/index.aspx["https://www.netapp.com/us/solutions/applications/big-data-analytics/index.aspx"^]

* Apache Spark workload con lo storage NetApp
+
https://www.netapp.com/pdf.html?item=/media/26877-nva-1157-deploy.pdf["https://www.netapp.com/pdf.html?item=/media/26877-nva-1157-deploy.pdf"^]

* Soluzioni storage NetApp per Apache Spark
+
https://www.netapp.com/media/16864-tr-4570.pdf["https://www.netapp.com/media/16864-tr-4570.pdf"^]

* Apache Hadoop su data fabric abilitato da NetApp
+
https://www.netapp.com/media/16877-tr-4529.pdf["https://www.netapp.com/media/16877-tr-4529.pdf"^]





== Ringraziamenti

* Paul Burland, Sales Rep, ANZ Victoria District Sales, NetApp
* Hoseb Dermanilian, Business Development Manager, NetApp
* Lee Dorrier, Director MPSG, NetApp
* David Thiessen, Systems Engineer, ANZ Victoria District se, NetApp




== Cronologia delle versioni

|===
| Versione | Data | Cronologia delle versioni del documento 


| Versione 1.0 | Gennaio 2018 | Release iniziale 


| Versione 2.0 | Ottobre 2021 | Aggiornato con il caso di utilizzo n. 5: Accelerare il carico di lavoro di analisi 


| Versione 3.0 | Novembre 2023 | Dettagli NIPAM rimossi 
|===