---
sidebar: sidebar 
permalink: data-analytics/kafka-ontap-overview.html 
keywords: tr4941, 4941, introduction 
summary: Questo documento descrive i benchmark delle performance per la piattaforma Confluent su NetApp ONTAP utilizzando un kit di benchmarking per lo storage a più livelli. 
---
= TR-4941: Confluenza con i controller di storage NetApp ONTAP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


Karthikeyan Nagalingam, Joe Scott, NetApp Rankesh Kumar, Confluent

[role="lead"]
Per rendere la piattaforma Confluent più scalabile ed elastica, l'IT deve essere in grado di scalare e bilanciare i carichi di lavoro molto rapidamente. Lo storage a più livelli consente di gestire l'archiviazione di enormi volumi di dati in Confluent riducendo il carico operativo.

L'idea fondamentale è separare lo storage dei dati dall'elaborazione dei dati, il che rende molto più semplice la scalabilità di ciascuno di essi in modo indipendente.

Dotato di innovazioni leader del settore, il software per la gestione dei dati NetApp ONTAP offre a Confluent numerosi vantaggi ovunque i dati siano presenti.

Questo documento descrive i benchmark delle performance per la piattaforma Confluent su NetApp ONTAP utilizzando un kit di benchmarking per lo storage a più livelli.
