---
sidebar: sidebar 
permalink: data-analytics/kafka-nfs-conclusion.html 
keywords: conclusion 
summary: La soluzione NetApp per il problema del ridenominazione sciocco offre una forma di storage semplice, economica e gestita centralmente per carichi di lavoro che in precedenza erano incompatibili con NFS. 
---
= Conclusione
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


link:kafka-nfs-performance-overview-and-validation-with-aff-on-premises.html["Precedente: Panoramica delle performance e validazione con AFF on-premise."]

[role="lead"]
La soluzione NetApp per il problema del ridenominazione sciocco offre una forma di storage semplice, economica e gestita centralmente per carichi di lavoro che in precedenza erano incompatibili con NFS. Questo nuovo paradigma consente ai clienti di creare cluster Kafka più gestibili che siano più facili da migrare e eseguire il mirroring ai fini del disaster recovery e della protezione dei dati. Abbiamo anche visto che NFS offre ulteriori vantaggi, come la riduzione dell'utilizzo della CPU e un tempo di recovery più rapido, un notevole miglioramento dell'efficienza dello storage e migliori performance grazie a NetApp ONTAP.

link:kafka-nfs-where-to-find-additional-information.html["Avanti: Dove trovare ulteriori informazioni."]
