---
sidebar: sidebar 
permalink: data-analytics/stgr-splunkss-conclusion.html 
keywords: conclusion, references 
summary: 'Splunk Enterprise è la soluzione SIEM leader di mercato che offre risultati ai team di sicurezza, IT e DevOps. L"utilizzo di Splunk è aumentato notevolmente nelle organizzazioni dei nostri clienti. Pertanto, è necessario aggiungere più origini dati mantenendo i dati per un periodo più lungo, insistendo così sull"infrastruttura Splunk.' 
---
= Conclusione
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Splunk Enterprise è la soluzione SIEM leader di mercato che offre risultati ai team di sicurezza, IT e DevOps. L'utilizzo di Splunk è aumentato notevolmente nelle organizzazioni dei nostri clienti. Pertanto, è necessario aggiungere più origini dati mantenendo i dati per un periodo più lungo, insistendo così sull'infrastruttura Splunk.

La combinazione di Splunk SmartStore e NetApp StorageGRID è progettata per fornire un'architettura scalabile alle organizzazioni per ottenere migliori performance di acquisizione con SmartStore e lo storage a oggetti StorageGRID e una maggiore scalabilità per un ambiente Splunk in più aree geografiche.



== Dove trovare ulteriori informazioni

Per ulteriori informazioni sulle informazioni descritte in questo documento, consultare i seguenti documenti e/o siti Web:

* Risorse di documentazione NetApp StorageGRID
+
https://docs.netapp.com/us-en/storagegrid-family/["https://docs.netapp.com/us-en/storagegrid-family/"^]

* Documentazione sui prodotti NetApp
+
https://docs.netapp.com["https://docs.netapp.com"^]

* Documentazione Splunk Enterprise
+
https://docs.splunk.com/Documentation/Splunk["https://docs.splunk.com/Documentation/Splunk"^]

* Splunk Enterprise informazioni su SmartStore
+
https://docs.splunk.com/Documentation/Splunk/8.0.6/Indexer/AboutSmartStore["https://docs.splunk.com/Documentation/Splunk/8.0.6/Indexer/AboutSmartStore"^]

* Splunk Enterprise Distributed Deployment Manual
+
https://docs.splunk.com/Documentation/Splunk/8.0.6/Deploy/Distributedoverview["https://docs.splunk.com/Documentation/Splunk/8.0.6/Deploy/Distributedoverview"^]

* Splunk Enterprise Gestione di Indexer e Clusters di Indexer
+
https://docs.splunk.com/Documentation/Splunk/8.0.6/Indexer/Aboutindexesandindexers["https://docs.splunk.com/Documentation/Splunk/8.0.6/Indexer/Aboutindexesandindexers"^]


