---
sidebar: sidebar 
permalink: data-analytics/stgr-splunkss-solution-benefits.html 
keywords: benefits, performance, multi-site, scalability, capacity, availability, cache 
summary: La soluzione consente di aggiungere risorse di elaborazione, di hot storage o S3 per soddisfare la crescente domanda in termini di numero di utenti o velocità di acquisizione in distribuzioni singole e multi-sito. 
---
= Vantaggi di questa soluzione
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
La soluzione consente di aggiungere risorse di elaborazione, di hot storage o S3 per soddisfare la crescente domanda in termini di numero di utenti o velocità di acquisizione in distribuzioni singole e multi-sito.

* *Prestazioni.* la combinazione di Splunk SmartStore e NetApp StorageGRID offre una rapida migrazione dei dati tra bucket hot e bucket warm utilizzando lo storage a oggetti. StorageGRID accelera il processo di migrazione fornendo performance veloci per carichi di lavoro a oggetti di grandi dimensioni.
* *Compatibile con più siti.* l'architettura distribuita di StorageGRID consente a Splunk SmartStore di estendere le implementazioni su siti singoli e multipli attraverso un singolo namespace globale in cui è possibile accedere ai dati da qualsiasi sito, indipendentemente dalla posizione in cui risiedono i dati.
* *Maggiore scalabilità.* scalare le risorse di storage in modo indipendente dalle risorse di calcolo per soddisfare esigenze e richieste in evoluzione nel tuo ambiente Splunk, fornendo così un TCO migliorato.
* *Capacità.* raggiungi volumi in rapida crescita nell'implementazione di Splunk con StorageGRID scalando un singolo namespace a oltre 560 PB.
* *Disponibilità dei dati.* Ottimizza disponibilità, performance, geodistribuzione, conservazione, protezione, e i costi dello storage con policy basate sui metadati che possono adattarsi in modo dinamico con l'evolversi del valore di business dei dati.


Aumenta le performance con la cache SmartStore, un componente dell'indicizzatore che gestisce il trasferimento delle copie bucket tra storage locale (hot) e remoto (warm). . La soluzione consente di aggiungere risorse di elaborazione, di hot storage o S3 per soddisfare la crescente domanda in termini di numero di utenti o velocità di acquisizione in distribuzioni singole e multi-sito
