---
sidebar: sidebar 
permalink: data-analytics/tr-4623.html 
keywords:  
summary:  
---
= TR-4623: NetApp e-Series E5700 e Splunk Enterprise
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


Mitch Blackburn, NetApp

[role="lead"]
TR-4623 descrive l'architettura integrata del design NetApp e-Series e Splunk. Ottimizzato per bilanciamento dello storage dei nodi, affidabilità, performance, capacità dello storage e densità, Questa progettazione utilizza il modello di nodo Splunk Clustered Index, con una maggiore scalabilità e un TCO inferiore. Il disaccoppiamento dello storage dal calcolo offre la possibilità di scalare ciascuno separatamente, risparmiando il costo dell'overprovisioning uno o l'altro. Inoltre, questo documento riassume i risultati dei test delle performance ottenuti da uno strumento di simulazione degli eventi del log della macchina Splunk.

link:https://www.netapp.com/pdf.html?item=/media/16851-tr-4623pdf.pdf["TR-4623: NetApp e-Series E5700 e Splunk Enterprise"^]
