---
sidebar: sidebar 
permalink: hyperv/hyperv-deploy-conclusion.html 
keywords: hyperv, hyper-v, deploy, netapp, virtualization 
summary: La soluzione fornisce le fasi necessarie per implementare Hyper-V sullo storage NetApp 
---
= Distribuzione di Microsoft Hyper-V sullo storage NetApp: Conclusione
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
ONTAP è la base di storage condiviso ottimale per implementare una vasta gamma di workload IT. Le piattaforme ONTAP AFF o ASA sono flessibili e scalabili per casi d'utilizzo e applicazioni multipli. Windows Server 2022 e Hyper-V attivati su di esso sono un caso di utilizzo comune come soluzione di virtualizzazione, descritto in questo documento. La flessibilità e la scalabilità dello storage ONTAP e delle funzioni associate consentono ai clienti di iniziare con un layer storage di dimensioni adeguate che può crescere e adattarsi ai propri requisiti di business in continua evoluzione. Nelle attuali condizioni di mercato, Hyper-V offre un'opzione di hypervisor alternativa perfetta, che fornisce la maggior parte delle funzionalità fornite da VMware.
