---
sidebar: sidebar 
permalink: hyperv/hyperv-deploy.html 
keywords: hyperv, hyper-v, deploy, netapp, virtualization, overview 
summary: La soluzione fornisce le fasi necessarie per implementare Hyper-V sullo storage NetApp 
---
= Distribuzione di Microsoft Hyper-V sullo storage NetApp
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
La piattaforma Windows Server utilizza il ruolo di Hyper-V per fornire la tecnologia di virtualizzazione. Hyper-V è uno dei numerosi ruoli opzionali offerti con Windows Server.



== Panoramica

Il ruolo Hyper-V ci permette di creare e gestire un ambiente informatico virtualizzato utilizzando la tecnologia di virtualizzazione integrata in Windows Server. La tecnologia Hyper-V virtualizza l'hardware per fornire un ambiente in cui è possibile eseguire più sistemi operativi contemporaneamente su un unico computer fisico. Hyper-V ti consente di creare e gestire le macchine virtuali e le loro risorse. Ogni macchina virtuale è un sistema informatico isolato e virtualizzato in grado di eseguire il proprio sistema operativo. Hyper-V fornisce un'infrastruttura per la virtualizzazione di applicazioni e carichi di lavoro che supporta una varietà di obiettivi aziendali volti a migliorare l'efficienza e ridurre i costi, un'alternativa perfetta a VMware® vSphere, soprattutto quando le organizzazioni sono alla ricerca di una coesistenza di più hypervisor nelle attuali condizioni di mercato.



== Pubblico

Questo documento descrive l'architettura e le procedure di distribuzione per la configurazione del cluster Hyper-V con i sistemi NetApp ONTAP. Il presente documento è destinato a tecnici di vendita, consulenti sul campo, servizi professionali, responsabili IT, tecnici dei partner, e clienti che intendono implementare Hyper-V come hypervisor principale o alternativo.



== Architettura

L'architettura descritta in questo documento include in particolare la virtualizzazione Microsoft® Windows Server® 2022 e Hyper-V®. NetApp consiglia vivamente il software di virtualizzazione e il software di gestione dell'infrastruttura come parte di ogni implementazione. La configurazione utilizza le Best practice per ogni componente per consentire un'infrastruttura affidabile di classe Enterprise.



== Riepilogo dei casi d'utilizzo

Questo documento descrive le procedure di implementazione e le Best practice per la configurazione del cluster Hyper-V per un funzionamento ottimale come carico di lavoro su Microsoft Windows Server 2022 utilizzando modelli di array FAS all-flash e ASA di NetApp. Il sistema operativo/hypervisor del server è Microsoft Windows Server 2022. Le linee guida riguardano i sistemi storage NetApp che gestiscono dati tramite i protocolli SAN (Storage Area Network) e NAS (Network-Attached Storage).
