---
settings:
  name: NetApp Solutions
  harmony_integration: maestro
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
    lipi_enabled: false
  langs: it-it,us-en,ja-jp,ko-kr,zh-cn,zh-tw,de-de,es-es,fr-fr
sidebar:
  entries:
  - title: Documentazione sulle soluzioni NetApp
    url: "/index.html"
  - section: ai
  - section: containers
  - section: data-access
  - title: Applicazioni aziendali
    entries:
    - title: SAP E SAP HANA
      url: https://docs.netapp.com/us-en/netapp-solutions-sap/
  - section: databases
  - section: data-analytics
  - section: ehc
  - section: rhhc
  - section: virtualization
  - section: automation
  - title: Soluzioni FlexPod
    url: https://docs.netapp.com/us-en/flexpod/
  - title: Soluzioni NetApp HCI legacy
    url: https://docs.netapp.com/us-en/hci-solutions/
  - title: Registro delle modifiche
    url: "/change-log-display.html"
  - title: Informazioni sulle soluzioni NetApp
    url: "/about.html"
  - title: Note legali
    url: "/reference_legal_notices.html"
homepage:
  tiles:
  - title: Introduzione
    links:
    - title: A proposito di questo repository
      url: about.html
    - title: Cronologia delle modifiche
      url: change-log-display.html
    - title: Blog
      url: blogs.html
    - title: Video e demo
      url: videos.html
    - title: Note legali
      url: legal-notices.html
  - title: Pagine di destinazione della soluzione
    links:
    - title: Intelligenza artificiale
      url: ai/index.html
    - title: Container
      url: containers/index.html
    - title: Database aziendali
      url: databases/index.html
    - title: Analisi dei dati moderna
      url: data-analytics/index.html
    - title: Multicloud ibrido NetApp con VMware
      url: ehc/index.html
    - title: Multicloud ibrido NetApp con Red Hat
      url: rhhc/index.html
    - title: SAP E SAP HANA
      url: https://docs.netapp.com/us-en/netapp-solutions-sap/index.html
    - title: Virtualizzazione
      url: virtualization/index.html
  - title: Automazione della soluzione
    links:
    - title: Introduzione
      url: automation/automation_introduction.html
    - title: Per iniziare
      url: automation/getting-started.html
    - title: Automazione della richiesta
      url: https://github.com/NetAppDocs/netapp-solutions/issues/new?body=[Request%20Automation]%0d%0a%0d%0aSolution%20Name:%20%0d%0aRequest%20Title:%20%0d%0aDescription:%0d%0aSuggestions:&title=Request%20Automation%20-%20%3Crequest_title%3E
  - title: FlexPod - Una soluzione NetApp e Cisco
    links:
    - title: Contenuti tecnici per le soluzioni FlexPod
      url: https://docs.netapp.com/us-en/flexpod/
    - title: Pagina di vendita FlexPod
      url: https://flexpod.com
    - title: Video e demo

      url: https://tv.netapp.com/search?q=flexpod
    - title: Blog
      url: https://blog.netapp.com/tag/FlexPod/
  - title: Feedback
    links:
    - title: Proporre una nuova soluzione
      url: https://github.com/NetAppDocs/netapp-solutions/issues/new?body=[Request%20Solution]%0d%0a%0d%0aSolution%20Use%20Case:%20%0d%0aSolution%20Description:%20%0d%0aAdditional%20Comments:&title=Request%20Solution%20-%20%3Csolution%3E
    - title: Fornire un feedback sulla soluzione
      url: https://github.com/NetAppDocs/netapp-solutions/issues/new?body=[Solution%20Feedback]%0d%0a%0d%0aSolution%20Name:%20%0d%0aSolution%20Feedback:%20%0d%0aAdditional%20Comments:&title=Solution%20Feedback%20-%20%3Csolution%3E
