---
settings:
  name: NetApp Solutions
  harmony_integration: maestro
  internal:
    pdf_enabled: false
  prod:
    pdf_enabled: true
    harmony_enabled: false
    lipi_enabled: false
  langs: it-it,us-en,ja-jp,ko-kr,zh-cn,zh-tw,de-de,es-es,fr-fr
sidebar:
  entries:
  - title: Documentazione sulle soluzioni NetApp
    url: "/index.html"
  - section: ai
  - section: containers
  - section: data-access
  - title: Applicazioni aziendali
    entries:
    - title: SAP E SAP HANA
      url: https://docs.netapp.com/us-en/netapp-solutions-sap/
  - section: databases
  - section: data-analytics
  - section: ehc
  - section: rhhc
  - section: virtualization
  - section: automation
  - title: Soluzioni FlexPod
    url: https://docs.netapp.com/us-en/flexpod/
  - title: Soluzioni NetApp HCI legacy
    url: https://docs.netapp.com/us-en/hci-solutions/
  - title: Registro delle modifiche
    url: "/change-log-display.html"
  - title: Informazioni sulle soluzioni NetApp
    url: "/about.html"
  - title: Note legali
    url: "/legal-notices.html"
