---
settings:
  name: NetApp Solutions
  harmony_integration: maestro
  internal:
    pdf_enabled: false
  prod:
    pdf_enabled: true
    harmony_enabled: false
    lipi_enabled: false
  langs: it-it,us-en,ja-jp,ko-kr,zh-cn,zh-tw,de-de,es-es,fr-fr
sidebar:
  entries:
  - title: Documentazione sulle soluzioni NetApp
    url: index.html
  - section: ai
  - section: data-analytics
  - section: cloud
  - section: virtualization
  - section: containers
  - section: databases
  - section: data-access
  - section: automation
  - title: SAP E SAP HANA
    url: https://docs.netapp.com/us-en/netapp-solutions-sap/
  - title: Soluzioni FlexPod
    url: https://docs.netapp.com/us-en/flexpod/
  - title: Registro delle modifiche
    url: change-log-display.html
  - title: Informazioni sulle soluzioni NetApp
    url: about.html
  - title: Note legali
    url: "/legal-notices.html"
