---
sidebar: sidebar 
permalink: videos.html 
summary: Serie di video e demo che illustrano le funzionalità di molte delle soluzioni NetApp 
keywords: netapp, solutions, videos, demos 
---
= Soluzioni NetApp: Video e demo
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:table-stripes: odd
:imagesdir: ./media/


[role="lead"]
Panoramica dei video e delle demo che evidenziano le funzionalità specifiche di molte delle soluzioni NetApp.

.Intelligenza artificiale (ai) e analisi dei dati moderna
[#ai%collapsible]
====
* link:https://www.youtube.com/playlist?list=PLdXI3bZJEw7nSrRhuolRPYqvSlGLuTOAO["Soluzioni ai di NetApp"^]
* link:https://www.youtube.com/playlist?list=PLdXI3bZJEw7n1sWK-QGq4QMI1VBJS-ZZW["MLOPS"^]


====
.Applicazioni e database aziendali
[#db%collapsible]
====
[Sottolineare] * Video per database open source* n.

[cols="5a, 5a, 5a"]
|===


 a| 
Implementazione automatica PostgreSQL, configurazione della replica ha/DR, failover, risincronizzazione

 a| 
 a| 

|===
[Sottolineare] * Video per la modernizzazione di Oracle con cloud ibrido in AWS e FSX* n.

[cols="5a, 5a, 5a"]
|===


 a| 
Parte 1 - caso d'utilizzo e architettura della soluzione

 a| 
Parte 2a - migrazione del database da on-premise ad AWS utilizzando il trasferimento automatizzato di PDB con la massima disponibilità

 a| 
Parte 2b - migrazione del database da on-premise ad AWS utilizzando la console BlueXP tramite SnapMirror




 a| 
Parte 3 - Configurazione automatica della replica ha/DR del database, failover, risincronizzazione

 a| 
Parte 4a - clone del database per sviluppo/test con interfaccia utente SnapCenter dalla copia di standby replicata

 a| 
Parte 4b - Backup, ripristino e clonazione del database con l'interfaccia utente di SnapCenter




 a| 
Parte 4c - Backup e ripristino del database con backup e ripristino di BlueXP SaaS Apps

 a| 
 a| 

|===
[Sottolineato] * Video per database SQL Server* n.

[cols="5a, 5a, 5a"]
|===


 a| 
Implementa SQL Server su AWS EC2 utilizzando Amazon FSX per NetApp ONTAP

 a| 
Oracle Multi-tenant Pluggable Database Clone con snapshot di storage

video::krzMWjrrMb0[youtube,width=360] a| 
Implementazione automatizzata di Oracle 19c RAC su FlexPod con Ansible

video::VcQMJIRzhoY[youtube,width=360]
|===
*Case study*

* link:https://customers.netapp.com/en/sap-azure-netapp-files-case-study["SAP su Azure NetApp Files"^]


====
.Multicloud ibrido (HMC)
[#hmc%collapsible]
====
[Sottolineato] * Video per AWS/VMC* n.

[cols="5a, 5a, 5a"]
|===


 a| 
Storage connesso guest Windows con FSX ONTAP utilizzando iSCSI

 a| 
Storage connesso guest Linux con FSX ONTAP con NFS

 a| 
Risparmi sul TCO di VMware Cloud su AWS con Amazon FSX per NetApp ONTAP




 a| 
Archivio dati supplementare VMware Cloud su AWS con Amazon FSX per NetApp ONTAP

 a| 
Installazione della configurazione e dell'implementazione di VMware HCX per VMC

 a| 
Dimostrazione della migrazione a VMotion con VMware HCX per VMC e FSxN




 a| 
Dimostrazione della migrazione a freddo con VMware HCX per VMC e FSxN

 a| 
 a| 

|===
[Sottolineato] * Video per Azure/AVS* n.

[cols="5a, 5a, 5a"]
|===


 a| 
Panoramica del datastore supplementare della soluzione VMware Azure con Azure NetApp Files

 a| 
Soluzione VMware Azure DR con Cloud Volumes ONTAP, SnapCenter e JetStream

 a| 
Dimostrazione della migrazione a freddo con VMware HCX per AVS e ANF




 a| 
Dimostrazione di VMotion con VMware HCX per AVS e ANF

 a| 
Dimostrazione della migrazione in blocco con VMware HCX per AVS e ANF

 a| 

|===
====
.MultiCloud ibrido con Red Hat OpenShift
[#rhhc%collapsible]
====
[cols="5a, 5a, 5a"]
|===


 a| 
ROSA DR con Astra Control Service

 a| 
Integrazione di FSxN con Astra Trident

 a| 
Failover e fail-back delle applicazioni su ROSA con FSxN




 a| 
Dr utilizzando Astra Control Center

link:https://www.netapp.tv/details/29504?mcid=35609780286441704190790628065560989458["Guarda su NetAppTV"]
 a| 
 a| 

|===
====
.Virtualizzazione
[#virtualization%collapsible]
====
* link:virtualization/vsphere_demos_videos.html["Raccolta video VMware"]


====
.Container/Kubernetes
[#containers%collapsible]
====
* link:containers/anthos-with-netapp/a-w-n_videos_and_demos.html["Video NetApp con Google anthos"]
* link:containers/tanzu_with_netapp/vtwn_videos_and_demos.html["Video NetApp con VMware Tanzu"]
* link:containers/devops_with_netapp/dwn_videos_and_demos.html["Video NetApp per DevOps"]
* link:containers/rh-os-n_videos_and_demos.html["Video di NetApp con Red Hat OpenShift"]


====
.Automazione della soluzione
[#automation%collapsible]
====
[cols="5a, 5a, 5a"]
|===


 a| 
Implementazione automatizzata di Oracle 19c RAC su FlexPod con Ansible

video::VcQMJIRzhoY[youtube,width=360] a| 
 a| 

|===
====