---
sidebar: sidebar 
permalink: ehc/aws-vmc.html 
keywords: NetApp Solutions, hyperscalers, amazon, vmc, vmware managed cloud, enterprise, hybrid, cloud, migrate, migration, disaster recovery, dr 
summary:  
---
= Funzionalità NetApp per AWS VMC
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
Scopri di più sulle funzionalità offerte da NetApp in AWS VMware Cloud (VMC), da NetApp come dispositivo di storage connesso come guest o come datastore NFS supplementare alla migrazione dei flussi di lavoro, all'estensione/diffusione nel cloud, al backup/ripristino e al disaster recovery.

Passare alla sezione relativa al contenuto desiderato selezionando una delle seguenti opzioni:

* link:#config["Configurazione di VMC in AWS"]
* link:#datastore["Opzioni di storage NetApp per VMC"]
* link:#solutions["Soluzioni cloud NetApp/VMware"]




== Configurazione di VMC in AWS

Come per i sistemi on-premise, la pianificazione di un ambiente di virtualizzazione basato sul cloud è fondamentale per un ambiente pronto per la produzione di successo per la creazione di macchine virtuali e la migrazione.

Questa sezione descrive come configurare e gestire VMware Cloud su AWS SDDC e utilizzarlo in combinazione con le opzioni disponibili per la connessione dello storage NetApp.


NOTE: Lo storage in-guest è l'unico metodo supportato per connettere Cloud Volumes ONTAP ad AWS VMC.

Il processo di installazione può essere suddiviso nei seguenti passaggi:

* Implementazione e configurazione di VMware Cloud per AWS
* Connetti VMware Cloud a FSX ONTAP


Visualizza i dettagli link:aws-setup.html["Procedura di configurazione per VMC"].



== Opzioni di storage NetApp per VMC

Lo storage NetApp può essere utilizzato in diversi modi, sia come congettura connessa che come datastore NFS supplementare, all'interno di AWS VMC.

Visitare il sito link:ehc-support-configs.html["Opzioni di storage NetApp supportate"] per ulteriori informazioni.

AWS supporta lo storage NetApp nelle seguenti configurazioni:

* FSX ONTAP come storage connesso guest
* Cloud Volumes ONTAP (CVO) come storage connesso guest
* FSX ONTAP come datastore NFS supplementare


Visualizza i dettagli link:aws-guest.html["Opzioni di storage di connessione guest per VMC"]. Visualizza i dettagli link:aws-native-nfs-datastore-option.html["Opzioni aggiuntive del datastore NFS per VMC"].



== Casi di utilizzo della soluzione

Con le soluzioni cloud NetApp e VMware, molti casi di utilizzo sono semplici da implementare nel tuo AWS VMC. I casi di utilizzo sono definiti per ciascuna delle aree cloud definite da VMware:

* Protect (include disaster recovery e backup/ripristino)
* Estendi
* Migrare


link:aws-solutions.html["Esplora le soluzioni NetApp per AWS VMC"]
