---
sidebar: sidebar 
permalink: ehc/aws-storage-options.html 
keywords: aws, netapp, fsxn, storage, options, nfs, supplemental, cvo 
summary: Lo storage NetApp può essere collegato al servizio Azure VMware come storage connesso come guest o supplementare. 
---
= Amazon Web Services: Opzioni per l'utilizzo dello storage NetApp
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Lo storage NetApp può essere collegato agli Amazon Web Services come storage connesso come guest o supplementare.



== Amazon FSX per NetApp ONTAP (FSX ONTAP) come datastore NFS supplementare

Amazon FSX ONTAP offre opzioni eccellenti per l'implementazione e la gestione dei workload dell'applicazione insieme ai file service, riducendo al tempo stesso il TCO rendendo i requisiti dei dati perfetti nel layer applicativo. Qualunque sia il caso di utilizzo, scegli VMware Cloud on AWS insieme ad Amazon FSX ONTAP per ottenere una rapida realizzazione dei vantaggi del cloud, di un'infrastruttura coerente e delle operazioni on-premise in AWS, della portabilità bidirezionale dei workload e della capacità e delle performance di livello Enterprise. Si tratta degli stessi processi e procedure familiari utilizzati per collegare lo storage.

Per ulteriori informazioni, visitare il sito:

* link:aws-native-overview.html["FSX ONTAP come archivio dati NFS supplementare: Panoramica"]
* link:aws-native-nfs-datastore-option.html["Amazon FSX per ONTAP come datastore supplementare"]




== Amazon FSX per NetApp ONTAP come storage connesso come ospite

Amazon FSX ONTAP è un servizio completamente gestito che offre un file storage altamente affidabile, scalabile, dalle performance elevate e ricco di funzionalità, costruito sul popolare file system ONTAP di NetApp. FSX ONTAP combina le caratteristiche, le performance, le capacità e le operazioni API note dei file system NetApp con l'agilità, la scalabilità e la semplicità di un servizio AWS completamente gestito.

FSX ONTAP offre un file storage condiviso ricco di funzionalità, rapido e flessibile, altamente accessibile da istanze di calcolo Linux, Windows e macOS in esecuzione in AWS o on-premise. FSX ONTAP offre uno storage su dischi a stato solido (SSD) dalle performance elevate con latenze inferiori al millisecondo. Con FSX ONTAP, puoi ottenere livelli di performance SSD per il tuo carico di lavoro, pagando per lo storage SSD solo per una piccola frazione dei dati.

Gestire i dati con FSX ONTAP è più semplice perché puoi snapshot, clonazione e replica i file con un semplice clic. Inoltre, FSX ONTAP esegue automaticamente il tiering dei dati su uno storage elastico e a basso costo, riducendo la necessità di eseguire il provisioning o gestire la capacità.

FSX ONTAP offre inoltre storage altamente disponibile e duraturo con backup completamente gestiti e supporto per il disaster recovery tra più aree. Per semplificare la protezione e la protezione dei dati, FSX ONTAP supporta le più diffuse applicazioni antivirus e di sicurezza dei dati.

Per ulteriori informazioni, visitare il sito link:aws-guest.html#fsx-ontap["FSX ONTAP come storage connesso guest"]



== Cloud Volumes ONTAP (CVO) come storage connesso guest

Cloud Volumes ONTAP, o CVO, è la soluzione per la gestione dei dati nel cloud leader del settore basata sul software di storage ONTAP, disponibile in modalità nativa su Amazon Web Services (AWS), Microsoft Azure e Google Cloud Platform (GCP).

Si tratta di una versione software-defined di ONTAP che utilizza lo storage nativo del cloud, consentendoti di avere lo stesso software di storage nel cloud e on-premise, riducendo la necessità di riorganizzare il tuo staff IT con metodi completamente nuovi per gestire i tuoi dati.

CVO offre ai clienti la possibilità di spostare senza problemi i dati dall'edge al data center, al cloud e viceversa, unendo il tuo cloud ibrido, il tutto gestito con una console di gestione a singolo pannello, NetApp Cloud Manager.

Per progettazione, CVO offre performance estreme e funzionalità di gestione dei dati avanzate per soddisfare anche le applicazioni più esigenti nel cloud.

Per ulteriori informazioni, visitare il sito link:aws-guest.html#aws-cvo["CVO come Guest Connected Storage"].
