---
sidebar: sidebar 
permalink: ehc/ehc-solutions.html 
keywords: NetApp Solutions, aws, amazon, vmc, vmware managed cloud, azure, avs, gcp, gcve, enterprise, hybrid, cloud, migrate, migration, disaster recovery, dr, backup, burst 
summary:  
---
= Soluzioni NetApp per VMware negli hyperscaler
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
Scopri di più sulle soluzioni offerte da NetApp per l'ambiente VMware in ciascuno degli hyperscaler, dalla migrazione dei flussi di lavoro, dall'estensione/diffusione al cloud, al backup/ripristino e al disaster recovery.



== Soluzioni NetApp per ambienti VMware

Sia che operiate in un modello di cloud ibrido o in un modello "cloud first", NetApp offre un'ampia gamma di soluzioni per affrontare i casi di utilizzo più comuni per la gestione dei carichi di lavoro in un modello di cloud o cloud ibrido.

NetApp offre anche soluzioni per lo storage con provisioning come storage in-guest (connesso al guest) o come datastore NFS supplementare in ciascuno degli hyperscaler. Tutte le soluzioni sono classificate in base alla classificazione VMware dei carichi di lavoro cloud. Tali classificazioni includono:

* Protect (include disaster recovery e backup/ripristino)
* Migrare
* Estendi


Per ulteriori informazioni sulle soluzioni disponibili per ciascun hyperscaler, visitare il sito:

* link:aws-solutions.html["Soluzioni per AWS/VMC"]
* link:azure-solutions.html["Soluzioni per Azure / AVS"]
* link:gcp-solutions.html["Soluzioni per GCP/GCVE"]

