---
sidebar: sidebar 
permalink: ehc/ehc-use-cases.html 
keywords: NetApp Solutions, ehc, enterprise hybrid cloud, use case, hyperscalers, vmware 
summary:  
---
= Casi di utilizzo per NetApp Hybrid Multibloud con VMware
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
Panoramica dei casi di utilizzo importanti per l'organizzazione IT durante la pianificazione di implementazioni cloud ibrido o cloud-first.



== Casi di utilizzo più comuni

I casi di utilizzo includono:

* Disaster recovery,
* Hosting dei carichi di lavoro durante la manutenzione del data center, * rapida esplosione in cui sono richieste risorse aggiuntive oltre a quanto previsto nel data center locale,
* Espansione del sito VMware,
* Migrazione rapida al cloud,
* Dev/test, e.
* Modernizzazione delle applicazioni sfruttando le tecnologie supplementari del cloud.


In questa documentazione, i riferimenti al workload cloud verranno dettagliati utilizzando i casi di utilizzo di VMware. Questi casi di utilizzo sono:

* Protect (include disaster recovery e backup/ripristino)
* Migrare
* Estendi




=== Dentro il percorso DELL'IT

La maggior parte delle organizzazioni è in viaggio verso la trasformazione e la modernizzazione. Nell'ambito di questo processo, le aziende stanno cercando di utilizzare gli investimenti VMware esistenti, sfruttando al contempo i vantaggi del cloud e esplorando i modi per rendere il processo di migrazione il più possibile perfetto. Questo approccio renderebbe molto semplice il loro impegno di modernizzazione perché i dati sono già nel cloud.

La risposta più semplice a questo scenario è rappresentata dalle offerte VMware in ogni hyperscaler. Come NetApp® Cloud Volumes, VMware offre un modo per spostare o estendere ambienti VMware on-premise su qualsiasi cloud, consentendo di mantenere risorse, competenze e strumenti on-premise esistenti durante l'esecuzione nativa dei carichi di lavoro nel cloud. Questo riduce i rischi perché non ci saranno interruzioni di servizio o necessità di modifiche IP e offre al team IT la possibilità di operare nel modo in cui si svolgono on-premise utilizzando le competenze e gli strumenti esistenti. Questo può portare a migrazioni del cloud accelerate e a una transizione molto più fluida verso un'architettura multicloud ibrida.



=== Comprendere l'importanza delle opzioni di storage NFS supplementari

Mentre VMware in qualsiasi cloud offre funzionalità ibride uniche a tutti i clienti, opzioni di storage NFS supplementari limitate hanno limitato la sua utilità per le organizzazioni con carichi di lavoro elevati in termini di storage. Poiché lo storage è direttamente legato agli host, l'unico modo per scalare lo storage è aggiungere più host, e questo può aumentare i costi del 35-40% o più per i carichi di lavoro a elevato utilizzo dello storage. Questi carichi di lavoro necessitano solo di storage aggiuntivo, non di potenza aggiuntiva. Ma ciò significa pagare per altri host.

Consideriamo questo scenario:

Un cliente richiede solo cinque host per CPU e memoria, ma ha molte esigenze di storage e ha bisogno di 12 host per soddisfare i requisiti di storage. Questo requisito finisce per mettere a punto la scala finanziaria dovendo acquistare la potenza aggiuntiva, quando è necessario solo incrementare lo storage.

Quando stai pianificando l'adozione e la migrazione del cloud, è sempre importante valutare l'approccio migliore e seguire il percorso più semplice per ridurre gli investimenti totali. L'approccio più comune e più semplice per qualsiasi migrazione applicativa è il rehosting (noto anche come Lift and Shift) in cui non esiste una macchina virtuale (VM) o una conversione dei dati. L'utilizzo di NetApp Cloud Volumes con il software-defined data center (SDDC) VMware, integrando al contempo vSAN, offre un'opzione semplice di "lift-and-shift".
