---
sidebar: sidebar 
permalink: ehc/ehc-config-vmware-intro.html 
keywords: NetApp Solutions, amazon, vmc, aws, microsoft azure, avs, azure, google cloud, gcp, gcve, vmware managed cloud, enterprise, hybrid, cloud, config, configuration 
summary:  
---
= Configurazione dell'ambiente di virtualizzazione nel cloud provider
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
I dettagli su come configurare l'ambiente di virtualizzazione in ciascuno degli hyperscaler supportati sono illustrati qui.

[role="tabbed-block"]
====
.AWS/VMC
--
Questa sezione descrive come configurare e gestire VMware Cloud su AWS SDDC e utilizzarlo in combinazione con le opzioni disponibili per la connessione dello storage NetApp.


NOTE: Lo storage in-guest è l'unico metodo supportato per connettere Cloud Volumes ONTAP ad AWS VMC.

Il processo di installazione può essere suddiviso nei seguenti passaggi:

* Implementazione e configurazione di VMware Cloud per AWS
* Connetti VMware Cloud a FSX ONTAP


Visualizza i dettagli link:aws-setup.html["Procedura di configurazione per VMC"].

--
.Azure/AVS
--
Questa sezione descrive come configurare e gestire Azure VMware Solution e utilizzarla in combinazione con le opzioni disponibili per la connessione dello storage NetApp.


NOTE: Lo storage in-guest è l'unico metodo supportato per connettere Cloud Volumes ONTAP alla soluzione VMware Azure.

Il processo di installazione può essere suddiviso nei seguenti passaggi:

* Registrare il provider di risorse e creare un cloud privato
* Connettersi a un gateway di rete virtuale ExpressRoute nuovo o esistente
* Convalidare la connettività di rete e accedere al cloud privato


Visualizza i dettagli link:azure-setup.html["Procedura di configurazione per AVS"].

--
.GCP/GCVE
--
Questa sezione descrive come configurare e gestire GCVE e utilizzarlo in combinazione con le opzioni disponibili per la connessione dello storage NetApp.


NOTE: Lo storage in-guest è l'unico metodo supportato per connettere Cloud Volumes ONTAP e Cloud Volumes Services a GCVE.

Il processo di installazione può essere suddiviso nei seguenti passaggi:

* Implementare e configurare GCVE
* Attiva accesso privato a GCVE


Visualizza i dettagli link:gcp-setup.html["Procedura di configurazione per GCVE"].

--
====