---
sidebar: sidebar 
permalink: ehc/evs-mount-fsxn-conclusion.html 
keywords: Amazon, AWS, EVS, Elastic VMware Service, ONTAP, FSx 
summary: In questo articolo sono fornite istruzioni su come configurare FSx per ONTAP come storage esterno per Amazon EVS da utilizzare con i protocolli NFS e iSCSI. 
---
= Conclusione
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
In questo documento sono fornite istruzioni su come configurare FSx per ONTAP come storage esterno per Amazon EVS da utilizzare con i protocolli NFS e iSCSI.

L'utilizzo di FSx for ONTAP come storage esterno per Amazon EVS offre chiari vantaggi operativi e di business. Offre una migliore resilienza dei dati, protezione, replicazione ed efficienza dei costi grazie alla tecnologia ONTAP, mantenendo al contempo un TCO ottimizzato grazie al disaccoppiamento dell'architettura iperconvergente VMware. Con FSx for ONTAP, gli utenti di Amazon EVS possono scalare lo storage senza aggiungere risorse di elaborazione e senza aumentare i costi. Questo consente di sfruttare appieno il potenziale di elasticità e scalabilità offerto dal cloud AWS.

Per saperne di più, leggi l'annuncio delle novità di Amazon: link:https://aws.amazon.com/about-aws/whats-new/2025/06/amazon-elastic-vmware-service-fsx-netapp-ontap/["Amazon EVS ora si integra con FSx per ONTAP"] e il blog di NetApp: link:https://www.netapp.com/blog/amazon-elastic-vmware-service-fsx-ontap/["Amazon EVS annuncia il supporto per FSx per ONTAP"] .
