---
sidebar: sidebar 
permalink: ehc/gcp-regions.html 
keywords: NetApp Solutions, google cloud, gcp, gcve, regions 
summary:  
---
= Disponibilità regionale: Datastore NFS supplementare per Google Cloud Platform (GCP)
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
Scopri di più sul supporto Global Region per GCP, GCVE e CVS.


NOTE: L'archivio dati NFS sarà disponibile nelle aree in cui sono disponibili entrambi i servizi (GCVE e prestazioni CVS).

Il datastore NFS supplementare per GCVE è supportato con il servizio volumi cloud di NetApp.


NOTE: Solo i volumi CVS-Performance possono essere utilizzati per GCVE NFS Datastore.
Per la posizione disponibile, fare riferimento a. link:https://bluexp.netapp.com/cloud-volumes-global-regions#cvsGc["Mappa geografica globale"]

Google Cloud VMware Engine è disponibile nelle seguenti posizioni immagine::gcve_regions_Mar2023.png[] per ridurre al minimo la latenza, il volume CVS di NetApp e GCVE in cui si intende montare il volume devono trovarsi nella stessa zona di disponibilità. Collabora con gli architetti delle soluzioni Google e NetApp per ottenere le ottimizzazioni di disponibilità e TCO.
