---
sidebar: sidebar 
permalink: ehc/ncvs-gc-control-plane-architecture.html 
keywords: identity, access, management, authorization, permission, service accounts, cloud volumes service api, jwt tokens 
summary: 'Tutte le azioni di gestione in Google Cloud NetApp Volumes vengono eseguite tramite API. La gestione di Google Cloud NetApp Volumes integrata nella console cloud GCP utilizza anche l"API di Google Cloud NetApp Volumes.' 
---
= Architettura del piano di controllo
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Tutte le azioni di gestione in Google Cloud NetApp Volumes vengono eseguite tramite API. La gestione di Google Cloud NetApp Volumes integrata nella console cloud GCP utilizza anche l'API di Google Cloud NetApp Volumes.



== Gestione di identità e accessi

Identity and Access Management (https://cloud.google.com/iam/docs/overview["IAM"^]) è un servizio standard che consente di controllare l'autenticazione (accessi) e l'autorizzazione (autorizzazioni) per le istanze di progetto di Google Cloud. Google IAM offre un audit trail completo delle autorizzazioni di autorizzazione e rimozione. Attualmente Google Cloud NetApp Volumes non fornisce l'audit dei piani di controllo.



=== Panoramica delle autorizzazioni

IAM offre permessi granulari integrati per Google Cloud NetApp Volumes. È possibile trovare un https://cloud.google.com/architecture/partners/netapp-cloud-volumes/security-considerations?hl=en_US["completa l'elenco delle autorizzazioni granulari qui"^].

IAM offre anche due ruoli predefiniti chiamati `netappcloudvolumes.admin` e. `netappcloudvolumes.viewer`. Questi ruoli possono essere assegnati a specifici utenti o account di servizio.

Assegnare ruoli e autorizzazioni appropriati per consentire agli utenti IAM di gestire Google Cloud NetApp Volumes.

Di seguito sono riportati alcuni esempi di utilizzo delle autorizzazioni granulari:

* Creare un ruolo personalizzato con solo autorizzazioni Get/List/create/Update in modo che gli utenti non possano eliminare i volumi.
* Utilizzare un ruolo personalizzato solo con `snapshot.*` Autorizzazioni per creare un account di servizio utilizzato per creare un'integrazione Snapshot coerente con l'applicazione.
* Creare un ruolo personalizzato da delegare `volumereplication.*` a utenti specifici.




=== Account di servizio

Per effettuare chiamate alle API di Google Cloud NetApp Volumes tramite script o https://registry.terraform.io/providers/NetApp/netapp-gcp/latest/docs["Terraform"^], è necessario creare un account di servizio con il `roles/netappcloudvolumes.admin` ruolo. È possibile utilizzare questo account di servizio per generare i token JWT necessari per autenticare le richieste API di Google Cloud NetApp Volumes in due modi diversi:

* Generare una chiave JSON e utilizzare le API di Google per derivare un token JWT da essa. Questo è l'approccio più semplice, ma implica la gestione manuale dei segreti (la chiave JSON).
* Utilizzare https://cloud.google.com/iam/docs/impersonating-service-accounts["Rappresentazione dell'account di servizio"^] con `roles/iam.serviceAccountTokenCreator`. Il codice (script, Terraform e così via). funziona con https://google.aip.dev/auth/4110["Credenziali predefinite dell'applicazione"^] e rappresenta l'account del servizio per ottenere le autorizzazioni. Questo approccio riflette le Best practice di sicurezza di Google.


Vedere https://cloud.google.com/architecture/partners/netapp-cloud-volumes/api?hl=en_US["Creazione dell'account di servizio e della chiave privata"^] Nella documentazione di Google Cloud per ulteriori informazioni.



== API Google Cloud NetApp Volumes

Google Cloud NetApp Volumes API utilizza un'API basata su REST utilizzando HTTPS (TLSv1,2) come trasporto di rete sottostante. È possibile trovare la definizione API più recente https://cloudvolumesgcp-api.netapp.com/swagger.json["qui"^] e le informazioni su come utilizzare l'API all'indirizzo https://cloud.google.com/architecture/partners/netapp-cloud-volumes/api?hl=en_US["Cloud Volumes API nella documentazione cloud di Google"^].

L'endpoint API viene gestito e protetto da NetApp utilizzando la funzionalità HTTPS standard (TLSv1.2).



=== Token JWT

L'autenticazione all'API viene eseguita con token bearer JWT (https://datatracker.ietf.org/doc/html/rfc7519["RFC-7519"^]). I token JWT validi devono essere ottenuti utilizzando l'autenticazione IAM di Google Cloud. A tale scopo, è necessario recuperare un token da IAM fornendo una chiave JSON dell'account di servizio.



== Registrazione dell'audit

Attualmente, non sono disponibili registri di audit del piano di controllo accessibili dall'utente.
