---
sidebar: sidebar 
permalink: ehc/ncvs-gc-overview.html 
keywords: 4918, tr4918, overview, introduction, scope, audience, abbreviation, definition 
summary: 'La sicurezza, in particolare nel cloud in cui l"infrastruttura non è sotto il controllo degli amministratori dello storage, è fondamentale per affidare i tuoi dati alle offerte di servizi fornite dai cloud provider. Questo documento offre una panoramica delle offerte di sicurezza offerte da NetApp Cloud Volumes Service in Google Cloud.' 
---
= TR-4918: Panoramica sulla sicurezza - NetApp Cloud Volumes Service in Google Cloud
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


Oliver Krause, Justin Parisi, NetApp



== Scopo del documento

La sicurezza, in particolare nel cloud in cui l'infrastruttura non è sotto il controllo degli amministratori dello storage, è fondamentale per affidare i tuoi dati alle offerte di servizi fornite dai cloud provider. Questo documento offre una panoramica delle offerte di sicurezza offerte da NetApp https://cloud.netapp.com/cloud-volumes-service-for-gcp["Cloud Volumes Service è disponibile in Google Cloud"^].



== Pubblico previsto

I destinatari del presente documento includono, a titolo esemplificativo e non esaustivo, i seguenti ruoli:

* Cloud provider
* Amministratori dello storage
* Architetti dello storage
* Risorse sul campo
* Decision maker aziendali


In caso di domande sul contenuto di questo report tecnico, consulta la sezione link:ncvs-gc-additional-information.html#contact-us[""Contattaci.""]

|===
| Abbreviazione | Definizione 


| CVS-SW | Cloud Volumes Service, CVS tipo di servizio 


| Performance CVS | Cloud Volume Service, tipo di servizio CVS-Performance 


| PSA |  
|===