---
sidebar: sidebar 
permalink: ehc/ncvs-gc-overview.html 
keywords: 4918, tr4918, overview, introduction, scope, audience, abbreviation, definition 
summary: 'La sicurezza, in particolare nel cloud in cui l"infrastruttura non è sotto il controllo degli amministratori dello storage, è fondamentale per affidare i tuoi dati alle offerte di servizi fornite dai cloud provider. Questo documento offre una panoramica delle offerte di sicurezza offerte da Google Cloud NetApp Volumes in Google Cloud.' 
---
= TR-4918: Panoramica sulla sicurezza - Google Cloud NetApp Volumes in Google Cloud
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


Oliver Krause, Justin Parisi, NetApp

[role="lead"]
La sicurezza, in particolare nel cloud in cui l'infrastruttura non è sotto il controllo degli amministratori dello storage, è fondamentale per affidare i tuoi dati alle offerte di servizi fornite dai cloud provider. Questo documento fornisce una panoramica delle offerte di protezione di https://cloud.netapp.com/cloud-volumes-service-for-gcp["Google Cloud NetApp Volumes offre in Google Cloud"^].



== Pubblico previsto

I destinatari del presente documento includono, a titolo esemplificativo e non esaustivo, i seguenti ruoli:

* Cloud provider
* Amministratori dello storage
* Architetti dello storage
* Risorse sul campo
* Decision maker aziendali


In caso di domande sul contenuto di questo report tecnico, consulta la sezione link:ncvs-gc-additional-information.html#contact-us[""Contattaci.""]

|===
| Abbreviazione | Definizione 


| Volumi NetApp-SW | Google Cloud NetApp Volumes, tipo di servizio NetApp Volumes 


| Volumi NetApp: Performance | Cloud Volume Service, tipo di servizio NetApp Volumes-Performance 


| PSA |  
|===