---
sidebar: sidebar 
permalink: containers/tanzu_with_netapp/vtwn_videos_and_demos.html 
keywords: video, demonstration, deployment, VMware Tanzu with NetApp, NetApp, Tanzu 
summary: Questa pagina contiene collegamenti a video che mostrano alcune delle funzionalità descritte in questo documento. 
---
= Video e demo: VMware Tanzu con NetApp
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../../media/


[role="lead"]
I seguenti video mostrano alcune delle funzionalità descritte in questo documento:

.Utilizza Astra Trident per eseguire il provisioning dello storage persistente in VMware Tanzu - VMware Tanzu con NetApp
video::8db3092b-3468-4754-b2d7-b01200fbb38d[panopto,width=360]
.Utilizza il centro di controllo Astra per clonare le applicazioni in VMware Tanzu - VMware Tanzu con NetApp
video::01aff358-a0a2-4c4f-9062-b01200fb9abd[panopto,width=360]

NOTE: Queste demo sono state registrate come anteprima tecnica utilizzando la versione 1.3.1 di TKG e la versione 21,12 di Astra Control Center. Consulta la matrice di supporto per le versioni ufficiali supportate.
NOTA: Queste demo sono state registrate come anteprima tecnica utilizzando la versione 1.3.1 di TKG e la versione 21,12 di Astra Control Center. Consulta la matrice di supporto per le versioni ufficiali supportate.

link:vtwn_additional_information.html["Pagina successiva: Ulteriori informazioni: VMware Tanzu con NetApp."]
