---
sidebar: sidebar 
permalink: containers/anthos-with-netapp/a-w-n_LB_MetalLB.html 
summary: In questa pagina sono riportate le istruzioni di installazione e configurazione per il bilanciamento del carico MetalLB. 
keywords: Anthos, Kubernetes, MetalLB, LoadBalancer, Astra, Astra Control Center 
---
= Installazione dei bilanciatori di carico MetalLB
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../../media/


[role="lead"]
Questa pagina elenca le istruzioni di installazione e configurazione per il bilanciamento del carico gestito da MetalLB.



== Installazione del bilanciamento del carico MetalLB

Il bilanciamento del carico MetalLB è completamente integrato con i cluster anthos su VMware e ha eseguito l'implementazione automatica come parte delle configurazioni dei cluster Admin e User a partire dalla release 1.11. Vi sono blocchi di testo nei rispettivi `cluster.yaml` file di configurazione che è necessario modificare per fornire informazioni sul bilanciamento del carico. Viene eseguito in hosting automatico sul cluster anthos invece di richiedere l'implementazione di risorse esterne come le altre soluzioni di bilanciamento del carico supportate. Consente inoltre di creare un pool ip che assegna automaticamente gli indirizzi con la creazione di servizi Kubernetes di tipo bilanciamento del carico in cluster che non vengono eseguiti su un provider cloud.



== Integrazione con anthos

Quando si attiva il bilanciamento del carico di MetalLB per l'amministratore di anthos, è necessario modificare alcune righe in `loadBalancer:` che esiste in `admin-cluster.yaml` file. Gli unici valori che è necessario modificare sono l'impostazione di `controlPlaneVIP:` quindi impostare `kind:` Come MetalLB. Vedere il seguente frammento di codice per un esempio:

[listing]
----
# (Required) Load balancer configuration
loadBalancer:
  # (Required) The VIPs to use for load balancing
  vips:
    # Used to connect to the Kubernetes API
    controlPlaneVIP: "10.61.181.230"
    # # (Optional) Used for admin cluster addons (needed for multi cluster features). Must
    # # be the same across clusters
    # addonsVIP: ""
  # (Required) Which load balancer to use "F5BigIP" "Seesaw" "ManualLB" or "MetalLB".
  # Uncomment the corresponding field below to provide the detailed spec
  kind: MetalLB
----
Quando si abilita il bilanciamento del carico MetalLB per i cluster di utenti anthos, vi sono due aree in ciascuna `user-cluster.yaml` file da aggiornare. In primo luogo, in modo simile a. `admin-cluster.yaml` modificare il `controlPlaneVIP:`, `ingressVIP:`, e. `kind:` valori in `loadBalancer:` sezione. Vedere il seguente frammento di codice per un esempio:

[listing]
----
loadBalancer:
  # (Required) The VIPs to use for load balancing
  vips:
    # Used to connect to the Kubernetes API
    controlPlaneVIP: "10.61.181.240"
    # Shared by all services for ingress traffic
    ingressVIP: "10.61.181.244"
  # (Required) Which load balancer to use "F5BigIP" "Seesaw" "ManualLB" or "MetalLB".
  # Uncomment the corresponding field below to provide the detailed spec
  kind: MetalLB
----

NOTE: L'indirizzo IP entressVIP deve trovarsi all'interno del pool di indirizzi IP assegnati al bilanciamento del carico MetalLB in un secondo momento della configurazione.

Quindi, accedere a `metalLB:` sottosezione e modificare `addressPools:` assegnando un nome al pool in `- name:` variabile. È inoltre necessario creare un pool di indirizzi ip che MetalLB può assegnare ai servizi di tipo LoadBalancer fornendo un intervallo a `addresses:` variabile.

[listing]
----
# # (Required when using "MetalLB" kind in user clusters) Specify the MetalLB config
 metalLB:
 #   # (Required) A list of non-overlapping IP pools used by load balancer typed services.
 #   # Must include ingressVIP of the cluster.
    addressPools:
 #   # (Required) Name of the address pool
    - name: "default"
 #     # (Required) The addresses that are part of this pool. Each address must be either
 #     # in the CIDR form (1.2.3.0/24) or range form (1.2.3.1-1.2.3.5).
      addresses:
      - "10.61.181.244-10.61.181.249"
----

NOTE: Il pool di indirizzi può essere fornito come un intervallo come nell'esempio, limitandolo a un numero di indirizzi in una particolare subnet, oppure può essere fornito come notazione CIDR se l'intera subnet è resa disponibile.

. Quando vengono creati servizi Kubernetes di tipo LoadBalancer, MetalLB assegna automaticamente un IP esterno ai servizi e annuncia l'indirizzo IP rispondendo alle richieste ARP.


link:a-w-n_LB_SeeSaw.html["Avanti: Installazione dei bilanciatori di carico seesaw."]
