---
sidebar: sidebar 
permalink: vmw-sc/sc-overview.html 
keywords: NetApp Solutions, vmware, sovereign cloud 
summary:  
---
= Panoramica di VMware Sovereign Cloud
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
Il concetto di sovranità sta emergendo come componente necessario del cloud computing per molte entità che elaborano e mantengono dati altamente sensibili, come ad esempio i governi nazionali e statali, e settori altamente regolamentati, come quello finanziario e sanitario. I governi nazionali stanno anche cercando di espandere la capacità economica digitale e di ridurre la dipendenza da aziende multinazionali per i propri servizi cloud.



== Iniziativa VMware Sovereign Cloud

VMware definisce un cloud sovrano che:

* Protegge e sblocca il valore dei dati critici (ad esempio, dati nazionali, dati aziendali e dati personali) sia per le organizzazioni del settore pubblico che privato
* Offre una capacità nazionale per l'economia digitale
* Protegge i dati con controlli di sicurezza verificati
* Garantisce la conformità alle leggi sulla privacy dei dati
* Migliora il controllo dei dati fornendo sia la residenza dei dati che la sovranità dei dati con un controllo giurisdizionale completo




== Partnership con un fornitore di servizi cloud VMware Sovereign di fiducia

Per garantire il successo, le organizzazioni devono collaborare con i partner di cui si fidano e che siano in grado di ospitare piattaforme cloud sovrane autentiche e autonome. I VMware Cloud Provider riconosciuti nell'ambito dell'iniziativa VMware Sovereign Cloud si impegnano a progettare e utilizzare soluzioni cloud basate su architetture software-defined moderne che incarnano i principi chiave e le Best practice delineate nel framework VMware Sovereign Cloud.

* *Sovranità dei dati e controllo giurisdizionale* – tutti i dati sono residenti e soggetti al controllo esclusivo e all'autorità dello Stato nazionale in cui sono stati raccolti. Le operazioni sono gestite completamente all'interno della giurisdizione
* *Accesso ai dati e integrità* – l'infrastruttura cloud è resiliente e disponibile in almeno due ubicazioni dei data center all'interno della giurisdizione con opzioni di connettività sicura e privata disponibili.
* *Sicurezza e conformità dei dati* – i controlli dei sistemi di gestione della sicurezza delle informazioni sono certificati in base a uno standard globale (o regionale) riconosciuto dal settore e sottoposti a verifiche periodiche.
* *Data Independence and Mobility* – supporto per le moderne architetture applicative per prevenire il vendor cloud lock-in e consentire la portabilità e l'indipendenza delle applicazioni


Per ulteriori informazioni su VMware, visitare il sito:

* link:https://www.vmware.com/content/dam/digitalmarketing/vmware/en/pdf/docs/vmw-sovereign-cloud-solution-brief-customer.pdf["Panoramica di VMware Sovereign Cloud"]
* link:https://www.vmware.com/topics/glossary/content/sovereign-cloud.html["Che cos'è VMware Sovereign Cloud?"]
* link:https://blogs.vmware.com/cloud/2021/10/06/vmware-sovereign-cloud/["Presentazione della nuova VMware Sovereign Cloud Initiative"]
* link:https://www.vmware.com/content/dam/learn/en/amer/fy22/pdf/1173457_Sovereign_Cloud_Technical_Whitepaper_V3.pdf["White paper tecnico su VMware Sovereign Cloud"]

