---
sidebar: sidebar 
permalink: vmw-sc/sc-use-cases.html 
keywords: NetApp Solutions, vmware, sovereign cloud, netapp, use case 
summary:  
---
= Netpp con VMware Sovereign Cloud: Casi di utilizzo
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
NetApp offre supporto per i concetti di VMware Sovereign Cloud attraverso l'integrazione di diverse tecnologie NetApp.

Utilizza i seguenti link per scoprire di più sulle integrazioni della tecnologia NetApp con VMware Sovereign Cloud:

* link:#storageGRID["NetApp StorageGRID come estensione dell'archivio oggetti"]




== NetApp StorageGRID come estensione dell'archivio oggetti

NetApp ha collaborato con VMware per integrare NetApp StorageGRID in VMware Cloud Director a supporto di VMware Sovereign Cloud. Questo plug-in di VMware Cloud Director consente ai service provider di utilizzare StorageGRID come offerta di storage a oggetti (indipendentemente dai casi d'utilizzo) e permette la gestione StorageGRID tramite la stessa soluzione VMware multi-tenant (VMware Cloud Director) utilizzata dai service provider per gestire altre parti del proprio catalogo di offerte.

I partner che offrono VMware Sovereign Cloud possono scegliere NetApp StorageGRID per gestire e mantenere ambienti cloud con dati non strutturati. La sua compatibilità universale nel supporto nativo per le API standard di settore, come le API Amazon S3, garantisce un'interoperabilità fluida su diversi ambienti cloud e innovazioni uniche, come la gestione automatizzata del ciclo di vita, contribuisce a garantire una protezione, uno storage e una conservazione a lungo termine dei dati non strutturati dei clienti con costi più contenuti.

L'integrazione di NetApp Sovereign Cloud con i clienti provider Cloud Director con:

* La garanzia che i dati sensibili, inclusi i metadati, rimangano sotto controllo sovrano impedendo al contempo l'accesso da parte di autorità straniere che potrebbero violare le leggi sulla privacy dei dati.
* Maggiore sicurezza e conformità per la protezione di applicazioni e dati da vettori di attacco in rapida evoluzione e al contempo garantire la conformità a un ambiente locale affidabile. infrastruttura, framework integrati ed esperti locali.
* Un'infrastruttura a prova di futuro per reagire rapidamente alle normative sulla privacy dei dati in continua evoluzione, alle minacce alla sicurezza e alla geopolitica.
* La possibilità di liberare il valore dei dati con condivisione e analisi sicure dei dati per favorire l'innovazione senza violare le leggi sulla privacy. L'integrità dei dati è protetta per garantire informazioni accurate.


Per ulteriori informazioni sull'integrazione di StorageGRID, consulta:

* link:https://www.netapp.com/newsroom/press-releases/news-rel-20231107-561294/["Annuncio NetApp"]

