---
sidebar: sidebar 
permalink: containers/a-w-n_solution_overview.html 
keywords: NVA-1165, Anthos, GKE, Netapp, Trident 
summary: 'Questo documento di riferimento fornisce la convalida dell"implementazione della soluzione anthos con NetApp, implementata in più ambienti di data center, convalidata da NetApp e dai nostri partner di progettazione.' 
---
= NVA-1165: Anthos con NetApp
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


Banu Sundhar e Suresh Thoppay, NetApp

[role="lead"]
Questo documento di riferimento fornisce la convalida dell'implementazione della soluzione anthos con NetApp da parte di NetApp e dei nostri partner tecnici quando viene implementata in più ambienti di data center. Descrive inoltre l'integrazione dello storage con i sistemi storage NetApp utilizzando Trident Storage orchestrator per la gestione dello storage persistente. Infine, esploriamo e documentiamo una serie di validazioni delle soluzioni e casi di utilizzo reali.



== Casi di utilizzo

La soluzione anthos con NetApp è progettata per offrire un valore eccezionale ai clienti con i seguenti casi di utilizzo:

* Facile da implementare e gestire l'ambiente anthos implementato utilizzando il fornito `bmctl` su metallo nudo o su `gkectl` Su VMware vSphere.
* Potenza combinata di container Enterprise e carichi di lavoro virtualizzati con anthos implementato virtualmente su vSphere o su bare metal con https://cloud.google.com/anthos/clusters/docs/bare-metal/1.9/how-to/vm-workloads["kubivirt"^].
* Configurazione reale e casi d'utilizzo che evidenziano le funzionalità anthos quando vengono utilizzate con storage NetApp e Trident, l'orchestrator di storage open-source per Kubernetes.




== Valore di business

Le aziende stanno adottando sempre più pratiche DevOps per creare nuovi prodotti, abbreviare i cicli di rilascio e aggiungere rapidamente nuove funzionalità. A causa della loro natura innata e agile, i container e i microservizi svolgono un ruolo cruciale nel supporto delle pratiche DevOps. Tuttavia, la pratica di DevOps su scala di produzione in un ambiente aziendale presenta le proprie sfide e impone determinati requisiti all'infrastruttura sottostante, come ad esempio:

* Alta disponibilità a tutti i livelli dello stack
* Procedure di implementazione semplici
* Operazioni e aggiornamenti senza interruzioni
* Infrastruttura programmabile e basata su API per restare al passo con l'agilità dei microservizi
* Multi-tenancy con garanzie di performance
* Possibilità di eseguire workload virtualizzati e containerizzati contemporaneamente
* Possibilità di scalare l'infrastruttura in modo indipendente in base alle esigenze dei carichi di lavoro


La soluzione anthos con NetApp riconosce queste sfide e presenta una soluzione che aiuta a risolvere ogni problema implementando l'implementazione completamente automatica di anthos in maniera prematura nell'ambiente di data center scelto dal cliente.



== Panoramica della tecnologia

La soluzione anthos con NetApp comprende i seguenti componenti principali:



=== Anthos on Prem

Anthos on Prem è una piattaforma Kubernetes aziendale completamente supportata che può essere implementata nell'hypervisor VMware vSphere o su un'infrastruttura bare metal di tua scelta.

Per ulteriori informazioni su anthos, visitare il sito Web di anthos all'indirizzo https://cloud.google.com/anthos["qui"^].



=== Sistemi storage NetApp

NetApp dispone di diversi sistemi storage perfetti per data center aziendali e implementazioni di cloud ibrido. Il portfolio NetApp include NetApp ONTAP, Cloud Volumes ONTAP, Google Cloud NetApp Volumes, Azure NetApp Files, FSX ONTAP per i sistemi storage NetApp ONTAP, tutti sistemi che offrono storage persistente per le applicazioni in container.

Per ulteriori informazioni, visitare il sito Web di NetApp https://www.netapp.com["qui"].



=== Integrazioni di storage NetApp

Trident è un orchestrator di storage open-source e pienamente supportato per container e distribuzioni Kubernetes, incluso anthos.

Per ulteriori informazioni, visitare il sito Web Trident https://docs.netapp.com/us-en/trident/index.html["qui"] .



== Opzioni di configurazione avanzate

Questa sezione è dedicata alle personalizzazioni che gli utenti reali dovrebbero eseguire durante l'implementazione di questa soluzione in produzione, ad esempio la creazione di un registro di immagini private dedicato o l'implementazione di istanze personalizzate di bilanciamento del carico.



== Matrice di supporto corrente per le release validate

Vedere https://cloud.google.com/anthos/docs/resources/partner-storage#netapp["qui"] per la matrice di supporto per le release validate.
