---
sidebar: sidebar 
permalink: containers/a-w-n_overview_storint.html 
keywords: Astra, Astra Control Center, Trident, Astra Trident, persistent storage 
summary: 'NetApp offre una serie di prodotti che assistono i nostri clienti nell"orchestrazione e nella gestione dei dati persistenti in ambienti basati su container come anthos.' 
---
= Panoramica sull'integrazione dello storage NetApp
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/




== Programma per partner di storage anthos Ready.

Google Cloud richiede periodicamente la convalida aggiornata delle integrazioni di storage dei partner con le nuove release di anthos attraverso il programma per partner di storage anthos Ready. È possibile trovare un elenco delle soluzioni storage attualmente validate, dei driver CSI, delle funzionalità disponibili e delle versioni di anthos supportate https://cloud.google.com/anthos/docs/resources/partner-storage["qui"^].

NetApp ha mantenuto una conformità regolare su base trimestrale con le richieste di validare il nostro orchestrator di storage conforme a Astra Trident CSI e il nostro sistema di storage ONTAP con le versioni di anthos.

La tabella seguente contiene le versioni anthos testate dai tecnici dei partner NetApp e NetApp per la convalida dei driver e delle funzionalità di NetApp Astra Trident CSI nell'ambito del programma per partner di storage anthos Ready:

|===


| Tipo di implementazione | Versione | Sistema storage | Versione di Astra Trident | Protocollo | Caratteristiche 


| VMware | 1.15 | ONTAP 9.12.1 | 23.04 | NAS | Multiwriter, espansione dei volumi, snapshot, PVCDataSource 


| VMware | 1.15 | ONTAP 9.12.1 | 23.04 | SAN | Blocco raw, espansione dei volumi, snapshot, PVCDataSource 


| VMware | 1.14 | ONTAP 9.12.1 | 23.01 | NAS | Multiwriter, espansione dei volumi, snapshot, PVCDataSource 


| VMware | 1.14 | ONTAP 9.12.1 | 23.01 | SAN | Blocco raw, espansione dei volumi, snapshot, PVCDataSource 


| VMware | 1.13 | ONTAP 9.12.1 | 22.10 | NAS | Multiwriter, espansione dei volumi, snapshot, PVCDataSource 


| VMware | 1.13 | ONTAP 9.12.1 | 22.10 | SAN | Blocco raw, espansione dei volumi, snapshot, PVCDataSource 


| VMware | 1.11 | ONTAP 9.9.1 | 22.04 | NAS | Multivriter, Volume Expansion, snapshot 


| VMware | 1.11 | ONTAP 9.9.1 | 22.04 | SAN | Blocco raw, espansione del volume, snapshot 


| VMware | 1.11 | Elemento 12.3 | 22.04 | SAN | Blocco raw, espansione del volume, snapshot 


| metallo nudo | 1.10 | ONTAP 9.8 | 22.01 | NAS | Multivriter, Volume Expansion, snapshot 


| metallo nudo | 1.10 | ONTAP 9.8 | 22.01 | SAN | Blocco raw, espansione del volume, snapshot 
|===


== Integrazioni di storage NetApp

NetApp offre una serie di prodotti che consentono di orchestrare e gestire i dati persistenti in ambienti basati su container come Anthos.

NetApp Astra Trident è un orchestrator di storage open-source e completamente supportato per container e distribuzioni Kubernetes, incluso Anthos. Per ulteriori informazioni, visita il sito web di Astra Trident https://docs.netapp.com/us-en/trident/index.html["qui"].

Le pagine seguenti contengono informazioni aggiuntive sui prodotti NetApp validati per la gestione delle applicazioni e dello storage persistente nella soluzione anthos con NetApp.
