---
sidebar: sidebar 
permalink: containers/rh-os-n_videos_and_demos.html 
keywords: video, demonstration, deployment 
summary:  
---
= Video e demo: Red Hat OpenShift con NetApp
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
I seguenti video mostrano alcune delle funzionalità documentate in questo documento:

.Integrazione di Cloud Insights con la virtualizzazione OpenShift
video::29ed6938-eeaf-4e70-ae7b-b15d011d75ff[panopto,width=360]
.Utilizzo di Red Hat MTV per migrare le VM alla virtualizzazione OpenShift con lo storage NetApp ONTAP
video::bac58645-dd75-4e92-b5fe-b12b015dc199[panopto,width=360]
.Accelera lo sviluppo del software con Astra Control e la tecnologia NetApp FlexClone - Red Hat OpenShift con NetApp
video::26b7ea00-9eda-4864-80ab-b01200fa13ac[panopto,width=360]
.Sfrutta NetApp Astra Control per eseguire l'analisi post-mortem e ripristinare l'applicazione
video::3ae8eb53-eda3-410b-99e8-b01200fa30a8[panopto,width=360]
.Data Protection in pipeline ci/CD con Astra Control Center
video::a6400379-52ff-4c8f-867f-b01200fa4a5e[panopto,width=360]
.Migrazione dei workload con Centro di controllo Astra - Red Hat OpenShift con NetApp
video::e397e023-5204-464d-ab00-b01200f9e6b5[panopto,width=360]
.Migrazione dei workload - Red Hat OpenShift con NetApp
video::27773297-a80c-473c-ab41-b01200fa009a[panopto,width=360]
.Installazione della virtualizzazione OpenShift - Red Hat OpenShift con NetApp
video::e589a8a3-ce82-4a0a-adb6-b01200f9b907[panopto,width=360]
.Implementazione di una macchina virtuale con virtualizzazione OpenShift - Red Hat OpenShift con NetApp
video::8a29fa18-8643-499e-94c7-b01200f9ce11[panopto,width=360]
.NetApp HCI per Red Hat OpenShift sulla virtualizzazione Red Hat
video::13b32159-9ea3-4056-b285-b01200f0873a[panopto,width=360]