---
sidebar: sidebar 
permalink: containers/rh-os-n_use_case_openshift_virtualization_rosa_prerequisites.html 
keywords: OpenShift, OCP, Trident, NetApp ONTAP, Red Hat OpenShift, OpenShift Virtualization, ROSA, CNV, Container Native Virtualization, Red Hat OpenShift Virtualization 
summary: Red Hat OpenShift Virtualization su ROSA 
---
= Implementa Red Hat OpenShift Virtualization con FSxN su ROSA
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Questa sezione fornisce dettagli sulla configurazione di FSX per NetApp ONTAP come classe di storage predefinita per il cluster ROSA, quindi crea una macchina virtuale che sfrutti lo storage FSX ONTAP per i suoi volumi. Esamineremo anche la connessione alla macchina virtuale utilizzando le credenziali guest e il riavvio della macchina virtuale. Infine, eseguiremo una migrazione live della macchina virtuale dal nodo corrente a un nuovo nodo. Esamineremo il contenuto dello spazio di archiviazione su disco dopo il riavvio di una VM e la migrazione in tempo reale .



== Prerequisiti

* link:https://signin.aws.amazon.com/signin?redirect_uri=https://portal.aws.amazon.com/billing/signup/resume&client_id=signup["Account AWS"]
* link:https://console.redhat.com/["Un account Red Hat"]
* Utente IAM link:https://www.rosaworkshop.io/rosa/1-account_setup/["con autorizzazioni appropriate"]per creare e accedere al cluster ROSA
* link:https://aws.amazon.com/cli/["CLI AWS"]
* link:https://console.redhat.com/openshift/downloads["ROSA CLI"]
* link:https://console.redhat.com/openshift/downloads["Interfaccia a riga di comando OpenShift"] (oc)
* link:https://docs.aws.amazon.com/eks/latest/userguide/helm.html["Documentazione di Helm 3"]
* link:https://docs.openshift.com/rosa/rosa_hcp/rosa-hcp-sts-creating-a-cluster-quickly.html["UN CLUSTER HCP ROSA"] (con almeno 3 nodi di lavoro bare-metal)
* link:https://docs.redhat.com/en/documentation/openshift_container_platform/4.17/html/virtualization/installing#virt-aws-bm_preparing-cluster-for-virt["OpenShift Virtualization installato su ROSA Cluster"]
* link:https://console.redhat.com/openshift/overview["Accesso alla console web Red Hat OpenShift"]

