---
sidebar: sidebar 
permalink: containers/rh-os-n_solution_overview.html 
keywords: NVA-1160, Red Hat, OpenShift, Netapp, Trident 
summary: 'Questo documento di riferimento fornisce la convalida dell"implementazione della soluzione Red Hat OpenShift, implementata tramite l"infrastruttura IPI (Installer Provised Infrastructure) in diversi ambienti di data center come validati da NetApp. Descrive inoltre l"integrazione dello storage con i sistemi storage NetApp utilizzando Trident Storage orchestrator per la gestione dello storage persistente. Infine, vengono analizzate e documentate una serie di validazioni delle soluzioni e casi di utilizzo reali.' 
---
= NVA-1160: Red Hat OpenShift con NetApp
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


Alan Cowles e Nikhil M Kulkarni, NetApp

[role="lead"]
Questo documento di riferimento fornisce la convalida dell'implementazione della soluzione Red Hat OpenShift, implementata tramite l'infrastruttura IPI (Installer Provised Infrastructure) in diversi ambienti di data center come validati da NetApp. Descrive inoltre l'integrazione dello storage con i sistemi storage NetApp utilizzando Trident Storage orchestrator per la gestione dello storage persistente. Infine, vengono analizzate e documentate una serie di validazioni delle soluzioni e casi di utilizzo reali.



== Casi di utilizzo

La soluzione Red Hat OpenShift con NetApp è progettata per offrire un valore eccezionale ai clienti con i seguenti casi di utilizzo:

* Facile da implementare e gestire Red Hat OpenShift implementato utilizzando IPI (Installer Provised Infrastructure) su bare metal, Red Hat OpenStack Platform, Red Hat Virtualization e VMware vSphere.
* Potenza combinata dei container aziendali e dei carichi di lavoro virtualizzati con Red Hat OpenShift implementato virtualmente su OSP, RHV o vSphere o su bare metal con la virtualizzazione OpenShift.
* Configurazione reale e casi di utilizzo che evidenziano le funzionalità di Red Hat OpenShift quando utilizzato con storage NetApp e Trident, l'orchestrator di storage open source per Kubernetes.




== Valore di business

Le aziende stanno adottando sempre più pratiche DevOps per creare nuovi prodotti, abbreviare i cicli di rilascio e aggiungere rapidamente nuove funzionalità. A causa della loro natura innata e agile, i container e i microservizi svolgono un ruolo cruciale nel supporto delle pratiche DevOps. Tuttavia, la pratica di DevOps su scala di produzione in un ambiente aziendale presenta le proprie sfide e impone determinati requisiti all'infrastruttura sottostante, come ad esempio:

* Alta disponibilità a tutti i livelli dello stack
* Procedure di implementazione semplici
* Operazioni e aggiornamenti senza interruzioni
* Infrastruttura programmabile e basata su API per restare al passo con l'agilità dei microservizi
* Multi-tenancy con garanzie di performance
* Possibilità di eseguire contemporaneamente carichi di lavoro virtualizzati e containerizzati
* Possibilità di scalare l'infrastruttura in modo indipendente in base alle esigenze dei carichi di lavoro


Red Hat OpenShift con NetApp riconosce queste sfide e presenta una soluzione che aiuta a risolvere ogni problema implementando l'implementazione completamente automatizzata di RedHat OpenShift IPI nell'ambiente del data center scelto dal cliente.



== Panoramica della tecnologia

La soluzione Red Hat OpenShift con NetApp comprende i seguenti componenti principali:



=== Red Hat OpenShift Container Platform

Red Hat OpenShift Container Platform è una piattaforma aziendale Kubernetes completamente supportata. Red Hat apporta diversi miglioramenti a Kubernetes open-source per offrire una piattaforma applicativa con tutti i componenti completamente integrati per la creazione, l'implementazione e la gestione delle applicazioni containerizzate.

Per ulteriori informazioni, visita il sito Web di OpenShift https://www.openshift.com["qui"].



=== Sistemi storage NetApp

NetApp dispone di diversi sistemi storage perfetti per data center aziendali e implementazioni di cloud ibrido. Il portfolio NetApp include i sistemi storage NetApp ONTAP, NetApp Element e NetApp e-Series, tutti in grado di fornire storage persistente per le applicazioni containerizzate.

Per ulteriori informazioni, visitare il sito Web di NetApp https://www.netapp.com["qui"].



=== Integrazioni di storage NetApp

NetApp Astra Control offre un ricco set di servizi di gestione dei dati integrati con l'applicazione e di storage per i workload Kubernetes stateful, implementati in un ambiente on-premise e basati sull'affidabile tecnologia di protezione dei dati NetApp.

Per ulteriori informazioni, visitare il sito Web di NetApp Astra https://docs.netapp.com/us-en/astra-family/["qui"].

Trident è un orchestrator di storage open-source e completamente supportato per container e distribuzioni Kubernetes, incluso Red Hat OpenShift.

Per ulteriori informazioni, visitare il sito Web Trident https://docs.netapp.com/us-en/trident/index.html["qui"] .



== Opzioni di configurazione avanzate

Questa sezione è dedicata alle personalizzazioni che gli utenti reali dovrebbero eseguire durante l'implementazione di questa soluzione in produzione, ad esempio la creazione di un registro di immagini private dedicato o l'implementazione di istanze personalizzate di bilanciamento del carico.



== Matrice di supporto corrente per le release validate

|===


| Tecnologia | Scopo | Versione del software 


| NetApp ONTAP | Storage | 9,8, 9,9.1, 9.12.1 


| NetApp Element | Storage | 12.3 


| NetApp Astra Control | Gestione dei dati consapevole dell'applicazione | 21.12.60, 23,04, 23,07, 23,10, 24,02 


| Trident di NetApp | Orchestrazione dello storage | 22.01.0, 23,04, 23,07, 23,10, 24,02 


| Red Hat OpenShift | Orchestrazione di container | 4,6 EUS, 4,7, 4,8, 4,10, 4,11, 4,12, 4,13, 4,14 


| VMware vSphere | Virtualizzazione del data center | 7,0, 8.0.2 
|===