---
sidebar: sidebar 
permalink: containers/rh-os-n_use_case_openshift_virtualization_deployment_prerequisites.html 
keywords: OpenShift, OCP, Trident, NetApp ONTAP, Red Hat OpenShift, OpenShift Virtualization, CNV, Container Native Virtualization, Red Hat OpenShift Virtualization 
summary: Virtualizzazione Red Hat OpenShift con NetApp ONTAP 
---
= Implementa la virtualizzazione di Red Hat OpenShift con NetApp ONTAP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
In questa sezione viene descritto in dettaglio come implementare Red Hat OpenShift Virtualization con NetApp ONTAP.



== Prerequisiti

* Un cluster Red Hat OpenShift (successivo alla versione 4.6) installato su un'infrastruttura bare-metal con nodi di lavoro RHCOS
* Implementare i controlli dello stato delle macchine per mantenere l'ha per le macchine virtuali
* Un cluster NetApp ONTAP
* Trident installato sul cluster OpenShift
* Un backend Trident configurato con una SVM sul cluster ONTAP
* Una StorageClass configurata nel cluster OpenShift con Trident come provisioner
* Accesso cluster-admin al cluster Red Hat OpenShift
* Accesso amministrativo al cluster NetApp ONTAP
* Una workstation di amministrazione con tridentctl e oc tools installati e aggiunti al percorso dei dollari


Poiché la virtualizzazione OpenShift è gestita da un operatore installato sul cluster OpenShift, impone un overhead aggiuntivo su memoria, CPU e storage, che deve essere tenuto in considerazione durante la pianificazione dei requisiti hardware per il cluster. Consultare la documentazione https://docs.openshift.com/container-platform/4.7/virt/install/preparing-cluster-for-virt.html#virt-cluster-resource-requirements_preparing-cluster-for-virt["qui"] per ulteriori dettagli.

In alternativa, è possibile specificare un sottoinsieme dei nodi del cluster OpenShift per ospitare gli operatori, i controller e le macchine virtuali della virtualizzazione OpenShift configurando le regole di posizionamento dei nodi. Per configurare le regole di posizionamento dei nodi per la virtualizzazione OpenShift, seguire la documentazione https://docs.openshift.com/container-platform/4.7/virt/install/virt-specifying-nodes-for-virtualization-components.html["qui"].

Per il supporto dello storage OpenShift Virtualization, NetApp consiglia di disporre di un StorageClass dedicato che richieda storage da un particolare backend Trident, a sua volta supportato da una SVM dedicata. In questo modo si mantiene un livello di multi-tenancy in relazione ai dati serviti per i carichi di lavoro basati su macchine virtuali sul cluster OpenShift.
