---
sidebar: sidebar 
permalink: containers/rh-os-n_videos_and_demos.html 
keywords: video, demonstration, deployment 
summary:  
---
= Video e demo: Red Hat OpenShift con NetApp
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


I seguenti video mostrano alcune delle funzionalità documentate in questo documento:

[cols="5a, 5a, 5a"]
|===


 a| 
Accelera lo sviluppo del software con Astra Control e la tecnologia NetApp FlexClone - Red Hat OpenShift con NetApp

 a| 
Sfrutta NetApp Astra Control per eseguire l'analisi post-mortem e ripristinare l'applicazione

 a| 
Data Protection in pipeline ci/CD con Astra Control Center




 a| 
Migrazione dei workload con Centro di controllo Astra - Red Hat OpenShift con NetApp

 a| 
Migrazione dei workload - Red Hat OpenShift con NetApp

 a| 
Installazione della virtualizzazione OpenShift - Red Hat OpenShift con NetApp




 a| 
Implementazione di una macchina virtuale con virtualizzazione OpenShift - Red Hat OpenShift con NetApp

 a| 
NetApp HCI per Red Hat OpenShift sulla virtualizzazione Red Hat

 a| 

|===
link:rh-os-n_additional_information.html["Pagina successiva: Ulteriori informazioni: Red Hat OpenShift con NetApp."]
