---
sidebar: sidebar 
permalink: containers/rh-os-n_load_balancers.html 
keywords: Advanced Configuration, Load Balancers, MetalLB 
summary: 'Questa sezione è dedicata all"analisi delle opzioni di bilanciamento del carico per gli utenti che desiderano personalizzare Red Hat OpenShift con l"implementazione NetApp.' 
---
= Analisi delle opzioni di bilanciamento del carico: Red Hat OpenShift con NetApp
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Nella maggior parte dei casi, Red Hat OpenShift rende le applicazioni disponibili al mondo esterno attraverso i percorsi. Un servizio viene esposto assegnandogli un nome host raggiungibile esternamente. Il percorso definito e gli endpoint identificati dal servizio possono essere utilizzati da un router OpenShift per fornire questa connettività denominata ai client esterni.

Tuttavia, in alcuni casi, le applicazioni richiedono l'implementazione e la configurazione di bilanciatori di carico personalizzati per esporre i servizi appropriati. Un esempio è NetApp Astra Control Center. Per soddisfare questa esigenza, abbiamo valutato diverse opzioni di bilanciamento del carico personalizzate. L'installazione e la configurazione sono descritte in questa sezione.

Le seguenti pagine contengono informazioni aggiuntive sulle opzioni di bilanciamento del carico validate nella soluzione Red Hat OpenShift con NetApp:

* link:rh-os-n_LB_MetalLB.html["MetalLB"]
* link:rh-os-n_LB_F5BigIP.html["F5 BIG-IP"]

