---
sidebar: sidebar 
permalink: vdi-vds/hcvdivds_use_cases.html 
keywords: Use cases, target audience 
summary: 'L"infrastruttura VDI ibrida con NetApp VDS consente ai service provider e agli amministratori dei desktop virtuali aziendali di espandere facilmente le risorse in altri ambienti cloud senza influire sugli utenti. La disponibilità di risorse on-premise su NetApp HCI offre un migliore controllo delle risorse GPU e consente di espandere i nodi di calcolo o storage in base alla richiesta.' 
---
= Casi di utilizzo
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
L'infrastruttura VDI ibrida con NetApp VDS consente ai service provider e agli amministratori dei desktop virtuali aziendali di espandere facilmente le risorse in altri ambienti cloud senza influire sugli utenti. La disponibilità di risorse on-premise offre un migliore controllo delle risorse e un'ampia scelta di opzioni (calcolo, GPU, storage e rete) per soddisfare la domanda.

Questa soluzione si applica ai seguenti casi di utilizzo:

* Nel cloud per i picchi della domanda di desktop e applicazioni remoti
* Riduzione del TCO per applicazioni e desktop remoti a esecuzione prolungata ospitandoli on-premise con storage flash e risorse GPU
* Facilità di gestione di desktop e applicazioni remoti negli ambienti cloud
* Sperimenta desktop e applicazioni remoti utilizzando un modello software-as-a-service con risorse on-premise




== Pubblico di destinazione

Il pubblico di riferimento per la soluzione comprende i seguenti gruppi:

* EUC/VDI Architect che vogliono comprendere i requisiti per un VDS ibrido
* Partner NetApp che desiderano assistere i clienti nelle loro esigenze di desktop remoto e applicazioni
* Clienti NetApp HCI esistenti che desiderano soddisfare le esigenze di desktop remoto e applicazioni


link:hcvdivds_netapp_virtual_desktop_service_overview.html["Pagina successiva: Panoramica del servizio Virtual Desktop di NetApp"]
