---
sidebar: sidebar 
permalink: vdi-vds/hcvdivds_hybrid_cloud_vdi_with_virtual_desktop_service.html 
keywords: TR-4861, VDS, Windows Virtual Desktop, Remote Desktop Services, Virtual Desktop Services, 
summary: 'NetApp Virtual Desktop Service (VDS) consente di orchestrare Remote Desktop Services (RDS) nei principali cloud pubblici e nei cloud privati. VDS supporta Windows Virtual Desktop (WVD) su Microsoft Azure. VDS automatizza molte attività che devono essere eseguite dopo l"implementazione di WVD o RDS, tra cui la configurazione delle condivisioni di file SMB (per profili utente, dati condivisi e disco principale utente), l"abilitazione delle funzionalità Windows, l"installazione di applicazioni e agenti, firewall e policy e così via.' 
---
= TR-4861: Cloud ibrido VDI con Virtual Desktop Service
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


Suresh Thoppay, NetApp

[role="lead"]
NetApp Virtual Desktop Service (VDS) consente di orchestrare Remote Desktop Services (RDS) nei principali cloud pubblici e nei cloud privati. VDS supporta Windows Virtual Desktop (WVD) su Microsoft Azure. VDS automatizza molte attività che devono essere eseguite dopo l'implementazione di WVD o RDS, tra cui la configurazione delle condivisioni di file SMB (per profili utente, dati condivisi e disco principale utente), l'abilitazione delle funzionalità Windows, l'installazione di applicazioni e agenti, firewall e policy e così via.

Gli utenti utilizzano VDS per desktop dedicati, desktop condivisi e applicazioni remote. VDS fornisce eventi con script per l'automazione della gestione delle applicazioni per i desktop e riduce il numero di immagini da gestire.

VDS offre un singolo portale di gestione per la gestione delle implementazioni in ambienti cloud pubblici e privati.



== Valore per il cliente

L'esplosione della forza lavoro remota del 2020 ha cambiato i requisiti di business continuity. I reparti IT devono affrontare nuove sfide per il provisioning rapido di desktop virtuali e quindi richiedere agilità di provisioning, gestione remota e i vantaggi TCO di un cloud ibrido che semplifica il provisioning on-premise e delle risorse cloud. Hanno bisogno di una soluzione di cloud ibrido che:

* Affronta la realtà dello spazio di lavoro post-COVID per consentire modelli di lavoro flessibili con dinamiche globali
* Consente di eseguire turni di lavoro semplificando e accelerando l'implementazione degli ambienti di lavoro per tutti i dipendenti, dai task worker agli utenti più esigenti
* Mobilizza la forza lavoro fornendo risorse VDI ricche e sicure indipendentemente dalla posizione fisica
* Semplifica l'implementazione del cloud ibrido
* Automatizza e semplifica la gestione della riduzione dei rischi


link:hcvdivds_use_cases.html["Successivo: Casi d'utilizzo"]
