---
sidebar: sidebar 
permalink: vdi-vds/hcvdivds_nvidia_licensing.html 
keywords: Licensing, NVIDIA, GPU, GRID, Virtual PC 
summary: Quando si utilizza un H610C o H615C, la licenza per la GPU deve essere acquistata dai partner NVIDIA autorizzati a rivendere le licenze. 
---
= Licenze NVIDIA
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
Quando si utilizza un H610C o H615C, la licenza per la GPU deve essere acquistata dai partner NVIDIA autorizzati a rivendere le licenze. È possibile trovare i partner NVIDIA con https://www.nvidia.com/object/partner-locator.html["ricerca partner"^]. Cerca competenze come GPU virtuale (vGPU) o Tesla.

Il software NVIDIA vGPU è disponibile in quattro edizioni:

* NVIDIA GRID Virtual PC (GRID VPC)
* Applicazioni virtuali NVIDIA GRID (GRID vApps)
* Workstation NVIDIA quadro Virtual Data Center (quadro VDWS)
* NVIDIA Virtual ComputeServer (vComputeServer)




== PC virtuale GRID

Questo prodotto è ideale per gli utenti che desiderano un desktop virtuale che offra un'esperienza utente ottimale per applicazioni Microsoft Windows, browser, video ad alta definizione e supporto multi-monitor. NVIDIA GRID Virtual PC offre un'esperienza nativa in un ambiente virtuale, consentendo di eseguire tutte le applicazioni del PC a piene performance.



== APPLICAZIONI Grid Virtual

LE APPLICAZIONI GRID vApps sono destinate alle organizzazioni che implementano un Remote Desktop Session host (RDSH) o altre soluzioni basate su sessioni o streaming di applicazioni. Progettati per offrire applicazioni Microsoft Windows alle massime performance, i desktop RDSH ospitati da Windows Server sono supportati anche DA GRID vApps.



== Quadro Virtual Data Center Workstation

Questa edizione è ideale per i designer mainstream e high-end che utilizzano potenti applicazioni per la creazione di contenuti 3D come Dassault CATIA, SOLIDWORKS, 3Dexcite, Siemens NX, PTC Creo, Schlumberger Petrel, o Autodesk Maya. NVIDIA quadro VDWS consente agli utenti di accedere alle proprie applicazioni grafiche professionali con funzionalità e prestazioni complete, ovunque si trovino su qualsiasi dispositivo.



== NVIDIA Virtual ComputeServer

Molte organizzazioni eseguono carichi di lavoro server a elaborazione intensiva come intelligenza artificiale (ai), deep learning (DL) e data science. In questi casi di utilizzo, il software NVIDIA vComputeServer virtualizza la GPU NVIDIA, che accelera i carichi di lavoro dei server a elaborazione intensiva con funzionalità come codice di correzione degli errori, eliminazione delle pagine, peer-to-peer su NVLink e multi-vGPU.


NOTE: Una licenza quadro VDWS consente di utilizzare GRID VPC e NVIDIA vComputeServer.

link:hcvdivds_deployment.html["Avanti: Implementazione"]
