---
sidebar: sidebar 
permalink: vdi-vds/hcvdivds_solutions_for_industry.html 
keywords: GPU, Azure, NVIDIA, Tesla M60, 
summary: Le workstation grafiche sono generalmente utilizzate in settori come produzione, sanità, energia, media e intrattenimento, istruzione, e così via. La mobilità è spesso limitata per le applicazioni a uso intensivo di grafica. 
---
= Soluzioni per il settore
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
Le workstation grafiche sono generalmente utilizzate in settori come produzione, sanità, energia, media e intrattenimento, istruzione, e così via. La mobilità è spesso limitata per le applicazioni a uso intensivo di grafica.

Per risolvere il problema della mobilità, i servizi di desktop virtuale offrono un ambiente desktop per tutti i tipi di lavoratori, dai task worker agli utenti esperti, utilizzando risorse hardware nel cloud o con NetApp HCI, incluse le opzioni per configurazioni flessibili della GPU. VDS consente agli utenti di accedere al proprio ambiente di lavoro da qualsiasi luogo con laptop, tablet e altri dispositivi mobili.

Per eseguire carichi di lavoro di produzione con software come ANSYS Fluent, ANSYS Mechanical, Autodesk AutoCAD, Autodesk Inventor, Autodesk 3ds Max, Dassault Systèmes SOLIDWORKS, Dassault Systèmes CATIA, PTC Creo, Siemens PLM NX e così via, Le GPU disponibili su diversi cloud (a gennaio 2021) sono elencate nella seguente tabella.

[cols="20%, 20%, 20%, 20%, 20%"]
|===
| Modello GPU | Microsoft Azure | Google Compute (GCP) | Amazon Web Services (AWS) | On-premise (NetApp HCI) 


| NVIDIA M60 | Sì | Sì | Sì | No 


| NVIDIA T4 | No | Sì | Sì | Sì 


| NVIDIA P100 | No | Sì | No | No 


| NVIDIA P4 | No | Sì | No | No 
|===
Sono inoltre disponibili sessioni desktop condivise con altri utenti e desktop personali dedicati. I desktop virtuali possono avere da una a quattro GPU o utilizzare GPU parziali con NetApp HCI. NVIDIA T4 è una scheda GPU versatile in grado di soddisfare le esigenze di un'ampia gamma di carichi di lavoro degli utenti. Ogni scheda GPU su NetApp HCI H615C dispone di 16 GB di memoria frame buffer e tre schede per server. Il numero di utenti che possono essere ospitati su un singolo server H615C dipende dal carico di lavoro dell'utente.

[cols="25%, 25%, 25%, 25%"]
|===
| Utenti/Server | Leggero (4 GB) | Media (8 GB) | Pesante (16 GB) 


| H615C | 12 | 6 | 3 
|===
Per determinare il tipo di utente, eseguire il profiler GPU mentre gli utenti lavorano con le applicazioni che eseguono attività tipiche. Il profiler GPU acquisisce le richieste di memoria, il numero di display e la risoluzione richiesta dagli utenti. È quindi possibile scegliere il profilo vGPU che soddisfa i requisiti.

I desktop virtuali con GPU possono supportare una risoluzione dello schermo fino a 8K, mentre l'utility nView può suddividere un singolo monitor in regioni per lavorare con diversi set di dati.

Con lo storage di file ONTAP, puoi ottenere i seguenti vantaggi:

* Un singolo namespace in grado di crescere fino a 20 PB di storage con 400 miliardi di file, senza molti input amministrativi
* Uno spazio dei nomi che può estendersi a livello globale con una Global file cache
* Multi-tenancy sicura con lo storage NetApp gestito
* Migrazione dei dati cold in archivi di oggetti utilizzando NetApp FabricPool
* Statistiche rapide sui file con analisi del file system
* Scalabilità di un cluster di storage fino a 24 nodi per aumentare capacità e performance
* Possibilità di controllare lo spazio di storage utilizzando quote e performance garantite con limiti di QoS
* Protezione dei dati con crittografia
* Soddisfare i più ampi requisiti di protezione e conformità dei dati
* Offrire opzioni flessibili di business continuity

