---
sidebar: sidebar 
permalink: vdi-vds/hcvdivds_conclusion.html 
keywords: VDS, Virtual Desktop Service, HCI, conclusion 
summary: 'NetApp Virtual Desktop Service offre un ambiente di applicazioni e desktop virtuali di facile utilizzo, con un"attenzione particolare alle sfide aziendali. Estendendo VDS con NetApp HCI, è possibile utilizzare le potenti funzionalità NetApp in un ambiente VDS, tra cui deduplica in linea, compattazione, thin provisioning e compressione.' 
---
= Conclusione
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
NetApp Virtual Desktop Service offre un ambiente di applicazioni e desktop virtuali di facile utilizzo, con un'attenzione particolare alle sfide aziendali. Estendendo i VDS con l'ambiente ONTAP on-premise, è possibile utilizzare le potenti funzionalità NetApp in un ambiente VDS, tra cui cloni rapidi, deduplica in-line, compaction, thin provisioning, e compressione. Queste funzionalità consentono di risparmiare sui costi di storage e migliorare le performance con lo storage all-flash. Con l'hypervisor VMware vSphere, che riduce al minimo i tempi di provisioning dei server utilizzando Virtual Volumes e vSphere API per l'integrazione degli array. Utilizzando il cloud ibrido, i clienti possono scegliere l'ambiente giusto per i carichi di lavoro esigenti e risparmiare denaro. La sessione desktop in esecuzione on-premise può accedere alle risorse cloud in base alle policy.
