---
sidebar: sidebar 
permalink: vdi-vds/vdi-index.html 
keywords: vdi, vds, virtual desktop, end use computing, 
summary: 'I task worker possono avviare rapidamente un"applicazione dall"elenco di applicazioni disponibili. I servizi app pubblicano le applicazioni dagli host della sessione di servizi Desktop remoto. Con WVD, i gruppi di applicazioni offrono funzionalità simili dai pool di host di Windows 10 a più sessioni.' 
---
= Soluzioni di End User Computing (EUC) / Virtual Desktop Infrastructure (VDI)
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
Sia che stiate implementando desktop virtuali on-premise o nel cloud, NetApp offre una vasta gamma di soluzioni EUC/VDI per soddisfare le vostre esigenze.



== NetApp Virtual Desktop Services (VDS)

NetApp Virtual Desktop Service (VDS) consente di orchestrare Remote Desktop Services (RDS) nei principali cloud pubblici e nei cloud privati.

Soluzioni disponibili per VDS:

* link:hcvdivds_hybrid_cloud_vdi_with_virtual_desktop_service.html["Cloud ibrido VDI con NetApp Virtual Desktop Service"]




== End User Computing con VMware Horizon

NetApp ha verificato le architetture per VMware Horizon in diverse configurazioni di calcolo. Le soluzioni disponibili includono:

* link:https://www.netapp.com/pdf.html?item=/media/7121-nva1132design.pdf["End User Computing con VMware (Guida alla progettazione)"]
* link:https://www.netapp.com/us/media/nva-1129-design.pdf["End User Computing con GPU VMware e NVIDIA (guida alla progettazione)"]
* link:https://www.netapp.com/us/media/nva-1129-deploy.pdf["End User Computing con GPU VMware e NVIDIA (Guida all'implementazione)"]
* link:https://www.netapp.com/us/media/tr-4792.pdf["End User Computing con VMware per la grafica 3D"]

