---
sidebar: sidebar 
permalink: virtualization/vmware-vcf-overview.html 
keywords: netapp, vmware, cloud, foundation, vcf, flexpod 
summary:  
---
= VMware Cloud Foundation
:allow-uri-read: 




== VMware Cloud Foundation

[role="lead"]
VMware Cloud Foundation (VCF) è un set di tecnologie che offre un percorso semplice per accedere a un'esperienza di cloud ibrido. Nella soluzione VCF, viene fornito supporto per i workload Kubernetes nativi e basati sulle macchine virtuali. I servizi essenziali come VMware vSphere, VMware vSAN, VMware NSX-T Data Center e VMware vRealize Cloud Management sono parte integrante del pacchetto VCF. Una volta combinati, questi servizi creano un'infrastruttura software-defined in grado di gestire la gestione di calcolo, storage, rete, sicurezza e cloud. Questa infrastruttura collettiva offre un'esperienza ibrida, in cui il framework VCF estende l'ambiente dal data center on-site ad Amazon Web Services (AWS), Azure e Google Cloud.



=== Risorse di documentazione

Per informazioni dettagliate sulle offerte NetApp per VMware Cloud Foundation, fare riferimento alle seguenti quattro (4) serie di blog in parte:

* link:https://www.netapp.com/blog/netapp-vmware-cloud-foundation-getting-started/["NetApp e VMware Cloud Foundation Made Easy parte 1: Introduzione"]
* link:https://www.netapp.com/blog/netapp-vmware-cloud-foundation-ontap-principal-storage/["NetApp e VMware Cloud Foundation Easy Part 2: Storage principale VCF e ONTAP"]
* link:https://www.netapp.com/blog/netapp-vmware-cloud-foundation-element-principal-storage/["NetApp e VMware Cloud Foundation hanno semplificato parte 3: VCF e storage Element Principal"]
* link:https://www.netapp.com/blog/netapp-vmware-cloud-foundation-supplemental-storage/["NetApp e VMware Cloud Foundation Made Easy - parte 4: Strumenti ONTAP per VMware e storage supplementare"]


*Soluzioni NetApp FlexPod per VMware Cloud Foundation*

* link:https://www.netapp.com/blog/expanding-flexpod-hybrid-cloud-with-vmware-cloud-foundation/["Espansione del cloud ibrido FlexPod con VMware Cloud Foundation"]
* link:https://www.cisco.com/c/en/us/td/docs/unified_computing/ucs/UCS_CVDs/flexpod_vcf.html["FlexPod come dominio del carico di lavoro per la base cloud di VMware"]
* link:https://www.cisco.com/c/en/us/td/docs/unified_computing/ucs/UCS_CVDs/flexpod_vcf_design.html["FlexPod as a workload Domain for VMware Cloud Foundation Design Guide (in inglese)"]

