---
sidebar: sidebar 
permalink: virtualization/vmware-scv-overview.html 
keywords: netapp, vmware, getting, started 
summary:  
---
= Plug-in SnapCenter per VMware vSphere
:allow-uri-read: 




== Plug-in SnapCenter per VMware vSphere

[role="lead"]
Il plug-in SnapCenter per VMware vSphere offre operazioni di backup e ripristino rapide, efficienti e coerenti con le macchine virtuali per macchine virtuali, datastore e VMDK. Funziona insieme a SnapCenter Server, consentendo funzionalità di backup e ripristino basate sull'applicazione per i plug-in SnapCenter specifici delle applicazioni.



=== Risorse di documentazione

Per informazioni dettagliate, fare riferimento alle seguenti risorse della documentazione.

* link:https://docs.netapp.com/us-en/sc-plugin-vmware-vsphere/["Plug-in SnapCenter per la documentazione di VMware vSphere"]




=== Risorse della soluzione

Fai riferimento alla seguente soluzione di backup 3-2-1, in cui è incluso il plug-in SnapCenter per backup e recovery di VMware vSphere e BlueXP per le VM.

Report tecnico: link:../ehc/bxp-scv-hybrid-solution.html["Data Protection 3-2-1 per VMware con plug-in SnapCenter e backup e recovery BlueXP per le VM"]

Blog Tech OnTap: link:https://community.netapp.com/t5/Tech-ONTAP-Blogs/3-2-1-Data-Protection-for-VMware-with-SnapCenter-Plug-in-and-BlueXP-backup-and/ba-p/446180["Data Protection 3-2-1 per VMware con plug-in SnapCenter e backup e recovery BlueXP per le VM"]



=== Risorse video

.Plug-in SnapCenter per VMware vSphere - prerequisiti della soluzione
video::38881de9-9ab5-4a8e-a17d-b01200fade6a[panopto]
.Plug-in SnapCenter per VMware vSphere - implementazione
video::10cbcf2c-9964-41aa-ad7f-b01200faca01[panopto]
.Plug-in SnapCenter per VMware vSphere - flusso di lavoro di backup
video::b7272f18-c424-4cc3-bc0d-b01200faaf25[panopto]
.Plug-in SnapCenter per VMware vSphere - flusso di lavoro di ripristino
video::ed41002e-585c-445d-a60c-b01200fb1188[panopto]
.SnapCenter - flusso di lavoro di ripristino SQL
video::8df4ad1f-83ad-448b-9405-b01200fb2567[panopto]