---
sidebar: sidebar 
permalink: virtualization/vsphere_admin_introduction.html 
keywords: vSphere, cloud, hybrid cloud, AWS, Azure, Google cloud, snapmirror cloud, cloud backup service, Cloud Sync, FabricPool, ONTAP 
summary: 'Questa pagina descrive le Best practice per l"implementazione di una soluzione di storage NetApp ONTAP in un ambiente VMware vSphere.' 
---
= Introduzione a ONTAP per amministratori vSphere
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/




== Perché scegliere ONTAP per vSphere?

NetApp ONTAP semplifica le operazioni di storage e gestione dei dati e si integra perfettamente con gli ambienti VMware, sia che si tratti di implementazione on-premise che nel cloud. La protezione dei dati Best-in-class di NetApp, le innovazioni per l'efficienza dello storage e le performance eccezionali nelle architetture VMware basate SU SAN e NAS sono tra i motivi per cui decine di migliaia di clienti hanno scelto ONTAP come soluzione di storage per le implementazioni vSphere.

NetApp offre numerosi plug-in, validazioni e qualifiche VMware di diversi prodotti VMware per supportare i clienti che devono affrontare le sfide specifiche dell'amministrazione di un ambiente di virtualizzazione. NetApp fa per lo storage e la gestione dei dati ciò che VMware fa per la virtualizzazione, consentendo ai clienti di concentrarsi sulle proprie competenze principali piuttosto che sulla gestione dello storage fisico. Questa partnership di quasi 20 anni tra VMware e NetApp continua a evolversi e ad aggiungere valore ai clienti con l'emergere di nuove tecnologie, come VMware Cloud Foundation e Tanzu, continuando a supportare le basi di vSphere.

I fattori chiave che i clienti apprezzano sono:

* *Storage unificato*
* *Efficienza dello storage*
* *Volumi virtuali e gestione basata su policy di storage*
* *Cloud ibrido*


Per ulteriori informazioni sulle soluzioni NetApp e VMware supportate, consultare le seguenti risorse:

* https://mysupport.netapp.com/matrix/#welcome["Il tool NetApp Interoperability Matrix"^] (IMT). IMT definisce i componenti e le versioni qualificate che è possibile utilizzare per creare configurazioni FC/FCoE, iSCSI, NFS e CIFS.
* https://www.vmware.com/resources/compatibility/search.php?deviceCategory=san&details=1&partner=64&isSVA=0&page=1&display_interval=10&sortColumn=Partner&sortOrder=Asc["Guida alla compatibilità VMware"^]. La guida alla compatibilità VMware elenca la compatibilità di sistemi, i/o, storage/SAN e backup con VMware Infrastructure e i prodotti software
* https://www.netapp.com/support-and-training/documentation/ontap-tools-for-vmware-vsphere-documentation/["Tool NetApp ONTAP per VMware"^]. ONTAP Tools per VMware vSphere è un plug-in vCenter Server singolo che include le estensioni VSC, VASA Provider e SRA (Storage Replication Adapter).

