---
sidebar: sidebar 
permalink: virtualization/vsphere_demos_videos.html 
keywords: vSphere, cloud, hybrid cloud, AWS, Azure, Google cloud, snapmirror cloud, cloud backup service, Cloud Sync, FabricPool, ONTAP 
summary: 'Questa pagina fornisce un"introduzione a video ed esercitazioni.' 
---
= Video e demo sulla virtualizzazione
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
Guarda i seguenti video e demo che illustrano le funzionalità specifiche delle soluzioni di cloud ibrido, virtualizzazione e container.

.Strumenti NetApp ONTAP per VMware vSphere
[%collapsible]
====
[cols="5a, 5a, 5a"]
|===


 a| 
Strumenti ONTAP per VMware - Panoramica

 a| 
Provisioning di archivi dati VMware iSCSI con ONTAP

 a| 
Provisioning di archivi dati VMware NFS con ONTAP


|===
====
.VMware Cloud su AWS con AWS FSX per NetApp ONTAP
[%collapsible]
====
[cols="5a, 5a, 5a"]
|===


 a| 
Storage connesso guest Windows con FSX ONTAP utilizzando iSCSI

 a| 
Storage connesso guest Linux con FSX ONTAP con NFS

 a| 
Risparmi sul TCO di VMware Cloud su AWS con Amazon FSX per NetApp ONTAP




 a| 
Archivio dati supplementare VMware Cloud su AWS con Amazon FSX per NetApp ONTAP

 a| 
Installazione della configurazione e dell'implementazione di VMware HCX per VMC

 a| 
Dimostrazione della migrazione a VMotion con VMware HCX per VMC e FSxN




 a| 
Dimostrazione della migrazione a freddo con VMware HCX per VMC e FSxN

 a| 
 a| 

|===
====
.Azure servizi VMware su Azure con Azure NetApp Files (ANF)
[%collapsible]
====
[cols="5a, 5a, 5a"]
|===


 a| 
Panoramica del datastore supplementare della soluzione VMware Azure con Azure NetApp Files

 a| 
Soluzione VMware Azure DR con Cloud Volumes ONTAP, SnapCenter e JetStream

 a| 
Dimostrazione della migrazione a freddo con VMware HCX per AVS e ANF




 a| 
Dimostrazione di VMotion con VMware HCX per AVS e ANF

 a| 
Dimostrazione della migrazione in blocco con VMware HCX per AVS e ANF

 a| 

|===
====
.Plug-in SnapCenter per VMware vSphere
[%collapsible]
====
Il software NetApp SnapCenter è una piattaforma aziendale di facile utilizzo per coordinare e gestire in modo sicuro la protezione dei dati tra applicazioni, database e file system.

Il plug-in SnapCenter per VMware vSphere consente di eseguire operazioni di backup, ripristino e collegamento per macchine virtuali e operazioni di backup e montaggio per datastore registrati con SnapCenter direttamente in VMware vCenter.

Per ulteriori informazioni sul plug-in NetApp SnapCenter per VMware vSphere, consultare la link:https://docs.netapp.com/ocsc-42/index.jsp?topic=%2Fcom.netapp.doc.ocsc-con%2FGUID-29BABBA7-B15F-452F-B137-2E5B269084B9.html["Panoramica del plug-in NetApp SnapCenter per VMware vSphere"].

[cols="5a, 5a, 5a"]
|===


 a| 
Plug-in SnapCenter per VMware vSphere - prerequisiti della soluzione

 a| 
Plug-in SnapCenter per VMware vSphere - implementazione

 a| 
Plug-in SnapCenter per VMware vSphere - flusso di lavoro di backup




 a| 
Plug-in SnapCenter per VMware vSphere - flusso di lavoro di ripristino

 a| 
SnapCenter - flusso di lavoro di ripristino SQL

 a| 

|===
====
.NetApp con VMware Tanzu
[%collapsible]
====
VMware Tanzu consente ai clienti di implementare, amministrare e gestire il proprio ambiente Kubernetes tramite vSphere o VMware Cloud Foundation. Questo portfolio di prodotti VMware consente ai clienti di gestire tutti i cluster Kubernetes pertinenti da un singolo piano di controllo scegliendo l'edizione VMware Tanzu più adatta alle loro esigenze.

Per ulteriori informazioni su VMware Tanzu, consultare https://tanzu.vmware.com/tanzu["Panoramica di VMware Tanzu"^]. Questa recensione illustra i casi d'utilizzo, le aggiunte disponibili e molto altro ancora su VMware Tanzu.

[cols="5a, 5a, 5a"]
|===


 a| 
Come utilizzare vVol con NetApp e VMware Tanzu Basic, parte 1

video::ZtbXeOJKhrc[youtube,width=360] a| 
Come utilizzare vVol con NetApp e VMware Tanzu Basic, parte 2

video::FVRKjWH7AoE[youtube,width=360] a| 
Come utilizzare vVol con NetApp e VMware Tanzu Basic, parte 3

video::Y-34SUtTTtU[youtube,width=360]
|===
====