---
sidebar: sidebar 
permalink: virtualization/vsphere_demos_videos.html 
keywords: vSphere, cloud, hybrid cloud, AWS, Azure, Google cloud, snapmirror cloud, cloud backup service, Cloud Sync, FabricPool, ONTAP 
summary: 'Questa pagina fornisce un"introduzione a video ed esercitazioni.' 
---
= Video e demo su cloud ibrido, virtualizzazione e container
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
Guarda i seguenti video e demo che illustrano le funzionalità specifiche delle soluzioni di cloud ibrido, virtualizzazione e container.

.Strumenti NetApp ONTAP per VMware vSphere
[%collapsible]
====
.Strumenti ONTAP per VMware - Panoramica
[%collapsible]
=====
video::otv_overview.mp4[]
=====
.Provisioning di archivi dati VMware iSCSI con ONTAP
[%collapsible]
=====
video::otv_iscsi_provision.mp4[]
=====
.Provisioning di archivi dati VMware NFS con ONTAP
[%collapsible]
=====
video::otv_nfs_provision.mp4[]
=====
====
.VMware Cloud su AWS con AWS FSX per NetApp ONTAP
[%collapsible]
====
.Storage connesso guest Windows con FSX ONTAP utilizzando iSCSI
[%collapsible]
=====
video::vmc_windows_vm_iscsi.mp4[]
=====
.Storage connesso guest Linux con FSX ONTAP con NFS
[%collapsible]
=====
video::vmc_linux_vm_nfs.mp4[]
=====
.Risparmi sul TCO di VMware Cloud su AWS con Amazon FSX per NetApp ONTAP
[%collapsible]
=====
video::FSxN-NFS-Datastore-on-VMC-TCO-calculator.mp4[]
=====
.Archivio dati supplementare VMware Cloud su AWS con Amazon FSX per NetApp ONTAP
[%collapsible]
=====
video::FSxN-NFS-Datastore-on-VMC.mp4[]
=====
.VMware Cloud su AWS Migrate con FSxN, VMware HCX
[%collapsible]
=====
video::VMC_HCX_Setup.mp4[]
video::Migration_HCX_VMC_FSxN_VMotion.mp4[]
video::Migration_HCX_VMC_FSxN_cold_migration.mp4[]
=====
====
.Azure servizi VMware su Azure con Azure NetApp Files (ANF)
[%collapsible]
====
.Panoramica del datastore supplementare della soluzione VMware Azure con Azure NetApp Files
[%collapsible]
=====
video::ANF-NFS-datastore-on-AVS.mp4[]
=====
.Soluzione VMware Azure DR con Cloud Volumes ONTAP, SnapCenter e JetStream
[%collapsible]
=====
video::AVS-guest-connect-DR-use-case.mp4[]
=====
.Azure VMware Solution Migrate con ANF, VMware HCX
[%collapsible]
=====
video::Migration_HCX_AVS_ANF_ColdMigration.mp4[]
video::Migration_HCX_AVS_ANF_VMotion.mp4[]
video::Migration_HCX_AVS_ANF_Bulk.mp4[]
=====
====
.Plug-in SnapCenter per VMware vSphere
[%collapsible]
====
Il software NetApp SnapCenter è una piattaforma aziendale di facile utilizzo per coordinare e gestire in modo sicuro la protezione dei dati tra applicazioni, database e file system.

Il plug-in SnapCenter per VMware vSphere consente di eseguire operazioni di backup, ripristino e collegamento per macchine virtuali e operazioni di backup e montaggio per datastore registrati con SnapCenter direttamente in VMware vCenter.

Per ulteriori informazioni sul plug-in NetApp SnapCenter per VMware vSphere, consultare la link:https://docs.netapp.com/ocsc-42/index.jsp?topic=%2Fcom.netapp.doc.ocsc-con%2FGUID-29BABBA7-B15F-452F-B137-2E5B269084B9.html["Panoramica del plug-in NetApp SnapCenter per VMware vSphere"].

.Plug-in SnapCenter per VMware vSphere - prerequisiti della soluzione
[%collapsible]
=====
video::scv_prereq_overview.mp4[]
=====
.Plug-in SnapCenter per VMware vSphere - implementazione
[%collapsible]
=====
video::scv_deployment.mp4[]
=====
.Plug-in SnapCenter per VMware vSphere - flusso di lavoro di backup
[%collapsible]
=====
video::scv_backup_workflow.mp4[]
=====
.Plug-in SnapCenter per VMware vSphere - flusso di lavoro di ripristino
[%collapsible]
=====
video::scv_restore_workflow.mp4[]
=====
.SnapCenter - flusso di lavoro di ripristino SQL
[%collapsible]
=====
video::scv_sql_restore.mp4[]
=====
====
.NetApp con VMware Tanzu
[%collapsible]
====
VMware Tanzu consente ai clienti di implementare, amministrare e gestire il proprio ambiente Kubernetes tramite vSphere o VMware Cloud Foundation. Questo portfolio di prodotti VMware consente ai clienti di gestire tutti i cluster Kubernetes pertinenti da un singolo piano di controllo scegliendo l'edizione VMware Tanzu più adatta alle loro esigenze.

Per ulteriori informazioni su VMware Tanzu, consultare https://tanzu.vmware.com/tanzu["Panoramica di VMware Tanzu"^]. Questa recensione illustra i casi d'utilizzo, le aggiunte disponibili e molto altro ancora su VMware Tanzu.

* https://www.youtube.com/watch?v=ZtbXeOJKhrc["Come utilizzare vVol con NetApp e VMware Tanzu Basic, parte 1"^]
* https://www.youtube.com/watch?v=FVRKjWH7AoE["Come utilizzare vVol con NetApp e VMware Tanzu Basic, parte 2"^]
* https://www.youtube.com/watch?v=Y-34SUtTTtU["Come utilizzare vVol con NetApp e VMware Tanzu Basic, parte 3"^]


====
.NetApp con Red Hat OpenShift
[%collapsible]
====
Red Hat OpenShift, una piattaforma Kubernetes aziendale, consente di eseguire applicazioni basate su container con una strategia di cloud ibrido aperto. Disponibile come servizio cloud sui principali cloud pubblici o come software autogestiti, Red Hat OpenShift offre ai clienti la flessibilità di cui hanno bisogno per progettare la propria soluzione basata su container.

Per ulteriori informazioni su Red Hat OpenShift, consulta questo articolo https://www.redhat.com/en/technologies/cloud-computing/openshift["Panoramica di Red Hat OpenShift"^]. Puoi anche consultare la documentazione del prodotto e le opzioni di implementazione per saperne di più su Red Hat OpenShift.

* https://docs.netapp.com/us-en/netapp-solutions/containers/rh-os-n_videos_workload_migration_manual.html["Migrazione dei workload - Red Hat OpenShift con NetApp"^]
* https://docs.netapp.com/us-en/netapp-solutions/containers/rh-os-n_videos_RHV_deployment.html["Red Hat OpenShift Deployment on RHV: Red Hat OpenShift con NetApp"^]


====