---
sidebar: sidebar 
permalink: virtualization/vsrm-ontap9_conclusion.html 
keywords: vmware, site, recovery manager, vsrm, hybrid, cloud, vcenter, disaster 
summary: 'VMware vCenter Site Recovery Manager è un"offerta di disaster recovery che offre orchestrazione automatica e test senza interruzioni di piani di recovery centralizzati per semplificare la gestione del disaster recovery per tutte le applicazioni virtualizzate.' 
---
= Conclusione
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
VMware vCenter Site Recovery Manager è un'offerta di disaster recovery che offre orchestrazione automatica e test senza interruzioni di piani di recovery centralizzati per semplificare la gestione del disaster recovery per tutte le applicazioni virtualizzate.

Implementando Site Recovery Manager sui sistemi NetApp ONTAP, è possibile ridurre drasticamente i costi e la complessità del disaster recovery. Con appliance di storage scalabili, facili da gestire e dalle performance elevate e solide offerte software, NetApp offre soluzioni di storage e gestione dei dati flessibili per supportare gli ambienti vSphere.

Le Best practice e i consigli forniti in questa guida non sono una soluzione adatta a tutti. Questo documento contiene una raccolta di Best practice e consigli che forniscono linee guida per pianificare, implementare e gestire i piani di DR SRM. Per pianificare e implementare gli ambienti VMware vCenter Site Recovery VMware sullo storage NetApp, rivolgersi a un esperto VMware locale. Gli esperti VMware di NetApp sono in grado di identificare rapidamente le esigenze e le esigenze di qualsiasi ambiente vSphere e di adattare la soluzione di storage di conseguenza.
