---
sidebar: sidebar 
permalink: containers/baremetal-anthos/bmanthos_introduction.html 
keywords: WP-7337, Google Cloud, Cloud Volumes ONTAP, Cloud Volume Service, hypervisor, Kubernetes 
summary: 'NetApp e Google Cloud hanno stretto una solida relazione da diversi anni, con NetApp che ha introdotto per la prima volta i servizi dati cloud in Google Cloud con Cloud Volumes ONTAP e Cloud Volumes Service. Questa relazione è stata quindi ampliata convalidando la piattaforma NetApp HCI per l"utilizzo con Google Cloud anthos on-premise, una soluzione di Kubernetes ibrido multi-cloud basata su hypervisor implementata su VMware vSphere. NetApp ha quindi superato la qualifica anthos Ready per NetApp Astra Trident, ONTAP e il protocollo NFS per fornire storage dinamico e persistente per i container.' 
---
= WP-7337: Anthos su metallo nudo
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../../media/


Alan Cowles e Nikhil M Kulkarni, NetApp

NetApp e Google Cloud hanno stretto una solida relazione da diversi anni, con NetApp che ha introdotto per la prima volta i servizi dati cloud per Google Cloud con Cloud Volumes ONTAP e Cloud Volumes Service. Questa relazione è stata quindi ampliata convalidando la piattaforma NetApp HCI per l'utilizzo con Google Cloud anthos on-premise, una soluzione di Kubernetes ibrido multi-cloud basata su hypervisor implementata su VMware vSphere. NetApp ha quindi superato la qualifica anthos Ready per NetApp Astra Trident, ONTAP e il protocollo NFS per fornire storage dinamico e persistente per i container.

Anthos può ora essere installato direttamente su server bare-metal nell'ambiente di un cliente, il che aggiunge un'opzione aggiuntiva per i clienti di estendere Google Cloud ai propri data center locali senza hypervisor. Inoltre, sfruttando le funzionalità del sistema operativo per lo storage NetApp ONTAP e di NetApp Astra Trident, puoi estendere le funzionalità della tua piattaforma integrando lo storage persistente per i container.

Questa combinazione ti consente di sfruttare appieno il potenziale di server, storage e networking, oltre al supporto, ai livelli di servizio, alla fatturazione mensile e alla flessibilità on-demand offerta da Google Cloud. Poiché utilizzi hardware, rete e storage personalizzati, hai il controllo diretto su scalabilità applicativa, sicurezza e latenza di rete, oltre a sfruttare i vantaggi delle applicazioni gestite e containerizzate con anthos on bare metal.

link:bmanthos_solution_overview.html["Pagina successiva: Panoramica della soluzione."]
