---
sidebar: sidebar 
permalink: containers/baremetal-anthos/bmanthos_conclusion.html 
keywords: bare metal, infrastructure, stateful, Trident 
summary: 'Anthos on bare metal con NetApp offre una solida piattaforma per eseguire in modo efficiente carichi di lavoro basati su container, consentendo la personalizzazione dell"infrastruttura implementata.' 
---
= Conclusione
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../../media/


Anthos on bare metal con NetApp offre una solida piattaforma per eseguire in modo efficiente carichi di lavoro basati su container, consentendo la personalizzazione dell'infrastruttura implementata. I clienti possono utilizzare l'infrastruttura server e il sistema operativo supportato di loro scelta o persino implementare la soluzione all'interno dell'infrastruttura esistente. La potenza e la flessibilità di questi ambienti aumentano notevolmente grazie all'integrazione di NetApp ONTAP e NetApp Astra Trident, supportando i carichi di lavoro delle applicazioni stateful attraverso il provisioning e la gestione efficienti dello storage persistente per i container. Estendendo il potenziale di Google Cloud nel proprio data center basato su NetApp, un cliente può sfruttare i vantaggi di una soluzione Kubernetes completamente supportata, altamente disponibile, facilmente scalabile e completamente gestita per lo sviluppo e la produzione dei carichi di lavoro delle applicazioni.

link:bmanthos_where_to_find_additional_information.html["Avanti: Dove trovare ulteriori informazioni."]
