= 
:allow-uri-read: 


. Per utilizzare i playbook Ansible che implementano Astra Control Center, è necessario disporre di una macchina Ubuntu/RHEL con Ansible installato. Seguire le procedure link:../automation/getting-started.html["qui"] Per Ubuntu e RHEL.
. Clonare il repository GitHub che ospita il contenuto Ansible.
+
[source, cli]
----
git clone https://github.com/NetApp-Automation/na_astra_control_suite.git
----
. Accedere al NetApp Support Site e scaricare l'ultima versione di NetApp Astra Control Center. Per farlo, è necessaria una licenza allegata al tuo account NetApp. Dopo aver scaricato il tarball, trasferirlo sulla workstation.
+

NOTE: Per iniziare a utilizzare una licenza di prova per Astra Control, visitare il sito https://cloud.netapp.com/astra-register["Sito di registrazione Astra"^].

. Creare o ottenere il file kubeconfig con accesso amministratore al cluster {k8s_usercluster_name} su cui deve essere installato Astra Control Center.
. Modificare la directory in `na_astra_control_suite`.
+
[source, cli]
----
cd na_astra_control_suite
----
. Modificare il `vars/vars.yml` archiviare e compilare le variabili con le informazioni richieste.
+
[source, cli]
----
#Define whether or not to push the Astra Control Center images to your private registry [Allowed values: yes, no]
push_images: yes

#The directory hosting the Astra Control Center installer
installer_directory: /home/admin/

#Specify the ingress type. Allowed values - "AccTraefik" or "Generic"
#"AccTraefik" if you want the installer to create a LoadBalancer type service to access ACC, requires MetalLB or similar.
#"Generic" if you want to create or configure ingress controller yourself, installer just creates a ClusterIP service for traefik.
ingress_type: "AccTraefik"

#Name of the Astra Control Center installer (Do not include the extension, just the name)
astra_tar_ball_name: astra-control-center-22.04.0

#The complete path to the kubeconfig file of the kubernetes/openshift cluster Astra Control Center needs to be installed to.
hosting_k8s_cluster_kubeconfig_path: /home/admin/cluster-kubeconfig.yml

#Namespace in which Astra Control Center is to be installed
astra_namespace: netapp-astra-cc

#Astra Control Center Resources Scaler. Leave it blank if you want to accept the Default setting.
astra_resources_scaler: Default

#Storageclass to be used for Astra Control Center PVCs, it must be created before running the playbook [Leave it blank if you want the PVCs to use default storageclass]
astra_trident_storageclass: basic

#Reclaim Policy for Astra Control Center Persistent Volumes [Allowed values: Retain, Delete]
storageclass_reclaim_policy: Retain

#Private Registry Details
astra_registry_name: "docker.io"

#Whether the private registry requires credentials [Allowed values: yes, no]
require_reg_creds: yes

#If require_reg_creds is yes, then define the container image registry credentials
#Usually, the registry namespace and usernames are same for individual users
astra_registry_namespace: "registry-user"
astra_registry_username: "registry-user"
astra_registry_password: "password"

#Kuberenets/OpenShift secret name for Astra Control Center
#This name will be assigned to the K8s secret created by the playbook
astra_registry_secret_name: "astra-registry-credentials"

#Astra Control Center FQDN
acc_fqdn_address: astra-control-center.cie.netapp.com

#Name of the Astra Control Center instance
acc_account_name: ACC Account Name

#Administrator details for Astra Control Center
admin_email_address: admin@example.com
admin_first_name: Admin
admin_last_name: Admin
----
. Esegui il manuale per implementare Astra Control Center. Il playbook richiede privilegi root per alcune configurazioni.
+
Eseguire il seguente comando per eseguire il playbook se l'utente che esegue il playbook è root o ha configurato sudo senza password.

+
[source, cli]
----
ansible-playbook install_acc_playbook.yml
----
+
Se l'utente ha configurato l'accesso sudo basato su password, eseguire il seguente comando per eseguire il manuale e inserire la password sudo.

+
[source, cli]
----
ansible-playbook install_acc_playbook.yml -K
----

