= Considerazioni sul dimensionamento della capacità
:allow-uri-read: 




== Considerazioni sul dimensionamento della capacità

La quantità di spazio su disco necessaria per un volume di destinazione del vault informatico ONTAP dipende da una varietà di fattori, il più importante dei quali è il tasso di variazione per i dati nel volume di origine. È improbabile che la pianificazione di backup e la pianificazione Snapshot sul volume di destinazione influiscano sull'utilizzo del disco sul volume di destinazione e che la velocità di modifica sul volume di origine sia costante. È consigliabile fornire un buffer di capacità di storage aggiuntiva oltre a quello necessario per adattarsi a future modifiche del comportamento di utenti finali o applicazioni.

Il dimensionamento di una relazione per 1 mese di conservazione in ONTAP richiede il calcolo dei requisiti storage in base a diversi fattori, tra cui le dimensioni del set di dati primario, il tasso di cambiamento dei dati (tasso di modifica giornaliero) e i risparmi in termini di deduplica e compressione (se applicabili).

Ecco l'approccio passo passo:

Il primo passo è conoscere le dimensioni del volume o dei volumi di origine che si sta proteggendo con il vault informatico. Questa è la quantità di base di dati che verranno inizialmente replicati nella destinazione del cyber vault. Quindi, stimare la frequenza di modifica giornaliera per il set di dati. Questa è la percentuale di dati che cambia ogni giorno. È fondamentale avere una buona comprensione di come sono dinamici i tuoi dati.

Ad esempio:

* Dimensioni del set di dati primario = 5TB
* Tasso di cambio giornaliero = 5% (0,05)
* Efficienza di deduplica e compressione = 50% (0,50)


Ora, esaminiamo il calcolo:

* Calcolare la velocità di modifica giornaliera dei dati:
+
`Changed data per day = 5000 * 5% = 250GB`

* Calcolare il totale dei dati modificati per 30 giorni:
+
`Total changed data in 30 days = 250 GB * 30 = 7.5TB`

* Calcolare lo storage totale necessario:
+
`TOTAL = 5TB + 7.5TB = 12.5TB`

* Applica i risparmi su deduplica e compressione:
+
`EFFECTIVE = 12.5TB * 50% = 6.25TB`



*Riepilogo delle esigenze di archiviazione*

* Senza efficienza: Richiederebbe *12,5TB* per memorizzare 30 giorni dei dati del vault.
* Con un'efficienza del 50%: Richiederebbe *6,25TB* di storage dopo la deduplica e la compressione.



NOTE: Le copie Snapshot possono avere un overhead aggiuntivo a causa dei metadati, ma questo è in genere di entità secondaria.


NOTE: Se vengono eseguiti più backup al giorno, regolare il calcolo in base al numero di copie Snapshot acquisite ogni giorno.


NOTE: Considerare la crescita dei dati nel tempo per garantire che il dimensionamento sia a prova di futuro.
