= 
:allow-uri-read: 


[role="tabbed-block"]
====
.AWS/VMC
--
AWS supporta lo storage NetApp nelle seguenti configurazioni:

* FSX ONTAP come storage connesso guest
* Cloud Volumes ONTAP (CVO) come storage connesso guest
* FSX ONTAP come datastore NFS supplementare


Visualizza i dettagli link:aws-guest.html["Opzioni di storage di connessione guest per VMC"]. Visualizza i dettagli link:aws-native-nfs-datastore-option.html["Opzioni aggiuntive del datastore NFS per VMC"].

Visualizza i dettagli link:aws-guest.html["Opzioni di storage di connessione guest per VMC"]. Visualizza i dettagli link:aws-native-nfs-datastore-option.html["Opzioni aggiuntive del datastore NFS per VMC"].

--
.Azure/AVS
--
Azure supporta lo storage NetApp nelle seguenti configurazioni:

* Azure NetApp Files (ANF) come storage connesso guest
* Cloud Volumes ONTAP (CVO) come storage connesso guest
* Azure NetApp Files (ANF) come datastore NFS supplementare


Visualizza i dettagli link:azure-guest.html["Opzioni di storage di connessione guest per AVS"]. Visualizza i dettagli link:azure-native-nfs-datastore-option.html["Opzioni aggiuntive del datastore NFS per AVS"].

Visualizza i dettagli link:azure-guest.html["Opzioni di storage di connessione guest per AVS"]. Visualizza i dettagli link:azure-native-nfs-datastore-option.html["Opzioni aggiuntive del datastore NFS per AVS"].

--
.GCP/GCVE
--
Google Cloud supporta lo storage NetApp nelle seguenti configurazioni:

* Cloud Volumes ONTAP (CVO) come storage connesso guest
* Google Cloud NetApp Volumes (NetApp Volumes) come storage connesso guest
* Google Cloud NetApp Volumes (NetApp Volumes) come datastore NFS supplementare


Visualizza i dettagli link:gcp-guest.html["Opzioni di storage di connessione guest per GCVE"]. Visualizza i dettagli link:gcp-ncvs-datastore.html["Opzioni aggiuntive del datastore NFS per GCVE"].

Visualizza i dettagli link:gcp-guest.html["Opzioni di storage di connessione guest per GCVE"]. Visualizza i dettagli link:gcp-ncvs-datastore.html["Opzioni aggiuntive del datastore NFS per GCVE"].

Ulteriori informazioni su link:https://www.netapp.com/blog/cloud-volumes-service-google-cloud-vmware-engine/["Supporto di datastore Google Cloud NetApp Volumes per Google Cloud VMware Engine (blog NetApp)"^] o. link:https://cloud.google.com/blog/products/compute/how-to-use-netapp-cvs-as-datastores-with-vmware-engine["Come usare Google Cloud NetApp Volumes come datastore per Google Cloud VMware Engine (Google blog)"^]

--
====