---
sidebar: sidebar 
permalink: databases/automation_ora_clone_lifecycle.html 
keywords: Database, Oracle, DataGuard, AWS, FSx ONTAP, Azure, ANF, 
summary: 'La soluzione mette a disposizione un toolkit di automazione basato su Ansible per la configurazione, il cloning e l"aggiornamento dei database cloni Oracle da un database primario. Il database primario può essere il database di standby fisico nella configurazione di Oracle Data Guard. La soluzione può essere applicata in un data center privato o nel cloud AWS con storage FSX ONTAP in configurazione NFS o ASM, oppure nel cloud Azure con storage Azure NetApp Files in configurazione NFS.' 
---
= Automazione del ciclo di vita dei cloni Oracle di SnapCenter
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


Allen Cao, Niyaz Mohamed, NetApp

[role="lead"]
La soluzione mette a disposizione un toolkit di automazione basato su Ansible per la configurazione, il cloning e l'aggiornamento dei database cloni Oracle da un database primario. Il database primario può essere il database di standby fisico nella configurazione di Oracle Data Guard. La soluzione può essere applicata in un data center privato o nel cloud AWS con storage FSX ONTAP in configurazione NFS o ASM, oppure nel cloud Azure con storage Azure NetApp Files in configurazione NFS.



== Scopo

I clienti apprezzano la funzione FlexClone dello storage NetApp ONTAP, che consente di creare cloni dei database di grandi dimensioni in modo rapido e ottenere ulteriori risparmi sullo storage, se la funzionalità thin clone è abilitata per la specifica offerta di storage in un data center privato o nel cloud pubblico. Questo toolkit basato su Ansible automatizza setup, cloning e aggiornamento dei database Oracle clonati in base alle tempistiche, utilizzando le utilità della riga di comando di NetApp SnapCenter per una gestione ottimizzata del ciclo di vita. Il toolkit si riferisce ai database Oracle implementati sullo storage ONTAP on-premise o su cloud pubblico (AWS o Azure) e gestiti dal tool dell'interfaccia utente di NetApp SnapCenter.

Questa soluzione risolve i seguenti casi di utilizzo:

* Setup del file di configurazione delle specifiche dei cloni del database Oracle.
* Creare e aggiornare il database Oracle clone in base alla pianificazione definita dall'utente.




== Pubblico

Questa soluzione è destinata alle seguenti persone:

* Un DBA che gestisce i database Oracle con SnapCenter.
* Un amministratore dello storage che gestisce lo storage ONTAP con SnapCenter.
* Proprietario di un'applicazione che ha accesso all'interfaccia utente di SnapCenter.




== Licenza

Accedendo, scaricando, installando o utilizzando il contenuto di questo repository GitHub, l'utente accetta i termini della licenza riportata in link:https://github.com/NetApp/na_ora_hadr_failover_resync/blob/master/LICENSE.TXT["File di licenza"^].


NOTE: Ci sono alcune restrizioni riguardo alla produzione e/o alla condivisione di qualsiasi opera derivata con il contenuto di questo repository GitHub. Prima di utilizzare il contenuto, leggere i termini della licenza. Se non si accettano tutti i termini, non accedere, scaricare o utilizzare il contenuto di questo repository.



== Implementazione della soluzione



=== Prerequisiti per l'implementazione

[%collapsible]
====
L'implementazione richiede i seguenti prerequisiti.

....
Ansible controller:
  Ansible v.2.10 and higher
  ONTAP collection 21.19.1
  Python 3
  Python libraries:
    netapp-lib
    xmltodict
    jmespath
....
....
SnapCenter server:
  version 5.0 and up, 6.1 for Azure NetApp Files
  backup policy configured
  Source database protected with a backup policy
....
....
Oracle servers:
  Source server managed by SnapCenter (In Data Guard, this would be the physical standby serer)
  Target server managed by SnapCenter (clone DB host)
....

NOTE: Per semplificare, il server Oracle di destinazione clone deve essere configurato in modo identico per il server Oracle di standby, ad esempio lo stack software Oracle, nonché il layout della directory per Oracle Home e così via

====


=== Scaricare il toolkit

[%collapsible]
====
[source, cli]
----
git clone https://bitbucket.ngage.netapp.com/scm/ns-bb/na_oracle_clone_lifecycle.git
----

NOTE: Al momento è possibile accedere al toolkit solo da parte dell'utente interno NetApp con accesso bitbucket. Per gli utenti esterni interessati, richiedere l'accesso al proprio account team o contattare il team di progettazione delle soluzioni NetApp.

====


=== Configurazione dei file host di destinazione Ansible

[%collapsible]
====
Il toolkit include un file hosts che definisce le destinazioni per cui viene eseguito un playbook Ansible. In genere, si tratta degli host clone di Oracle di destinazione. Di seguito è riportato un file di esempio. Una voce dell'host include l'indirizzo IP dell'host di destinazione e la chiave ssh per l'accesso di un utente amministratore all'host per eseguire il comando clone o refresh.

#Host cloni Oracle

....
[clone_1]
ora_04.cie.netapp.com ansible_host=10.61.180.29 ansible_ssh_private_key_file=ora_04.pem
....
 [clone_2]
 [clone_3]
====


=== Configurazione variabili globali

[%collapsible]
====
I playbook Ansible prendono input variabili da diversi file variabili. Di seguito è riportato un esempio di file variabile globale vars.yml.

 # ONTAP specific config variables
 # SnapCtr specific config variables
....
snapctr_usr: xxxxxxxx
snapctr_pwd: 'xxxxxxxx'
....
 backup_policy: 'Oracle Full offline Backup'
 # Linux specific config variables
 # Oracle specific config variables
====


=== Configurazione variabili host

[%collapsible]
====
Le variabili host sono definite nella directory host_vars denominata {{ host_name }}.yml. Di seguito è riportato un esempio di file di variabile host Oracle di destinazione ora_04.cie.netapp.com.yml che mostra la configurazione tipica.

 # User configurable Oracle clone db host specific parameters
....
# Source database to clone from
source_db_sid: NTAP1
source_db_host: ora_03.cie.netapp.com
....
....
# Clone database
clone_db_sid: NTAP1DEV
....
 snapctr_obj_id: '{{ source_db_host }}\{{ source_db_sid }}'
====


=== Configurazione aggiuntiva del server Oracle di destinazione dei cloni

[%collapsible]
====
Il server Oracle di destinazione della clonazione deve avere lo stack software Oracle identico a quello del server Oracle di origine installato e sottoposto a patch. L'utente Oracle .bash_profile ha $ORACLE_BASE e $ORACLE_HOME configurato. Inoltre, la variabile $ORACLE_HOME deve corrispondere all'impostazione del server Oracle di origine. Di seguito viene riportato un esempio.

 # .bash_profile
....
# Get the aliases and functions
if [ -f ~/.bashrc ]; then
        . ~/.bashrc
fi
....
....
# User specific environment and startup programs
export ORACLE_BASE=/u01/app/oracle
export ORACLE_HOME=/u01/app/oracle/product/19.0.0/NTAP1
....
====


=== Esecuzione Playbook

[%collapsible]
====
Sono disponibili un totale di tre playbook per eseguire il ciclo di vita dei cloni del database Oracle con le utility della CLI di SnapCenter.

. Installare i prerequisiti del controller Ansible - una sola volta.
+
[source, cli]
----
ansible-playbook -i hosts ansible_requirements.yml
----
. File di configurazione clone - una sola volta.
+
[source, cli]
----
ansible-playbook -i hosts clone_1_setup.yml -u admin -e @vars/vars.yml
----
. Crea e aggiorna regolarmente il database dei cloni da crontab con uno script shell per chiamare un playbook di refresh.
+
[source, cli]
----
0 */4 * * * /home/admin/na_oracle_clone_lifecycle/clone_1_refresh.sh
----



NOTE: Modificare il nome utente in sudo user per la configurazione SnapCenter.

Per un database clone aggiuntivo, creare un clone_n_setup.yml e clone_n_refresh.yml separati e clone_n_refresh.sh. Configurare di conseguenza gli host di destinazione Ansible e il file hostname.yml nella directory host_vars.

====


== Dove trovare ulteriori informazioni

Per ulteriori informazioni sull'automazione delle soluzioni NetApp, consulta il seguente sito Web link:../automation/automation_introduction.html["Automazione delle soluzioni NetApp"^]
