---
sidebar: sidebar 
permalink: databases/getting_started_requirements.html 
keywords: Linux, RHEL Oracle19c, NFS, ONTAP 
summary: 'In questa pagina viene descritto il metodo automatizzato per l"implementazione di Oracle19c sullo storage NetApp ONTAP.' 
---
= Per iniziare
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
Questa soluzione è stata progettata per essere eseguita in un ambiente AWX/Tower o da CLI su un host di controllo Ansible.



== AWX/Tower

Per gli ambienti AWX/tower, viene fornita una guida alla creazione di un inventario della gestione del cluster ONTAP e del server Oracle (IP e nomi host), alla creazione di credenziali, alla configurazione di un progetto che estrae il codice Ansible da NetApp Automation Github e al modello di lavoro che avvia l'automazione.

. Compilare le variabili specifiche del proprio ambiente, quindi copiarle e incollarle nei campi Extra Vars del modello di lavoro.
. Una volta aggiunti i var aggiuntivi al modello di lavoro, è possibile avviare l'automazione.
. Il modello di lavoro viene eseguito in tre fasi specificando i tag per ontap_CONFIG, linux_CONFIG e oracle_CONFIG.




== CLI tramite l'host di controllo Ansible

. Per configurare l'host Linux in modo che sia possibile utilizzarlo come host di controllo Ansiblelink:../automation/getting-started.html["fare clic qui per istruzioni dettagliate"]
. Una volta configurato l'host di controllo Ansible, è possibile clonare il repository Ansible Automation.
. Modificare il file hosts con gli IP e/o i nomi host della gestione del cluster ONTAP e degli IP di gestione del server Oracle.
. Compilare le variabili specifiche dell'ambiente, quindi copiarle e incollarle in `vars.yml` file.
. Ogni host Oracle dispone di un file variabile identificato dal relativo nome host che contiene variabili specifiche dell'host.
. Una volta completati tutti i file variabili, è possibile eseguire il playbook in tre fasi specificando i tag per `ontap_config`, `linux_config`, e. `oracle_config`.




== Requisiti

[cols="3, 9"]
|===
| Ambiente | Requisiti 


.4+| *Ambiente Ansible* | Host AWX/Tower o Linux come host di controllo Ansible 


| Ansible v.2.10 e versioni successive 


| Python 3 


| Librerie Python - netapp-lib - xmltodict - jmespath 


.3+| *ONTAP* | ONTAP versione 9.3 - 9.7 


| Due aggregati di dati 


| VLAN NFS e ifgrp create 


.5+| *Server Oracle* | RHEL 7/8 


| Oracle Linux 7/8 


| Interfacce di rete per NFS, gestione pubblica e opzionale 


| File di installazione Oracle sui server Oracle 
|===


== Dettagli sull'automazione

Questa implementazione automatica è progettata con un singolo playbook Ansible che consiste di tre ruoli separati. I ruoli sono per le configurazioni ONTAP, Linux e Oracle. La seguente tabella descrive le attività automatizzate.

[cols="4, 9"]
|===
| Ruolo | Attività 


.5+| *ontap_config* | Verifica preliminare dell'ambiente ONTAP 


| Creazione di SVM basate su NFS per Oracle 


| Creazione di policy di esportazione 


| Creazione di volumi per Oracle 


| Creazione di LIF NFS 


.9+| *linux_config* | Creare punti di montaggio e montare volumi NFS 


| Verificare i montaggi NFS 


| Configurazione specifica del sistema operativo 


| Creare directory Oracle 


| Configurare gli hugepage 


| Disattiva SELinux e il daemon del firewall 


| Attivare e avviare il servizio chronyd 


| aumentare il limite massimo del descrittore di file 


| Creare il file di sessione pam.d. 


.8+| *oracle_config* | Installazione del software Oracle 


| Creare un listener Oracle 


| Creare database Oracle 


| Configurazione dell'ambiente Oracle 


| Salva stato PDB 


| Attivare la modalità di archiviazione delle istanze 


| Abilitare il client DNFS 


| Abilitare l'avvio e lo spegnimento automatici del database tra i riavvii del sistema operativo 
|===


== Parametri predefiniti

Per semplificare l'automazione, abbiamo preimpostato molti parametri di implementazione Oracle richiesti con valori predefiniti. In genere non è necessario modificare i parametri predefiniti per la maggior parte delle implementazioni. Un utente più avanzato può apportare modifiche ai parametri predefiniti con cautela. I parametri predefiniti si trovano in ogni cartella di ruoli nella directory dei valori predefiniti.



== Istruzioni per l'implementazione

Prima di iniziare, scaricare i seguenti file di installazione e patch Oracle e inserirli in `/tmp/archive` Directory con accesso in lettura, scrittura ed esecuzione per tutti gli utenti su ciascun server DB da implementare. Le attività di automazione cercano i file di installazione denominati in quella particolare directory per l'installazione e la configurazione di Oracle.

[listing]
----
LINUX.X64_193000_db_home.zip -- 19.3 base installer
p31281355_190000_Linux-x86-64.zip -- 19.8 RU patch
p6880880_190000_Linux-x86-64.zip -- opatch version 12.2.0.1.23
----


== Licenza

Leggere le informazioni sulla licenza come indicato nel repository Github. Accedendo, scaricando, installando o utilizzando il contenuto di questo repository, l'utente accetta i termini della licenza stabilita link:https://github.com/NetApp-Automation/na_oracle19c_deploy/blob/master/LICENSE.TXT["qui"^].

Si noti che esistono alcune limitazioni relative alla produzione e/o alla condivisione di qualsiasi opera derivata con il contenuto di questo repository. Leggere attentamente i termini del link:https://github.com/NetApp-Automation/na_oracle19c_deploy/blob/master/LICENSE.TXT["Licenza"^] prima di utilizzare il contenuto. Se non si accettano tutti i termini, non accedere, scaricare o utilizzare il contenuto di questo repository.

Una volta pronti, fare clic su link:awx_automation.html["Qui per le procedure di implementazione AWX/Tower dettagliate"] oppure link:cli_automation.html["Qui per l'implementazione della CLI"].
