---
sidebar: sidebar 
permalink: databases/hybrid_dbops_snapcenter_prerequisite.html 
summary: 'Alcuni prerequisiti devono essere configurati sia on-premise che nel cloud prima dell"esecuzione dei carichi di lavoro del database del cloud ibrido. La sezione seguente fornisce un riepilogo generale di questo processo e i seguenti collegamenti forniscono ulteriori informazioni sulla configurazione di sistema necessaria.' 
keywords: workflow, prerequisites, licensing, networking, security 
---
= Configurazione dei prerequisiti
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Alcuni prerequisiti devono essere configurati sia on-premise che nel cloud prima dell'esecuzione dei carichi di lavoro del database del cloud ibrido. La sezione seguente fornisce un riepilogo generale di questo processo e i seguenti collegamenti forniscono ulteriori informazioni sulla configurazione di sistema necessaria.



== On-premise

* Installazione e configurazione di SnapCenter
* Configurazione dello storage del server di database on-premise
* Requisiti di licenza
* Networking e sicurezza
* Automazione




== Cloud pubblico

* Accesso a NetApp Cloud Central
* Accesso alla rete da un browser Web a diversi endpoint
* Percorso di rete per un connettore
* Permessi del cloud provider
* Networking per singoli servizi


Considerazioni importanti:

. Dove implementare Cloud Manager Connector?
. Dimensionamento e architettura di Cloud Volume ONTAP
. Nodo singolo o alta disponibilità?


I seguenti link forniscono ulteriori dettagli:

link:hybrid_dbops_snapcenter_prereq_onprem.html["On-premise"]

link:hybrid_dbops_snapcenter_prereq_cloud.html["Cloud pubblico"]
