---
sidebar: sidebar 
permalink: databases/hybrid_dbops_snapcenter_getting_started.html 
summary: Questa sezione fornisce un riepilogo delle attività che devono essere completate per soddisfare i requisiti dei prerequisiti, come descritto nella sezione precedente. La sezione seguente fornisce un elenco di task di alto livello per le operazioni on-premise e di cloud pubblico. È possibile accedere ai processi e alle procedure dettagliate facendo clic sui relativi collegamenti. 
keywords: introduction, workflow 
---
= Panoramica introduttiva
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:table-stripes: odd
:imagesdir: ./../media/


link:hybrid_dbops_snapcenter_prereq_cloud.html["Precedente: Prerequisiti per il cloud pubblico."]

[role="lead"]
Questa sezione fornisce un riepilogo delle attività che devono essere completate per soddisfare i requisiti dei prerequisiti, come descritto nella sezione precedente. La sezione seguente fornisce un elenco di task di alto livello per le operazioni on-premise e di cloud pubblico. È possibile accedere ai processi e alle procedure dettagliate facendo clic sui relativi collegamenti.



== On-premise

* Configurare l'utente amministratore del database in SnapCenter
* Prerequisiti per l'installazione del plug-in SnapCenter
* Installazione del plug-in host SnapCenter
* Rilevamento delle risorse DB
* Configurare il peering del cluster di storage e la replica del volume DB
* Aggiunta di SVM per lo storage del database CVO a SnapCenter
* Impostare il criterio di backup del database in SnapCenter
* Implementare policy di backup per proteggere il database
* Validare il backup




== Cloud pubblico AWS

* Controllo prima del volo
* Passaggi per implementare Cloud Manager e Cloud Volumes ONTAP in AWS
* Implementare l'istanza di calcolo EC2 per il carico di lavoro del database


Per ulteriori informazioni, fare clic sui seguenti collegamenti:

link:hybrid_dbops_snapcenter_getting_started_onprem.html["On-premise"], link:hybrid_dbops_snapcenter_getting_started_aws.html["Cloud pubblico - AWS"]
