---
sidebar: sidebar 
permalink: databases/marketing_overview.html 
keywords: Linux, RHEL Oracle19c, NFS, ONTAP, Ansible 
summary: 'In questa pagina viene descritto il metodo automatizzato per l"implementazione di Oracle19c sullo storage NetApp ONTAP.' 
---
= Panoramica della soluzione
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/




== Implementazione automatica di Oracle19c per ONTAP su NFS

Le organizzazioni stanno automatizzando i propri ambienti per ottenere efficienze, accelerare le implementazioni e ridurre l'impegno manuale. I tool di gestione della configurazione come Ansible vengono utilizzati per ottimizzare le operazioni dei database aziendali. In questa soluzione, dimostreremo come utilizzare Ansible per automatizzare il provisioning e la configurazione di Oracle 19c con NetApp ONTAP. Consentendo agli amministratori dello storage, agli amministratori di sistema e ai DBA di implementare in modo coerente e rapido nuovo storage, configurare server di database e installare il software Oracle 19c, otterrete i seguenti vantaggi:

* Elimina le complessità di progettazione e gli errori umani e implementa un'implementazione coerente e ripetibile e Best practice
* Riduzione dei tempi di provisioning dello storage, configurazione degli host DB e installazione di Oracle
* Aumenta la produttività di amministratori di database, sistemi e amministratori dello storage
* Scalabilità di storage e database con facilità


NetApp offre ai clienti i moduli e i ruoli Ansible validati per accelerare l'implementazione, la configurazione e la gestione del ciclo di vita del tuo ambiente di database Oracle. Questa soluzione fornisce istruzioni e codice del playbook Ansible per aiutarti a:

* Creare e configurare lo storage NFS ONTAP per il database Oracle
* Installare Oracle 19c su RedHat Enterprise Linux 7/8 o Oracle Linux 7/8
* Configurare Oracle 19c sullo storage NFS ONTAP


Per ulteriori dettagli o per iniziare, consulta i video di panoramica riportati di seguito.



=== Implementazioni AWX/tower

Parte 1: Introduzione, requisiti, dettagli di automazione e configurazione iniziale AWX/Tower

.Implementazione AWX
video::d844a9c3-4eb3-4512-bf21-b01200f09f66[panopto]
Parte 2: Variabili ed esecuzione del Playbook

.AWX Playbook Run
video::6da1b960-e1c9-4950-b750-b01200f0bdfa[panopto]


=== Implementazione della CLI

Parte 1: Guida introduttiva, requisiti, dettagli di automazione e configurazione host di Ansible Control

.Implementazione della CLI
video::373e7f2a-c101-4292-a3e4-b01200f0d078[panopto]
Parte 2: Variabili ed esecuzione del Playbook

.Esecuzione del Playbook CLI
video::d58ebdb0-8bac-4ef9-b4d1-b01200f95047[panopto]