---
sidebar: sidebar 
permalink: databases/sql-srv-anf_conclusion.html 
keywords: takeaways, hybrid-cloud 
summary: Sia che tu stia prendendo di mira un cloud all-cloud o ibrido con database stretch, Azure NetApp Files offre opzioni eccellenti per implementare e gestire i carichi di lavoro del database, riducendo al contempo il TCO rendendo i requisiti dei dati perfetti a livello applicativo. 
---
= Conclusione
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
Sia che tu stia prendendo di mira un cloud all-cloud o ibrido con database stretch, Azure NetApp Files offre opzioni eccellenti per implementare e gestire i carichi di lavoro del database, riducendo al contempo il TCO rendendo i requisiti dei dati perfetti a livello applicativo.

In questo documento vengono illustrati i consigli per la pianificazione, la progettazione, l'ottimizzazione e la scalabilità delle implementazioni di Microsoft SQL Server con Azure NetApp Files, che possono variare notevolmente da un'implementazione all'altra. La soluzione giusta dipende sia dai dettagli tecnici dell'implementazione che dai requisiti di business alla base del progetto.



== Punti da asporto

I punti chiave di questo documento includono:

* È ora possibile utilizzare Azure NetApp Files per ospitare il database e il testimone della condivisione file per il cluster SQL Server.
* È possibile aumentare i tempi di risposta delle applicazioni e fornire una disponibilità del 99.9999% per fornire l'accesso ai dati di SQL Server quando e dove necessario.
* È possibile semplificare la complessità generale dell'implementazione di SQL Server e la gestione continua, come lo striping raid, con un ridimensionamento semplice e istantaneo.
* Puoi affidarti a funzionalità operative intelligenti per implementare i database SQL Server in pochi minuti e accelerare i cicli di sviluppo.
* Se Azure Cloud è la destinazione, Azure NetApp Files è la soluzione di storage giusta per un'implementazione ottimizzata.

