---
sidebar: sidebar 
permalink: databases/tr-4722.html 
keywords:  
summary:  
---
= TR-4722: Database MySQL su Best practice NetApp ONTAP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


Anup Bharti, Manohar Kulkarni, Jeffrey Steiner NetApp

[role="lead"]
MySQL e le sue varianti, tra cui MariaDB e Percona, sono ampiamente utilizzate per molte applicazioni aziendali. Variano da siti di social networking a livello globale e grandi sistemi di e-commerce a sistemi di hosting per PMI contenenti migliaia di istanze di database. Questo documento descrive i requisiti di configurazione e fornisce istruzioni sull'ottimizzazione e la configurazione dello storage per la distribuzione di MySQL sul software di gestione dati NetApp® ONTAP®. Per determinare se l'ambiente, le configurazioni e le versioni specificate in questo report supportano il tuo ambiente, consulta l'Interoperability Matrix Tool (IMT).

link:https://www.netapp.com/pdf.html?item=/media/16423-tr-4722pdf.pdf["TR-4722: Database MySQL su Best practice NetApp ONTAP"^]
