---
sidebar: sidebar 
permalink: databases/tr-4250-link.html 
keywords:  
summary:  
---
= TR-4250: SAP con Oracle su UNIX e NFS con NetApp Clustered Data ONTAP e SnapManager per SAP 3.4
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


Nils Bauer, NetApp

TR-4250 affronta le sfide legate alla progettazione di soluzioni storage per supportare i prodotti di business suite SAP utilizzando un database Oracle. L'obiettivo principale di questo documento è rappresentato dalle sfide comuni di progettazione, implementazione, funzionamento e gestione dell'infrastruttura storage affrontate dai leader aziendali e IT che utilizzano le soluzioni SAP di ultima generazione. Le raccomandazioni contenute in questo documento sono generiche e non sono specifiche di un'applicazione SAP o delle dimensioni e dell'ambito dell'implementazione SAP. TR-4250 presuppone che il lettore abbia una conoscenza di base della tecnologia e del funzionamento dei prodotti NetApp e SAP. TR-4250 è stato sviluppato in base all'interazione dello staff tecnico di NetApp, SAP, Oracle e dei nostri clienti.

link:https://www.netapp.com/pdf.html?item=/media/19525-tr-4250.pdf["TR-4250: SAP con Oracle su UNIX e NFS con NetApp Clustered Data ONTAP e SnapManager per SAP 3.4"^]
