---
sidebar: sidebar 
permalink: ehc/ncvs/ncvs-gc-additional-information.html 
keywords:  
summary:  
---
= Informazioni aggiuntive, cronologia delle versioni e informazioni di contatto
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../../media/


link:ncvs-gc-service-operation.html["Precedente: Operazione di servizio."]

[role="lead"]
Per ulteriori informazioni sulle informazioni descritte in questo documento, consultare i seguenti documenti e/o siti Web:

* Documentazione Google Cloud per Cloud Volumes Service
+
https://cloud.google.com/architecture/partners/netapp-cloud-volumes/["https://cloud.google.com/architecture/partners/netapp-cloud-volumes/"^]

* Accesso al servizio privato di Google
+
https://cloud.google.com/vpc/docs/private-services-access?hl=en_US["https://cloud.google.com/vpc/docs/private-services-access?hl=en_US"^]

* Documentazione sui prodotti NetApp
+
https://www.netapp.com/support-and-training/documentation/["https://www.netapp.com/support-and-training/documentation/"^]

* Programma del modulo di convalida crittografica: NetApp CryptoMod
+
https://csrc.nist.gov/projects/cryptographic-module-validation-program/certificate/4144["https://csrc.nist.gov/projects/cryptographic-module-validation-program/certificate/4144"^]

* La soluzione NetApp per ransomware
+
https://www.netapp.com/pdf.html?item=/media/16716-sb-3938pdf.pdf&v=202093745["https://www.netapp.com/pdf.html?item=/media/16716-sb-3938pdf.pdf&v=202093745"^]

* TR-4616: NFS Kerberos in ONTAP
+
https://www.netapp.com/pdf.html?item=/media/19384-tr-4616.pdf["https://www.netapp.com/pdf.html?item=/media/19384-tr-4616.pdf"^]





== Cronologia delle versioni

|===
| Versione | Data | Cronologia delle versioni del documento 


| Versione 1.0 | Maggio 2022 | Release iniziale. 
|===


== Contattaci

Facci sapere come possiamo migliorare questo report tecnico.

Contattaci all'indirizzo mailto:doccomments@netapp.com[doccomments@netapp.com^]. Includere IL REPORT TECNICO 4918 nell'oggetto.
