---
sidebar: sidebar 
permalink: ehc/ncvs/ncvs-gc-basics-of-nas-protocols.html 
keywords: nas, basics, gcp, nfs, smb 
summary: I protocolli NAS consentono a più client su una rete di accedere agli stessi dati su un sistema storage, ad esempio Cloud Volumes Service su GCP. NFS e SMB sono i protocolli NAS definiti e operano su base client/server, dove Cloud Volumes Service agisce come server. 
---
= Nozioni di base sui protocolli NAS
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../../media/


link:ncvs-gc-nas-protocols_overview.html["Precedente: Panoramica dei protocolli NAS."]

[role="lead"]
I protocolli NAS consentono a più client su una rete di accedere agli stessi dati su un sistema storage, ad esempio Cloud Volumes Service su GCP. NFS e SMB sono i protocolli NAS definiti e operano su base client/server, dove Cloud Volumes Service agisce come server. I client inviano al server richieste di accesso, lettura e scrittura e il server è responsabile del coordinamento dei meccanismi di blocco dei file, dell'archiviazione delle autorizzazioni e della gestione delle richieste di identità e autenticazione.

Ad esempio, se un client NAS desidera creare un nuovo file in una cartella, viene seguita la seguente procedura generale.

. Il client richiede al server informazioni sulla directory (permessi, proprietario, gruppo, ID file, spazio disponibile, e così via); il server risponde con le informazioni se il client richiedente e l'utente hanno le autorizzazioni necessarie sulla cartella padre.
. Se le autorizzazioni sulla directory consentono l'accesso, il client chiede al server se il nome del file creato esiste già nel file system. Se il nome del file è già in uso, la creazione non riesce. Se il nome del file non esiste, il server comunica al client che può procedere.
. Il client invia una chiamata al server per creare il file con l'handle di directory e il nome del file e imposta l'accesso e i tempi di modifica. Il server invia un ID file univoco al file per assicurarsi che non vengano creati altri file con lo stesso ID.
. Il client invia una chiamata per controllare gli attributi del file prima dell'operazione DI SCRITTURA. Se le autorizzazioni lo consentono, il client scrive il nuovo file. Se il protocollo/applicazione utilizza il blocco, il client richiede al server un blocco per impedire ad altri client di accedere al file mentre sono bloccati per evitare il danneggiamento dei dati.


link:ncvs-gc-nfs.html["Avanti: NFS."]
