---
sidebar: sidebar 
permalink: ehc/azure/azure-avs.html 
keywords: NetApp Solutions, hyperscalers, azure, avs, enterprise, hybrid, cloud, migrate, migration, disaster recovery, dr 
summary:  
---
= Funzionalità NetApp per Azure AVS
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../../media/


[role="lead"]
Scopri di più sulle funzionalità offerte da NetApp alla soluzione Azure VMware (AVS): Da NetApp come dispositivo di storage connesso come guest o come datastore NFS supplementare alla migrazione dei flussi di lavoro, all'estensione/diffusione nel cloud, al backup/ripristino e al disaster recovery.

Passare alla sezione relativa al contenuto desiderato selezionando una delle seguenti opzioni:

* link:#config["Configurazione di AVS in Azure"]
* link:#datastore["Opzioni di storage NetApp per AVS"]
* link:#solutions["Soluzioni cloud NetApp/VMware"]




== Configurazione di AVS in Azure

Come per i sistemi on-premise, la pianificazione di un ambiente di virtualizzazione basato sul cloud è fondamentale per un ambiente pronto per la produzione di successo per la creazione di macchine virtuali e la migrazione.

Questa sezione descrive come configurare e gestire Azure VMware Solution e utilizzarla in combinazione con le opzioni disponibili per la connessione dello storage NetApp.


NOTE: Lo storage in-guest è l'unico metodo supportato per connettere Cloud Volumes ONTAP alla soluzione VMware Azure.

Il processo di installazione può essere suddiviso nei seguenti passaggi:

* Registrare il provider di risorse e creare un cloud privato
* Connettersi a un gateway di rete virtuale ExpressRoute nuovo o esistente
* Convalidare la connettività di rete e accedere al cloud privato


Visualizza i dettagli link:azure-setup.html["Procedura di configurazione per AVS"].



== Opzioni di storage NetApp per AVS

Lo storage NetApp può essere utilizzato in diversi modi, come congettura connessa o come datastore NFS supplementare, all'interno di Azure AVS.

Visitare il sito link:../ehc-support-configs.html["Opzioni di storage NetApp supportate"] per ulteriori informazioni.

Azure supporta lo storage NetApp nelle seguenti configurazioni:

* Azure NetApp Files (ANF) come storage connesso guest
* Cloud Volumes ONTAP (CVO) come storage connesso guest
* Azure NetApp Files (ANF) come datastore NFS supplementare


Visualizza i dettagli link:azure-guest.html["Opzioni di storage di connessione guest per AVS"]. Visualizza i dettagli link:azure-native-nfs-datastore-option.html["Opzioni aggiuntive del datastore NFS per AVS"].



== Casi di utilizzo della soluzione

Con le soluzioni cloud NetApp e VMware, molti casi di utilizzo sono semplici da implementare in Azure AVS. I casi se sono definiti per ciascuna delle aree cloud definite da VMware:

* Protect (include disaster recovery e backup/ripristino)
* Estendi
* Migrare


link:azure-solutions.html["Esplora le soluzioni NetApp per Azure AVS"]
