---
sidebar: sidebar 
permalink: vmware/netapp-vsphere8.html 
keywords: netapp, vmware, getting, started 
summary:  
---
= Supporto NetApp per vSphere 8
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
La partnership tra NetApp e VMware è l'unica partnership in cui un singolo sistema storage si occupa di tutti i principali casi di utilizzo definiti da VMware.



== All-flash moderno e connesso al cloud per vSphere 8

Le implementazioni di ONTAP vengono eseguite su una vasta gamma di piattaforme, tra cui appliance progettate da NetApp, commodity hardware e nel cloud pubblico. ONTAP offre uno storage unificato sia con l'accesso a protocolli SAN o NAS e in configurazioni che spaziano da flash ad alta velocità a supporti più economici fino allo storage basato sul cloud. NetApp offre inoltre piattaforme flash costruite ad hoc per semplificare e segmentare le esigenze di storage senza la creazione di silos. Inoltre, NetApp offre un software per permettere facilmente lo spostamento dei dati tra ambienti on-premise e cloud. Infine, NetApp BlueXP mette a disposizione una singola dashboard per la gestione di tutte queste relazioni e dell'impatto dello storage.

* link:https://docs.netapp.com/us-en/ontap-systems-family/intro-family.html["Piattaforme NetApp"]
* link:../ehc/index.html["Multicloud ibrido NetApp con soluzioni VMware"]

