---
sidebar: sidebar 
permalink: vmware/vmw-getting-started-vm-data-collector.html 
keywords: vmware, getting, started, overview, netapp, vm, data, collector, vmdc 
summary:  
---
= VMDC (VM Data Collector)
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Un componente chiave del dimensionamento corretto e della proiezione di possibili opportunità di ottimizzazione è la comprensione dello stato attuale dell'ambiente VMware.



== Introduzione

Virtual Machine Data Collector (VMDC) è un toolkit gratuito, leggero e semplice basato su GUI per ambienti VMware che consente agli utenti di raccogliere informazioni dettagliate sull'inventario delle macchine virtuali (VM), degli host, dello storage e delle reti.

Per ulteriori informazioni su Virtual Machine Data Collector, vedere link:https://docs.netapp.com/us-en/netapp-solutions/vmware/vmdc.html["Documentazione di Virtual Machine Data Collector"].



== Funzionalità VMDC

VMDC è solo una pietra miliare per la raccolta di statistiche rapide e istantanee per la progettazione di possibilità di ottimizzazione per le licenze di base VMware insieme a vCPU e RAM. Le informazioni sull'infrastruttura dati NetApp, che richiedono l'installazione di aus e raccoglitori di dati, dovrebbero essere la fase successiva più ovvia per comprendere la topologia dettagliata delle macchine virtuali, il raggruppamento delle macchine virtuali utilizzando l'annotazione in modo da dimensionare correttamente i carichi di lavoro e garantire una prova futura dell'infrastruttura.

Campionamento delle metriche raccolte con VMDC:

* Informazioni VM
+
** Nome VM
** Stato alimentazione VM
** Informazioni CPU VM
** Informazioni sulla memoria VM
** Posizione VM
** Informazioni sulla rete VM
** e molto altro ancora


* Performance delle macchine virtuali
+
** Dati sulle prestazioni delle macchine virtuali all'intervallo selezionato
** Informazioni di lettura/scrittura VM
** Informazioni IOPS delle VM
** Latenza delle VM
** e molto altro ancora


* Informazioni sull'host ESXi
+
** Informazioni sul data center host
** Informazioni sul cluster host
** Informazioni sul modello host
** Informazioni sulla CPU host
** Informazioni sulla memoria host
** e molto altro ancora



