---
sidebar: sidebar 
permalink: vmware/vmw-vcf-protect-sc.html 
keywords: vmware, vcf, protect, snapcenter 
summary:  
---
= Proteggi i carichi di lavoro con SnapCenter
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Il plug-in SnapCenter per VMware vSphere migliora VMware Cloud Foundation semplificando backup e recovery, garantendo backup coerenti con l'applicazione e ottimizzando lo storage con le tecnologie di efficienza di NetApp.

Supporta flussi di lavoro automatizzati e operazioni scalabili fornendo al contempo un'integrazione perfetta con il client vSphere. Grazie alla replica SnapMirror che offre backup secondario on-premise o nel cloud, offre una solida data Protection ed efficienza delle operazioni negli ambienti virtualizzati.

Per ulteriori dettagli, fare riferimento alle seguenti soluzioni.

* link:vmw-vcf-scv-wkld.html["Proteggi il dominio del carico di lavoro VCF"]
* link:vmw-vcf-scv-multiwkld.html["Proteggere i domini multipli del carico di lavoro VCF"]
* link:vmw-vcf-scv-nvme.html["Proteggi il dominio del carico di lavoro VCF con NVMe"]
* link:vmw-vcf-scv-321.html["Data Protection 3-2-1 per VMware con plug-in SnapCenter e backup e recovery BlueXP per le VM"]

