---
sidebar: sidebar 
permalink: vmware/vmw-getting-started-migration.html 
keywords: vmware, getting, started, overview, netapp 
summary:  
---
= Migrazione di macchine virtuali su datastore supportati da ONTAP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
La migrazione dei carichi di lavoro VMware su NetApp ONTAP semplifica la gestione dei dati e migliora le performance tramite le funzionalità di storage avanzate di ONTAP come la deduplica, la compressione e le snapshot efficienti.



== Introduzione

Questa migrazione abilita una perfetta integrazione, una protezione dei dati migliorata e una maggiore flessibilità nella gestione degli ambienti virtualizzati, garantendo una transizione fluida con tempi di inattività minimi.

Per ulteriori informazioni sulla migrazione dei carichi di lavoro VMware in datastore supportati da ONTAP, vedere link:https://docs.netapp.com/us-en/netapp-solutions/vmware/migrate-vms-to-ontap-datastore.html["Migrazione delle macchine virtuali nei datastore ONTAP"].



== Casi di utilizzo

Esistono molte opzioni di migrazione in termini di origine e destinazione quando si considera di passare ai datastore supportati da ONTAP.

* Migrazione dai sistemi storage di terze parti (incluso vSAN) ai datastore ONTAP.
* Migrazione di macchine virtuali nello stesso cluster vSphere
* Migrazione di VM in più cluster vSphere
* Migrazione di VM tra server vCenter nello stesso dominio SSO
* Migrazione di VM tra server vCenter in domini SSO diversi
* Migrazione di VM nelle ubicazioni dei data center
* Migrazione dai sistemi storage di terze parti (incluso vSAN) ai datastore ONTAP.
* Migrazione delle VM in un ambiente di cloud ibrido

