---
sidebar: sidebar 
permalink: vmware/vmw-vcf-draas-bxp.html 
keywords: vmware, vcf, dr, disaster recovery, draas, bluexp 
summary:  
---
= Disaster recovery con BlueXP  DRaaS
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Disaster Recovery as a Service (DRaaS) implementazione di disaster recovery tramite replica a livello di blocco da un sito primario a un sito di disaster recovery NetApp BlueXP .

BlueXP  DRaaS è un metodo efficace ed economico per proteggere i workload dai guasti del sito e dai problemi di integrità dei dati, inclusi gli attacchi ransomware. Inoltre, NetApp BlueXP  DRaaS ottimizza questa strategia fornendo una soluzione di disaster recovery gestita e basata sul cloud, garantendo un ripristino rapido e un downtime minimo in caso di disastri.

Per i dettagli tecnici, fare riferimento alle seguenti soluzioni.

* link:vmw-dr-draas-vmfs.html["Dr utilizzando BlueXP  DRaaS per archivi dati VMFS"]
* link:vmw-dr-draas-nfs.html["Dr utilizzando BlueXP  DRaaS per datastore NFS"]

