---
sidebar: sidebar 
permalink: vmware/vmw-getting-started-hybrid-multicloud.html 
keywords: vmware, getting, started, overview, netapp, hybrid, multicloud, multi, cloud 
summary:  
---
= Multi-Cloud ibrido
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Le architetture di multicloud ibrido di VMware con NetApp consentono un'integrazione perfetta tra infrastruttura on-premise e servizi di cloud pubblico, garantendo flessibilità e scalabilità.



== Introduzione

Questo approccio permette alle aziende di migrare facilmente i carichi di lavoro, ottimizzare l'utilizzo delle risorse e mantenere operazioni coerenti in entrambi gli ambienti.

Per ulteriori informazioni sugli scenari di cloud ibrido con VMware e NetApp, vedere link:https://docs.netapp.com/us-en/netapp-solutions/ehc/ehc-overview.html#vmware-cloud-options-in-public-cloud["Panoramica del multicloud ibrido NetApp con VMware"].



== Scenari di implementazione di VMware con NetApp

Questa sezione descrive le varie opzioni di implementazione per gli ambienti VMware nei cloud on-premise e pubblici. Ciascun cloud provider supporta uno stack SDDC (Software Defined Data Center) e/o VCF (VMware Cloud Foundation) all'interno delle rispettive offerte di cloud pubblico.

* *VMware on-premise*


L'utilizzo di VMware con storage NetApp on-premise offre un ambiente di virtualizzazione solido, scalabile e flessibile. Abbinando le funzionalità avanzate di gestione dei dati di NetApp, come deduplica, compressione e snapshot efficienti, con il sistema storage appropriato basato su ONTAP, i clienti possono scegliere la piattaforma che fa per loro. Questa combinazione garantisce prestazioni elevate, affidabilità e gestione semplificata per i carichi di lavoro virtualizzati, migliorando l'efficienza complessiva del centro dati.

* *Soluzione Azure VMware*


Azure VMware Solution è un servizio di cloud ibrido che consente il funzionamento completo degli SDDC VMware nel cloud pubblico Microsoft Azure. Azure VMware Solution è una soluzione di prima parte completamente gestita e supportata da Microsoft, verificata da VMware sfruttando l'infrastruttura Azure. Ciò significa che quando Azure VMware Solution viene implementata, i clienti ottengono VMware ESXi per la virtualizzazione del calcolo, vSAN per lo storage iperconvergente, E NSX per il networking e la sicurezza, il tutto sfruttando la presenza globale di Microsoft Azure, le strutture di data center leader di settore e la vicinanza al ricco ecosistema di servizi e soluzioni Azure native.

* *VMware Cloud on AWS*


VMware Cloud su AWS porta il software SDDC di livello Enterprise di VMware su AWS Cloud con accesso ottimizzato ai servizi AWS nativi. Basato su VMware Cloud Foundation, VMware Cloud su AWS integra i prodotti di calcolo, storage e virtualizzazione di rete di VMware (VMware vSphere, VMware vSAN e VMware NSX) insieme alla gestione di VMware vCenter Server, ottimizzata per l'esecuzione su un'infrastruttura AWS bare-metal flessibile e dedicata.

* *Google Cloud VMware Engine*


Google Cloud VMware Engine è un'offerta Infrastructure-as-a-service (IaaS) costruita sull'infrastruttura scalabile e dalle performance elevate di Google Cloud e sullo stack di VMware Cloud Foundation - VMware vSphere, vCenter, vSAN e NSX-T. questo servizio permette un percorso rapido verso il cloud, una migrazione o un'estensione perfetta dei carichi di lavoro VMware esistenti dagli ambienti on-premise a Google Cloud Platform senza i costi, lo sforzo o il rischio di riprogettare le applicazioni o di riorganizzare le operazioni. Si tratta di un servizio venduto e supportato da Google, che lavora a stretto contatto con VMware.
