---
sidebar: sidebar 
permalink: vmware/vmw-getting-started-bluexp-disaster-recovery.html 
keywords: vmware, getting, started, overview, netapp, bluexp, disaster, recovery, draas 
summary:  
---
= Disaster recovery BlueXP  (DRaaS)
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
La pianificazione del disaster recovery è fondamentale per gli amministratori VMware per ridurre al minimo i tempi di inattività in caso di guasti hardware, attacchi informatici o disastri naturali.



== Introduzione

Disporre di un piano di successo e di una combinazione di tecnologie garantisce la protezione di dati critici, applicazioni e VM. La sfida del disaster recovery è determinare il livello di protezione e i costi associati adeguati.

Gli array ONTAP offrono una replica integrata per trasferire i dati dei volumi, e quindi le macchine virtuali che risiedono nelle LUN del datastore designate, da un sito all'altro. BlueXP  DRaaS si integra con vSphere e automatizza l'intero flusso di lavoro per un failover e un failback perfetti in caso di emergenza.

Per ulteriori informazioni su BlueXP  DRaaS, vedere link:https://docs.netapp.com/us-en/netapp-solutions/ehc/dr-draas-overview.html["Panoramica di BlueXP  DRaaS"].



== Considerazioni

Le parti più lunghe di un failover del disaster recovery in un ambiente VMware vSphere sono l'esecuzione dei passaggi necessari per inventariare, registrare, riconfigurare e accendere le macchine virtuali nel sito di disaster recovery. Una soluzione ideale presenta un RPO basso (misurato in minuti) e un RTO basso (misurato in minuti-ore). Un fattore spesso trascurato in una soluzione di DR è la possibilità di testare in modo efficiente la soluzione DR su un intervallo periodico.

Per progettare una soluzione di DR, tenere presente i seguenti fattori:

* L'obiettivo RTO (Recovery Time Objective). L'RTO rappresenta la velocità con cui un'azienda può eseguire il ripristino da un evento disastroso o, in particolare, il tempo necessario per eseguire il processo di ripristino e rendere nuovamente disponibili i servizi aziendali.
* L'obiettivo RPO (Recovery Point Objective). L'RPO indica la data di nascita dei dati recuperati dopo che sono stati resi disponibili, in relazione al tempo in cui si è verificato il disastro.
* Scalabilità e adattabilità. Questo fattore include la possibilità di aumentare le risorse di storage in maniera incrementale con l'aumentare della domanda.


Per ulteriori informazioni tecniche sulle soluzioni disponibili, vedere:

* link:https://docs.netapp.com/us-en/netapp-solutions/ehc/dr-draas-nfs.html["Dr utilizzando BlueXP  DRaaS per datastore NFS"]
* link:https://docs.netapp.com/us-en/netapp-solutions/ehc/dr-draas-vmfs.html["Dr utilizzando BlueXP  DRaaS per archivi dati VMFS"]

