---
sidebar: sidebar 
permalink: vmware/vmw-vcf-provision.html 
keywords: vmware, vcf, provision, principal, storage 
summary:  
---
= Provisioning dell'ambiente VCF con l'archiviazione principale
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Lo storage NetApp ONTAP rappresenta la soluzione di storage principale ideale per la gestione di VMware Cloud Foundation (VCF) e i domini di workload VI, offrendo performance elevate, scalabilità, gestione avanzata dei dati e integrazione perfetta, che migliorano collettivamente l'efficienza operativa e la protezione dei dati.

Fare riferimento alle seguenti soluzioni per i dettagli tecnici sul provisioning di un ambiente VCF nel dominio appropriato e con il protocollo appropriato.

* link:vmw-vcf-mgmt-principal-fc.html["Dominio di gestione con FC"]
* link:vmw-vcf-mgmt-principal-nfs.html["Dominio di gestione con NFS"]
* link:vmw-vcf-viwld-principal-fc.html["Dominio del carico di lavoro dell'infrastruttura virtuale con FC"]
* link:vmw-vcf-viwld-principal-nfs.html["Dominio del carico di lavoro dell'infrastruttura virtuale con NFS"]

