---
sidebar: sidebar 
permalink: vmware/vmw-vcf-protect-vmsc.html 
keywords: vmware, vcf, protect, vmsc, vsphere, metro, storage, cluster 
summary:  
---
= Alta disponibilità con VMware vSphere Metro Storage Cluster (vMSC)
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
L'alta disponibilità NetApp ONTAP, integrato con VMware vSphere Metro Storage Cluster (vMSC), fornisce una solida soluzione per la gestione di VMware Cloud Foundation (VCF) e i domini del carico di lavoro VI.

Questa combinazione garantisce disponibilità continua dei dati, failover perfetto e disaster recovery in siti dispersi geograficamente, migliorando la resilienza e la continuità operativa per i carichi di lavoro critici. La sincronizzazione attiva di SnapMirror consente ai servizi di business di continuare a funzionare anche in caso di guasto completo del sito, supportando il failover delle applicazioni in modo trasparente utilizzando una copia secondaria. Non sono richiesti interventi manuali o script personalizzati per attivare un failover con la sincronizzazione attiva di SnapMirror.

Per ulteriori dettagli, fare riferimento alle seguenti soluzioni.

* link:vmw-vcf-vmsc-mgmt-smas.html["Cluster stretch per dominio di gestione che utilizza la sincronizzazione attiva di SnapMirror"]
* link:vmw-vcf-vmsc-mgmt-mcc.html["Cluster stretch per dominio di gestione con MetroCluster"]
* link:vmw-vcf-vmsc-viwld-smas.html["Cluster stretch per dominio del carico di lavoro VI con sincronizzazione attiva SnapMirror"]
* link:vmw-vcf-vmsc-viwld-mcc.html["Cluster stretch per dominio del carico di lavoro VI con MetroCluster"]

