---
sidebar: sidebar 
permalink: vmware/vmw-getting-started-data-infrastructure-insights.html 
keywords: vmware, getting, started, overview, netapp, data, infrastructure, insights, dii 
summary:  
---
= Informazioni sull'infrastruttura dati (DII)
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
NetApp Data Infrastructure Insights è un tool di monitoraggio dell'infrastruttura cloud che ti offre visibilità sulla tua completa infrastruttura.



== Introduzione

Con Data Infrastructure Insights puoi monitorare, risolvere i problemi e ottimizzare tutte le risorse, inclusi cloud pubblici e data center privati.

Per ulteriori informazioni su Data Infrastructure Insights, vedere link:https://docs.netapp.com/us-en/data-infrastructure-insights/index.html["Documentazione di approfondimento sull'infrastruttura dati"].



== Funzionalità di Data Infrastructure Insights

* Data Infrastructure Insights offre il monitoring del multicloud ibrido, offrendo un'osservabilità full-stack di infrastruttura e carichi di lavoro.
* Raccolta di dati per infrastrutture e carichi di lavoro eterogenei, tra cui Kubernetes
* Aprire Telegraf Collector e aprire le API per una facile integrazione
* Avvisi e notifiche completi
* Apprendimento automatico per informazioni intelligenti
* Ottimizzare l'utilizzo delle risorse
* Dashboard integrate o personalizzabili con filtri avanzati per ridurre al minimo il rumore dello schermo per rispondere alle domande
* Scopri lo stato delle tue operazioni di storage ONTAP 
* Proteggi la tua risorsa di business più preziosa, i dati, dagli attacchi ransomware o di distruzione dei dati

