---
sidebar: sidebar 
permalink: vmware/vmw-vcf-migrate.html 
keywords: vmware, vcf, migrate, import 
summary:  
---
= Migrare l'infrastruttura esistente a VCF
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
La conversione di un ambiente vSphere con datastore esistenti in esecuzione su ONTAP in un ambiente VMware Cloud Foundation (VCF) comporta l'integrazione dell'infrastruttura esistente in una moderna architettura di cloud privato.

Questo processo sfrutta la flessibilità dello storage ONTAP per garantire un accesso e una gestione perfetti dei dati. Una volta stabilito il dominio di gestione VCF, gli amministratori possono importare in modo efficiente altri ambienti vSphere nell'ecosistema VCF. Questa integrazione migliora l'utilizzo delle risorse, semplifica la gestione del cloud privato e garantisce una transizione fluida con interruzioni minime per i carichi di lavoro esistenti.

Fare riferimento alle seguenti soluzioni per i dettagli tecnici sulla conversione di un'istanza di vCenter.

* link:vmw-vcf-mgmt-nfs.html["Conversione dell'istanza vCenter esistente in VCF Management Domain (NFS)"]
* link:vmw-vcf-mgmt-fc.html["Convertire l'istanza vCenter (datastore FC) in dominio di gestione VCF"]

