---
sidebar: sidebar 
permalink: vmware/vmw-vcf-expand.html 
keywords: vmware, vcf, expand, supplemental, storage 
summary:  
---
= Espandere ambiente VCF con archiviazione supplementare
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
VMware Cloud Foundation (VCF) supporta un'ampia gamma di opzioni di storage supplementari per espandere lo storage sui domini di gestione VCF e di carico di lavoro VI.

Gli strumenti ONTAP di NetApp per VMware vSphere offrono una soluzione efficiente per questa espansione, integrando perfettamente lo storage NetApp nell'ambiente VCF. I tool ONTAP semplificano l'installazione e la gestione dei datastore, consentendo agli amministratori di eseguire il provisioning e gestire lo storage direttamente dal client vSphere. Le funzionalità avanzate di ONTAP, come snapshot, cloning e protezione dei dati, migliorano le performance, l'efficienza e la scalabilità dello storage all'interno dell'ambiente VCF.

Fare riferimento alle seguenti soluzioni per i dettagli tecnici per espandere l'ambiente VCF.

* link:vmw-vcf-mgmt-supplemental-iscsi.html["Dominio di gestione con iSCSI"]
* link:vmw-vcf-mgmt-supplemental-fc.html["Dominio di gestione con FC"]
* link:vmw-vcf-viwld-supplemental-vvols.html["Dominio del carico di lavoro dell'infrastruttura virtuale con vVol (iSCSI)"]
* link:vmw-vcf-viwld-supplemental-nfs-vvols.html["Dominio del carico di lavoro dell'infrastruttura virtuale con vVol (NFS)"]
* link:vmw-vcf-viwld-supplemental-nvme.html["Dominio del carico di lavoro dell'infrastruttura virtuale con NVMe/TCP"]
* link:vmw-vcf-viwld-supplemental-fc.html["Dominio del carico di lavoro dell'infrastruttura virtuale con FC"]

