---
sidebar: sidebar 
permalink: vmware/vmw-vcf-viwld-principal-fc.html 
keywords: netapp, vmware, cloud, foundation, vcf, asa, all-flash, array, ontap tools, otv, sddc, fc 
summary:  
---
= VMFS su FC come storage principale per i domini del carico di lavoro VI
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
In questo scenario verrà descritto come configurare un datastore VMFS con Fiber Channel (FC) come storage principale per la distribuzione di un dominio del carico di lavoro VI in VCF. Se necessario, faremo riferimento alla documentazione esterna per le operazioni che devono essere eseguite in SDDC Manager di VCF e descriveremo le operazioni specifiche per la parte relativa alla configurazione dello storage.



== Vantaggi di Fibre Channel

*Prestazioni elevate:* FC offre velocità di trasferimento dati elevate, il che lo rende ideale per le applicazioni che richiedono un accesso rapido e affidabile a grandi quantità di dati.

*Bassa latenza:* latenza molto bassa, fondamentale per applicazioni sensibili alle performance come database e ambienti virtualizzati.

*Affidabilità:* le reti FC sono note per la loro robustezza e affidabilità, con caratteristiche come la ridondanza integrata e la correzione degli errori.

*Larghezza di banda dedicata:* FC fornisce una larghezza di banda dedicata per il traffico di storage, riducendo il rischio di congestione della rete.

Per ulteriori informazioni sull'utilizzo di Fibre Channel con i sistemi di storage NetApp, consultare https://docs.netapp.com/us-en/ontap/san-admin/san-provisioning-fc-concept.html["Provisioning di SAN con FC"] .



== Panoramica dello scenario

Questo scenario copre i seguenti passaggi di alto livello:

* Crea una Storage Virtual Machine (SVM) con interfacce logiche (LIF) per il traffico FC.
* Raccogliere le informazioni WWPN degli host da distribuire e creare i gruppi iniziatori corrispondenti sul sistema di archiviazione ONTAP.
* Crea un volume FC sul sistema storage ONTAP.
* Mappare i gruppi iniziatori per creare un volume FC
* Utilizzo di zoning a destinazione degli initiator singoli su switch FC. Creare una zona per ciascun iniziatore (singola zona iniziatore).
+
** Per ciascuna zona, includere una destinazione che sia l'interfaccia logica FC ONTAP (WWPN) per le SVM. Devono essere presenti almeno due interfacce logiche per nodo per SVM. Non utilizzare la WWPN delle porte fisiche.


* Creare un pool di rete per il traffico vMotion in SDDC Manager.
* Commissione di host in VCF per l'utilizzo in un dominio del carico di lavoro VI.
* Implementare un dominio del carico di lavoro VI in VCF utilizzando un datastore FC come storage principale.



NOTE: Questa soluzione è applicabile alle piattaforme ONTAP che supportano lo storage NFS, inclusi NetApp AFF e FAS.



== Prerequisiti

In questo scenario vengono utilizzati i seguenti componenti e configurazioni:

* Un sistema storage ONTAP AFF o ASA con porte FC collegate agli switch FC.
* SVM creata con life FC.
* VSphere con HBA FC collegati agli switch FC.
* Lo zoning a initiator singolo target è configurato sugli switch FC.



NOTE: NetApp consiglia un multipath per le LUN FC.



== Fasi di implementazione



=== Dominio di gestione - Cluster predefinito

Lo storage principale FC sul cluster iniziale è supportato solo con lo strumento di importazione dei campi di brownfield VCF. Se VCF viene implementato con lo strumento cloudbuilder (fino alla versione 5,2.x), è supportato solo VSAN. Per ulteriori informazioni, fare riferimento alla sezione https://techdocs.broadcom.com/us/en/vmware-cis/vcf/vcf-5-2-and-earlier/5-2/map-for-administering-vcf-5-2/importing-existing-vsphere-environments-admin/convert-or-import-a-vsphere-environment-into-vmware-cloud-foundation-admin.html["Conversione dell'ambiente vSphere esistente in dominio di gestione"].



=== Dominio di gestione - cluster aggiuntivo

Il cluster vSphere aggiuntivo nel dominio di gestione può essere distribuito con le seguenti opzioni: * Sono presenti cluster aggiuntivi nell'ambiente vSphere e utilizzano lo strumento di importazione brownfield di VCF per convertire l'ambiente vSphere nel dominio di gestione. https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere-10/configure/create-vvols-datastore.html["Strumenti ONTAP per VMware vSphere"], https://docs.netapp.com/us-en/ontap/san-admin/provision-storage.html["API di System Manager o ONTAP"] Può essere utilizzato per implementare il datastore VMFS nel cluster vSphere. * Utilizzare l'API SDDC per distribuire cluster aggiuntivi. Gli host vSphere devono avere configurato il datastore VMFS. Utilizzare https://docs.netapp.com/us-en/ontap/san-admin/provision-storage.html["API di System Manager o ONTAP"] per implementare LUN negli host vSphere. * Utilizzare l'interfaccia utente di SDDC Manager per distribuire cluster aggiuntivi. Ma questa opzione crea solo il datastore VSAN fino alla versione 5,2.x



=== Dominio carico di lavoro VI - cluster predefinito

Dopo aver attivato e attivato il dominio di gestione, è possibile creare il dominio del carico di lavoro VI:

* Utilizzo dell'interfaccia utente di SDDC Manager. Gli host vSphere devono avere configurato il datastore VMFS. Utilizza System Manager o l'API ONTAP per implementare LUN negli host vSphere.
* Importare un ambiente vSphere esistente come nuovo dominio del carico di lavoro VI. È possibile utilizzare i tool ONTAP per le API VMware vSphere, System Manager o ONTAP per implementare il datastore VMFS nel cluster vSphere.




=== Dominio carico di lavoro VI - cluster aggiuntivo

Una volta attivo e funzionante il carico di lavoro VI, è possibile implementare cluster aggiuntivi con VMFS su FC LUN usando le opzioni seguenti.

* Cluster aggiuntivi nell'ambiente vSphere importati utilizzando il tool di importazione Brownfield di VCF. È possibile utilizzare i tool ONTAP per le API VMware vSphere, System Manager o ONTAP per implementare il datastore VMFS nel cluster vSphere.
* Utilizzo dell'interfaccia utente o dell'API di SDDC Manager per l'implementazione di cluster aggiuntivi. Gli host vSphere devono avere configurato il datastore VMFS. Utilizza System Manager o l'API ONTAP per implementare LUN negli host vSphere.




== Ulteriori informazioni

Per informazioni sulla configurazione dei sistemi storage ONTAP, consultare la link:https://docs.netapp.com/us-en/ontap["Documentazione di ONTAP 9"] centro.

Per informazioni sulla configurazione di VCF, fare riferimento alla link:https://techdocs.broadcom.com/us/en/vmware-cis/vcf/vcf-5-2-and-earlier/5-2.html["Documentazione di VMware Cloud Foundation"].
