---
sidebar: sidebar 
permalink: vmware/vsphere_demos_videos.html 
keywords: vSphere, cloud, hybrid cloud, AWS, Azure, Google cloud, snapmirror cloud, cloud backup service, BlueXP Copy and Sync, FabricPool, ONTAP 
summary: 'Questa pagina fornisce un"introduzione a video ed esercitazioni.' 
---
= Video e demo sulla virtualizzazione
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Guarda i seguenti video e demo che illustrano le funzionalità specifiche delle soluzioni di cloud ibrido, virtualizzazione e container.

.Strumenti NetApp ONTAP per VMware vSphere
[%collapsible%open]
====
.Strumenti ONTAP per VMware - Panoramica
video::e8071955-f6f1-45a0-a868-b12a010bba44[panopto]
.Provisioning di archivi dati VMware iSCSI con ONTAP
video::5c047271-aecc-437c-a444-b01200f9671a[panopto]
.Provisioning di archivi dati VMware NFS con ONTAP
video::a34bcd1c-3aaa-4917-9a5d-b01200f97f08[panopto]
====
.Plug-in SnapCenter per VMware vSphere
[%collapsible%open]
====
Il software NetApp SnapCenter è una piattaforma aziendale di facile utilizzo per coordinare e gestire in modo sicuro la protezione dei dati tra applicazioni, database e file system.

Il plug-in SnapCenter per VMware vSphere consente di eseguire operazioni di backup, ripristino e collegamento per macchine virtuali e operazioni di backup e montaggio per datastore registrati con SnapCenter direttamente in VMware vCenter.

Per ulteriori informazioni sul plug-in NetApp SnapCenter per VMware vSphere, consultare la link:https://docs.netapp.com/ocsc-42/index.jsp?topic=%2Fcom.netapp.doc.ocsc-con%2FGUID-29BABBA7-B15F-452F-B137-2E5B269084B9.html["Panoramica del plug-in NetApp SnapCenter per VMware vSphere"].

.Plug-in SnapCenter per VMware vSphere - prerequisiti della soluzione
video::38881de9-9ab5-4a8e-a17d-b01200fade6a[panopto,width=360]
.Plug-in SnapCenter per VMware vSphere - implementazione
video::10cbcf2c-9964-41aa-ad7f-b01200faca01[panopto,width=360]
.Plug-in SnapCenter per VMware vSphere - flusso di lavoro di backup
video::b7272f18-c424-4cc3-bc0d-b01200faaf25[panopto,width=360]
.Plug-in SnapCenter per VMware vSphere - flusso di lavoro di ripristino
video::ed41002e-585c-445d-a60c-b01200fb1188[panopto,width=360]
.SnapCenter - flusso di lavoro di ripristino SQL
video::8df4ad1f-83ad-448b-9405-b01200fb2567[panopto,width=360]
====
.Soluzioni per la protezione dei dati 3-2-1
[%collapsible%open]
====
Le soluzioni per la protezione dei dati 3-2-1 combinano backup primari e secondari on-premise, utilizzando la tecnologia SnapMirror, con copie replicate sullo storage a oggetti utilizzando il backup e recovery di BlueXP.

.Protezione dei dati 3-2-1 per datastore VMFS con plug-in SnapCenter per backup e recovery di VMware vSphere e BlueXP per macchine virtuali
video::7c21f3fc-4025-4d8f-b54c-b0e001504c76[panopto,width=360]
====
.VMware Cloud su AWS con AWS FSX ONTAP
[%collapsible%open]
====
.Storage connesso guest Windows con FSX ONTAP utilizzando iSCSI
video::0d03e040-634f-4086-8cb5-b01200fb8515[panopto,width=360]
.Storage connesso guest Linux con FSX ONTAP con NFS
video::c3befe1b-4f32-4839-a031-b01200fb6d60[panopto,width=360]
.Risparmi sul TCO di VMware Cloud su AWS con Amazon FSX ONTAP
video::f0fedec5-dc17-47af-8821-b01200f00e08[panopto,width=360]
.Datastore supplementare di VMware Cloud su AWS con Amazon FSX ONTAP
video::2065dcc1-f31a-4e71-a7d5-b01200f01171[panopto,width=360]
.Installazione della configurazione e dell'implementazione di VMware HCX per VMC
video::6132c921-a44c-4c81-aab7-b01200fb5d29[panopto,width=360]
.Dimostrazione della migrazione VMotion con VMware HCX per VMC ed FSX ONTAP
video::52661f10-3f90-4f3d-865a-b01200f06d31[panopto,width=360]
.Dimostrazione della migrazione a freddo con VMware HCX per VMC ed FSX ONTAP
video::685c0dc2-9d8a-42ff-b46d-b01200f056b0[panopto,width=360]
====
.Azure servizi VMware su Azure con Azure NetApp Files (ANF)
[%collapsible%open]
====
.Panoramica del datastore supplementare della soluzione VMware Azure con Azure NetApp Files
video::8c5ddb30-6c31-4cde-86e2-b01200effbd6[panopto,width=360]
.Soluzione VMware Azure DR con Cloud Volumes ONTAP, SnapCenter e JetStream
video::5cd19888-8314-4cfc-ba30-b01200efff4f[panopto,width=360]
.Dimostrazione della migrazione a freddo con VMware HCX per AVS e ANF
video::b7ffa5ad-5559-4e56-a166-b01200f025bc[panopto,width=360]
.Dimostrazione di VMotion con VMware HCX per AVS e ANF
video::986bb505-6f3d-4a5a-b016-b01200f03f18[panopto,width=360]
.Dimostrazione della migrazione in blocco con VMware HCX per AVS e ANF
video::255640f5-4dff-438c-8d50-b01200f017d1[panopto,width=360]
====
.VMware Cloud Foundation con NetApp ONTAP
[%collapsible%open]
====
.Archivi dati NFS come archiviazione principale per i domini del carico di lavoro VCF
video::9b66ac8d-d2b1-4ac4-a33c-b16900f67df6[panopto]
.Archivi dati iSCSI come archiviazione supplementare per i domini di gestione VCF
video::1d0e1af1-40ae-483a-be6f-b156015507cc[panopto]
====
.NetApp con VMware Tanzu
[%collapsible%open]
====
VMware Tanzu consente ai clienti di implementare, amministrare e gestire il proprio ambiente Kubernetes tramite vSphere o VMware Cloud Foundation. Questo portfolio di prodotti VMware consente ai clienti di gestire tutti i cluster Kubernetes pertinenti da un singolo piano di controllo scegliendo l'edizione VMware Tanzu più adatta alle loro esigenze.

Per ulteriori informazioni su VMware Tanzu, consultare https://tanzu.vmware.com/tanzu["Panoramica di VMware Tanzu"^]. Questa recensione illustra i casi d'utilizzo, le aggiunte disponibili e molto altro ancora su VMware Tanzu.

.Come utilizzare vVol con NetApp e VMware Tanzu Basic, parte 1
video::ZtbXeOJKhrc[youtube,width=360]
.Come utilizzare vVol con NetApp e VMware Tanzu Basic, parte 2
video::FVRKjWH7AoE[youtube,width=360]
.Come utilizzare vVol con NetApp e VMware Tanzu Basic, parte 3
video::Y-34SUtTTtU[youtube,width=360]
====
.NetApp Cloud Insights
[%collapsible%open]
====
NetApp Cloud Insights è una piattaforma completa di monitoring e analytics progettata per fornire visibilità e controllo sulla tua infrastruttura cloud e on-premise.

.NetApp Cloud Insights - osservabilità per il moderno data center
video::1e4da521-3104-4d51-8cde-b0e001502d3d[panopto,width=360]
====