---
sidebar: sidebar 
permalink: vmware/vsphere_auto_introduction.html 
keywords: vSphere, cloud, hybrid cloud, AWS, Azure, Google cloud, snapmirror cloud, cloud backup service, BlueXP Copy and Sync, FabricPool, ONTAP 
summary: 'Questa pagina descrive i vantaggi dell"automazione delle funzionalità ONTAP di base in un ambiente VMware vSphere.' 
---
= Introduzione all'automazione per ONTAP e vSphere
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Questa pagina descrive i vantaggi dell'automazione delle funzionalità ONTAP di base in un ambiente VMware vSphere.



== Automazione VMware

L'automazione è parte integrante della gestione degli ambienti VMware fin dai primi giorni di VMware ESX. La capacità di implementare l'infrastruttura come codice ed estendere le pratiche alle operazioni del cloud privato aiuta ad alleviare i problemi legati a scalabilità, flessibilità, self-provisioning ed efficienza.

L'automazione può essere organizzata nelle seguenti categorie:

* *Implementazione dell'infrastruttura virtuale*
* *Operazioni della macchina guest*
* *Operazioni cloud*


Gli amministratori hanno a disposizione numerose opzioni per l'automazione dell'infrastruttura. Sia attraverso l'utilizzo di funzionalità vSphere native come profili host o specifiche di personalizzazione per le macchine virtuali alle API disponibili sui componenti software VMware, sui sistemi operativi e sui sistemi storage NetApp, sono disponibili documentazione e indicazioni significative.

Data ONTAP 8.0.1 e versioni successive supportano alcune API VMware vSphere per l'integrazione degli array (VAAI) quando l'host ESX esegue ESX 4.1 o versioni successive. VAAI è un insieme di API che consentono la comunicazione tra host VMware vSphere ESXi e dispositivi di storage. Queste funzionalità consentono di trasferire le operazioni dall'host ESX al sistema storage e aumentare il throughput di rete. L'host ESX attiva automaticamente le funzioni nell'ambiente corretto. È possibile determinare la misura in cui il sistema utilizza le funzioni VAAI controllando le statistiche contenute nei contatori VAAI.

Il punto di partenza più comune per l'automazione dell'implementazione di un ambiente VMware è il provisioning di datastore a blocchi o basati su file. È importante definire i requisiti delle attività effettive prima di sviluppare l'automazione corrispondente.

Per ulteriori informazioni sull'automazione degli ambienti VMware, consultare le seguenti risorse:

* https://netapp.io/configuration-management-and-automation/["Il NetApp Pub"^]. Automazione e gestione della configurazione NetApp.
* https://galaxy.ansible.com/community/vmware["La community Ansible Galaxy per VMware"^]. Una raccolta di risorse Ansible per VMware.
* https://community.broadcom.com/vmware-code/home["Risorse VMware {code}"^]. Risorse necessarie per progettare soluzioni per il data center software-defined, inclusi forum, standard di progettazione, codice di esempio e tool per sviluppatori.

