---
sidebar: sidebar 
permalink: ai/a400-thinksystem-test-plan.html 
keywords: test plan, validation, image recognition training, processes 
summary: 'In questa convalida, abbiamo eseguito il training per il riconoscimento delle immagini come specificato da MLPerf v2.0. In particolare, abbiamo formato il modello ResNet v2.0 con il dataset ImageNet. La metrica principale è il tempo necessario per raggiungere la precisione desiderata. Inoltre, segnaliamo la larghezza di banda del training in immagini al secondo per valutare meglio l"efficienza dello scale-out.' 
---
= Piano di test
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
In questa convalida, abbiamo eseguito il training per il riconoscimento delle immagini come specificato da MLPerf v2.0. In particolare, abbiamo formato il modello ResNet v2.0 con il set di dati ImageNet fino a raggiungere una precisione del 76.1%. La metrica principale è il tempo necessario per raggiungere la precisione desiderata. Inoltre, segnaliamo la larghezza di banda del training in immagini al secondo per valutare meglio l'efficienza dello scale-out.

Il test case principale ha valutato più processi di training indipendenti (uno per nodo) in esecuzione simultanea. Simula il caso d'utilizzo principale, un sistema condiviso utilizzato da più data scientist. Il secondo caso di test ha valutato l'efficienza dello scale-out.
