---
sidebar: sidebar 
permalink: ai/a400-thinksystem-conclusion.html 
keywords: acknowledgements, additional information 
summary: 'Questa soluzione NetApp e Lenovo è un"architettura scale-out flessibile, ideale per l"accesso all"ai di medie imprese. Lo storage NetApp offre le stesse performance o migliori dello storage SSD locale e offre i seguenti vantaggi a data scientist, data engineer e decision maker IT.' 
---
= Conclusione
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
La soluzione NetApp e Lenovo validata qui è un'architettura scale-out flessibile ideale per l'ingresso nell'ai di medie imprese.

Lo storage NetApp offre le stesse performance o migliori dello storage SSD locale e offre i seguenti vantaggi a data scientist, data engineer e decision maker IT:

* Condivisione semplice dei dati tra sistemi ai, analytics e altri sistemi aziendali critici. Questa condivisione dei dati riduce l'overhead dell'infrastruttura, migliora le performance e ottimizza la gestione dei dati in tutta l'azienda.
* Calcolo e storage scalabili in maniera indipendente per ridurre al minimo i costi e migliorare l'utilizzo delle risorse.
* Workflow di sviluppo e implementazione ottimizzati grazie a snapshot e cloni integrati per spazi di lavoro degli utenti istantanei ed efficienti in termini di spazio, controllo delle versioni integrato e implementazione automatizzata.
* Protezione dei dati di livello Enterprise per disaster recovery e continuità del business.




== Ringraziamenti

* Karthikeyan Nagalingam, Technical Marketing Engineer, NetApp
* Jarrett Upton, Admin, ai Lab Systems, Lenovo




== Dove trovare ulteriori informazioni

Per ulteriori informazioni sulle informazioni descritte in questo documento, consultare i seguenti documenti e/o siti Web:

* Pagina del prodotto NetApp All Flash Array
+
https://www.netapp.com/us/products/storage-systems/all-flash-array/aff-a-series.aspx["https://www.netapp.com/us/products/storage-systems/all-flash-array/aff-a-series.aspx"^]

* Pagina NetApp AFF A400
+
https://docs.netapp.com/us-en/ontap-systems/a400/index.html["https://docs.netapp.com/us-en/ontap-systems/a400/index.html"]

* Pagina del prodotto software per la gestione dei dati NetApp ONTAP
+
http://www.netapp.com/us/products/data-management-software/ontap.aspx["http://www.netapp.com/us/products/data-management-software/ontap.aspx"^]

* MLPerf
+
https://mlperf.org/["https://mlperf.org"^]

* Benchmark TensorFlow
+
https://github.com/tensorflow/benchmarks["https://github.com/tensorflow/benchmarks"^]

* NVIDIA SMI (nvidia-smi)
+
https://developer.nvidia.com/nvidia-system-management-interface["https://developer.nvidia.com/nvidia-system-management-interface"]


