---
sidebar: sidebar 
permalink: ai/ai-edge-conclusion.html 
keywords: acknowledgements, additional information 
summary: 'L"automazione basata sull"ai e l"edge computing sono un approccio leader per aiutare le organizzazioni aziendali a ottenere la trasformazione digitale e massimizzare l"efficienza e la sicurezza delle operazioni. Con l"edge computing, i dati vengono elaborati molto più velocemente perché non devono viaggiare da e verso un data center. Di conseguenza, il costo associato all"invio dei dati avanti e indietro ai data center o al cloud è diminuito.' 
---
= Conclusione
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
L'automazione basata sull'ai e l'edge computing sono un approccio leader per aiutare le organizzazioni aziendali a ottenere la trasformazione digitale e massimizzare l'efficienza e la sicurezza delle operazioni. Con l'edge computing, i dati vengono elaborati molto più velocemente perché non devono viaggiare da e verso un data center. Di conseguenza, il costo associato all'invio dei dati avanti e indietro ai data center o al cloud è diminuito. Una latenza inferiore e una velocità maggiore possono essere utili quando le aziende devono prendere decisioni quasi in tempo reale utilizzando modelli di inferenza ai implementati all'edge della rete.

I sistemi storage NetApp offrono performance uguali o migliori rispetto allo storage SSD locale e offrono i seguenti vantaggi a data scientist, data engineer, sviluppatori ai/ML e decision maker aziendali o IT:

* Condivisione semplice dei dati tra sistemi ai, analytics e altri sistemi aziendali critici. Questa condivisione dei dati riduce l'overhead dell'infrastruttura, migliora le performance e ottimizza la gestione dei dati in tutta l'azienda.
* Calcolo e storage scalabili in maniera indipendente per ridurre al minimo i costi e migliorare l'utilizzo delle risorse.
* Workflow di sviluppo e implementazione ottimizzati grazie a copie Snapshot e cloni integrati per spazi di lavoro degli utenti istantanei ed efficienti in termini di spazio, controllo integrato delle versioni e implementazione automatizzata.
* Protezione dei dati di livello Enterprise per disaster recovery e business continuity. La soluzione NetApp e Lenovo presentata in questo documento è un'architettura scalabile e flessibile, ideale per le implementazioni di inferenza ai di livello Enterprise all'edge della rete.




== Ringraziamenti

* J.J. Falkanger, Sr Manager, soluzioni HPC e ai, Lenovo
* Dave Arnette, Technical Marketing Engineer, NetApp
* Joey Parnell, Tech Lead e-Series ai Solutions, NetApp
* Cody Harryman, QA Engineer, NetApp




== Dove trovare ulteriori informazioni

Per ulteriori informazioni sulle informazioni descritte in questo documento, consultare i seguenti documenti e/o siti Web:

* Pagina del prodotto array NetApp AFF A-Series
+
https://www.netapp.com/data-storage/aff-a-series/["https://www.netapp.com/data-storage/aff-a-series/"^]

* Software per la gestione dei dati NetApp ONTAP: Libreria di informazioni ONTAP 9
+
http://mysupport.netapp.com/documentation/productlibrary/index.html?productID=62286["http://mysupport.netapp.com/documentation/productlibrary/index.html?productID=62286"^]

* TR-4727: Introduzione a NetApp EF-Series
+
https://www.netapp.com/pdf.html?item=/media/17179-tr4727pdf.pdf["https://www.netapp.com/pdf.html?item=/media/17179-tr4727pdf.pdf"^]

* Scheda informativa sul software NetApp e-Series SANtricity
+
https://www.netapp.com/pdf.html?item=/media/19775-ds-3171-66862.pdf["https://www.netapp.com/pdf.html?item=/media/19775-ds-3171-66862.pdf"^]

* Storage persistente NetApp per container - NetApp Trident
+
https://netapp.io/persistent-storage-provisioner-for-kubernetes/["https://netapp.io/persistent-storage-provisioner-for-kubernetes/"^]

* MLPerf
+
** https://mlcommons.org/en/["https://mlcommons.org/en/"^]
** http://www.image-net.org/["http://www.image-net.org/"^]
** https://mlcommons.org/en/news/mlperf-inference-v11/["https://mlcommons.org/en/news/mlperf-inference-v11/"^]


* Copia e sincronizzazione di NetApp BlueXP
+
https://docs.netapp.com/us-en/occm/concept_cloud_sync.html#how-cloud-sync-works["https://docs.netapp.com/us-en/occm/concept_cloud_sync.html#how-cloud-sync-works"^]

* Benchmark TensorFlow
+
https://github.com/tensorflow/benchmarks["https://github.com/tensorflow/benchmarks"^]

* Lenovo ThinkSystem SE350 Edge Server
+
https://lenovopress.com/lp1168["https://lenovopress.com/lp1168"^]

* Array di storage flash unificato Lenovo ThinkSystem DM5100F
+
https://lenovopress.com/lp1365-thinksystem-dm5100f-unified-flash-storage-array["https://lenovopress.com/lp1365-thinksystem-dm5100f-unified-flash-storage-array"]


