---
sidebar: sidebar 
permalink: ai/ai-edge-architecture-sizing-options.html 
keywords: architecture, sizing, computer server, shared storage 
summary: 'È possibile regolare l"impostazione utilizzata per la convalida in modo che si adatti ad altri casi di utilizzo.' 
---
= Opzioni di dimensionamento dell'architettura
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
È possibile regolare l'impostazione utilizzata per la convalida in modo che si adatti ad altri casi di utilizzo.



== Server di calcolo

Abbiamo utilizzato una CPU Intel Xeon D-2123IT, che è il livello più basso di CPU supportato in SE350, con quattro core fisici e TDP da 60 W. Anche se il server non supporta la sostituzione delle CPU, può essere ordinato con una CPU più potente. La CPU più alta supportata è Intel Xeon D-2183IT con 16 core, 100 W a 2,20 GHz. Ciò aumenta notevolmente la capacità di calcolo della CPU. Anche se la CPU non era un collo di bottiglia per l'esecuzione dei carichi di lavoro di inferenza, aiuta nell'elaborazione dei dati e in altre attività correlate all'inferenza. Attualmente, NVIDIA T4 è l'unica GPU disponibile per i casi di utilizzo edge; pertanto, attualmente, non è possibile aggiornare o eseguire il downgrade della GPU.



== Storage condiviso

Per il test e la convalida, il sistema NetApp AFF C190, con una capacità di storage massima di 50,5 TB, un throughput di 4,4 Gbps per letture sequenziali e 230 K IOPS per letture casuali di piccole dimensioni, è stato utilizzato per lo scopo di questo documento ed è stato dimostrato adatto per i carichi di lavoro di inferenza edge.

Tuttavia, se è necessaria una maggiore capacità di storage o velocità di rete più elevate, è consigliabile utilizzare i sistemi di storage NetApp AFF A220 o NetApp AFF A250. Inoltre, per la convalida della soluzione è stato utilizzato anche il sistema NetApp EF280, con una capacità massima di 1,5 PB e una larghezza di banda di 10 Gbps. È possibile utilizzare una maggiore capacità di storage con una larghezza di banda superiore https://www.netapp.com/pdf.html?item=/media/19339-DS-4082.pdf&v=2021691654["NetApp EF300"^] .
