---
sidebar: sidebar 
permalink: ai/ai-protopia-inferencing-accuracy-comparison.html 
keywords: faceboxes, alpha value, accuracy, comparison 
summary: 'Per questa convalida, abbiamo eseguito la deduzione per un caso d"utilizzo di rilevamento dell"immagine utilizzando un set di immagini raw. Quindi, abbiamo eseguito la stessa attività di deduzione sullo stesso set di immagini con l"aggiunta dell"offuscamento di Protopia prima dell"inferenza. Abbiamo ripetuto l"attività utilizzando diversi valori DI ALPHA per la componente di offuscamento Protopia.' 
---
= Confronto della precisione delle deduzione
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


link:ai-protopia-test-procedure.html["Precedente: Procedura di test."]

[role="lead"]
Per questa convalida, abbiamo eseguito la deduzione per un caso d'utilizzo di rilevamento dell'immagine utilizzando un set di immagini raw. Quindi, abbiamo eseguito la stessa attività di deduzione sullo stesso set di immagini con l'aggiunta dell'offuscamento di Protopia prima dell'inferenza. Abbiamo ripetuto l'attività utilizzando diversi valori DI ALPHA per la componente di offuscamento Protopia. Nel contesto dell'offuscamento di Protopia, il valore ALFA rappresenta la quantità di offuscamento applicata, con un valore ALFA più alto che rappresenta un livello più elevato di offuscamento. Abbiamo quindi confrontato la precisione delle deduzione in queste diverse esecuzioni.

Le due tabelle seguenti forniscono dettagli sul nostro caso di utilizzo e delineano i risultati.

Protopia collabora direttamente con i clienti per determinare il valore ALFA appropriato per un caso di utilizzo specifico.

|===
| Componente | Dettagli 


| Modello | FaceBoxes (PyTorch) - 


| Dataset | Dataset FDDB 
|===
|===
| Offuscamento di Protopia | ALFA | Precisione 


| No | N/A. | 0.9337148153739079 


| Sì | 0.05 | 0.9028766627325002 


| Sì | 0.1 | 0.9024301009661478 


| Sì | 0.2 | 0.9081836283186224 


| Sì | 0.4 | 0.9073066107482036 


| Sì | 0.6 | 0.8847816568680239 


| Sì | 0.8 | 0.8841195749171925 


| Sì | 0.9 | 0.8455427675252052 


| Sì | 0.95 | 0.8455427675252052 
|===
link:ai-protopia-obfuscation-speed.html["Avanti: Velocità di offuscamento."]
