---
sidebar: sidebar 
permalink: ai/ai-sent-where-to-find-additional-information.html 
keywords:  
summary:  
---
= Dove trovare ulteriori informazioni
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Per ulteriori informazioni sulle informazioni descritte in questo documento, consultare i seguenti documenti e/o siti Web:

* Demo interattive 3D
+
http://www.netapp.com/ai["www.netapp.com/ai"^]

* Connettiti direttamente con uno specialista ai di NetApp
+
https://www.netapp.com/artificial-intelligence/["https://www.netapp.com/artificial-intelligence/"^]

* NVDIA base Command Platform with NetApp Solution Brief
+
https://www.netapp.com/pdf.html?item=/media/32792-DS-4145-NVIDIA-Base-Command-Platform-with-NetApp.pdf["https://www.netapp.com/pdf.html?item=/media/32792-DS-4145-NVIDIA-Base-Command-Platform-with-NetApp.pdf"^]

* Infografica sulle buone ragioni di NetApp per ai 10
+
https://www.netapp.com/us/media/netapp-ai-10-good-reasons.pdf["https://www.netapp.com/pdf.html?item=/media/16147-netapp-ai-10-good-reasonspdf.pdf"^]

* Ai in Healthcare: White paper sull'apprendimento approfondito per identificare le lesioni COVID-19 nelle scansioni TC polmonari
+
https://www.netapp.com/pdf.html?item=/media/31240-WP-7342.pdf["https://www.netapp.com/pdf.html?item=/media/31240-WP-7342.pdf"^]

* Ai in Healthcare: White paper sul monitoraggio dell'utilizzo della maschera facciale in ambito sanitario
+
https://www.netapp.com/pdf.html?item=/media/37490-NA-611-Monitoring-face-mask-usage-in-healthcare-settings.pdf["https://www.netapp.com/pdf.html?item=/media/37490-NA-611-Monitoring-face-mask-usage-in-healthcare-settings.pdf"^]

* Ai in Healthcare: Report tecnico di imaging diagnostico
+
https://www.netapp.com/pdf.html?item=/media/7395-tr4811.pdf["https://www.netapp.com/pdf.html?item=/media/7395-tr4811.pdf"^]

* Ai per il retail: Ai di NetApp Conversational con NVIDIA RIVA
+
link:cainvidia_executive_summary.html["In sintesi"]

* Analisi della soluzione ai di NetApp ONTAP
+
https://www.netapp.com/pdf.html?item=/media/6736-sb-3939.pdf["https://www.netapp.com/pdf.html?item=/media/6736-sb-3939.pdf"^]

* Descrizione della soluzione NetApp DataOps Toolkit
+
https://www.netapp.com/pdf.html?item=/media/21480-SB-4111-1220-NA-Data-Science-Toolkit.pdf["https://www.netapp.com/pdf.html?item=/media/21480-SB-4111-1220-NA-Data-Science-Toolkit.pdf"^]

* Analisi della soluzione NetApp ai Control Plane
+
https://www.netapp.com/pdf.html?item=/media/6737-sb-4055.pdf["https://www.netapp.com/pdf.html?item=/media/6737-sb-4055.pdf"^]

* EBook trasformare il settore con Data Drive ai
+
https://www.netapp.com/pdf.html?item=/media/16968-na-337pdf.pdf["https://www.netapp.com/us/media/na-337.pdf"^]

* Analisi della soluzione ai NetApp EF-Series
+
https://www.netapp.com/pdf.html?item=/media/26708-SB-4136-NetApp-AI-E-Series.pdf["https://www.netapp.com/pdf.html?item=/media/26708-SB-4136-NetApp-AI-E-Series.pdf"^]

* Analisi della soluzione NetApp ai e Lenovo ThinkSystem for ai Inferencing
+
https://www.netapp.com/pdf.html?item=/media/25316-SB-4129.pdf["https://www.netapp.com/pdf.html?item=/media/25316-SB-4129.pdf"^]

* Analisi della soluzione NetApp ai e Lenovo ThinkSystem per ai e ML Enterprise
+
https://www.netapp.com/pdf.html?item=/media/25317-SB-4128.pdf["https://www.netapp.com/pdf.html?item=/media/25317-SB-4128.pdf"^]

* NetApp e NVIDIA – ridefinire le possibilità con i video ai
+
https://www.youtube.com/watch?v=38xw65SteUc["https://www.youtube.com/watch?v=38xw65SteUc"^]


