---
sidebar: sidebar 
permalink: ai/aicp_kubernetes_deployment.html 
keywords: NVIDIA, GPU, Kubernetes, Control Plane, Trident 
summary: Questa pagina descrive le attività da completare per implementare un cluster Kubernetes in cui implementare la soluzione NetApp ai Control Plane. Se si dispone già di un cluster Kubernetes, è possibile saltare questa sezione se si utilizza una versione di Kubernetes supportata da Kubeflow e NetApp Trident. 
---
= Implementazione di Kubernetes
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
Questa sezione descrive le attività da completare per implementare un cluster Kubernetes in cui implementare la soluzione NetApp ai Control Plane. Se si dispone già di un cluster Kubernetes, è possibile saltare questa sezione se si utilizza una versione di Kubernetes supportata da Kubeflow e NetApp Trident. Per un elenco delle versioni di Kubernetes supportate da Kubeflow, vedere la https://www.kubeflow.org/docs/started/getting-started/["Documentazione ufficiale del Kubeflow"^]. Per un elenco delle versioni di Kubernetes supportate da Trident, vedere https://netapp-trident.readthedocs.io/["Documentazione di Trident"^].

Per le implementazioni on-premise di Kubernetes che incorporano nodi bare-metal con GPU NVIDIA, NetApp consiglia di utilizzare il tool di implementazione DeepOps Kubernetes di NVIDIA. Questa sezione descrive l'implementazione di un cluster Kubernetes utilizzando DeepOps.



== Prerequisiti

Prima di eseguire l'esercizio di implementazione descritto in questa sezione, si presuppone che siano già state eseguite le seguenti attività:

. Sono già stati configurati nodi Kubernetes bare-metal (ad esempio, un sistema NVIDIA DGX che fa parte di un pod ai ONTAP) in base alle istruzioni di configurazione standard.
. È stato installato un sistema operativo supportato su tutti i nodi master e worker di Kubernetes e su un host di distribuzione jump. Per un elenco dei sistemi operativi supportati da DeepOps, vedere https://github.com/NVIDIA/deepops["Sito DeepOps GitHub"^].




== Utilizzare NVIDIA DeepOps per installare e configurare Kubernetes

Per implementare e configurare il cluster Kubernetes con NVIDIA DeepOps, eseguire le seguenti operazioni da un host di distribuzione jump:

. Scaricare NVIDIA DeepOps seguendo le istruzioni sul https://github.com/NVIDIA/deepops/tree/master/docs["Pagina introduttiva"^] Sul sito NVIDIA DeepOps GitHub.
. Implementare Kubernetes nel cluster seguendo le istruzioni sul https://github.com/NVIDIA/deepops/tree/master/docs/k8s-cluster["Pagina della Guida all'implementazione di Kubernetes"^] Sul sito NVIDIA DeepOps GitHub.

