---
sidebar: sidebar 
permalink: ai/aicp_conclusion.html 
keywords: NetApp AI Machine Deep Learning 
summary:  
---
= Conclusione
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
Aziende e organizzazioni di tutte le dimensioni e in tutti i settori stanno passando all'intelligenza artificiale (ai), all'apprendimento automatico (ML) e al deep learning (DL) per risolvere problemi reali, offrire prodotti e servizi innovativi e ottenere un vantaggio in un mercato sempre più competitivo. Man mano che le organizzazioni aumentano l'utilizzo di ai, ML e DL, devono affrontare molte sfide, tra cui la scalabilità dei workload e la disponibilità dei dati. Queste sfide possono essere affrontate utilizzando la soluzione NetApp ai Control Plane.

Questa soluzione consente di clonare rapidamente uno spazio dei nomi dei dati. Inoltre, consente di definire e implementare flussi di lavoro di training ai, ML e DL che incorporano la creazione quasi istantanea di dati e linee di base dei modelli per la tracciabilità e il controllo delle versioni. Con questa soluzione, è possibile tracciare ogni singolo modello di training fino ai set di dati esatti con cui il modello è stato addestrato e/o validato. Infine, questa soluzione consente di eseguire rapidamente il provisioning degli spazi di lavoro dei notebook Jupyter con accesso a set di dati di grandi dimensioni.

Poiché questa soluzione è rivolta a data scientist e data engineer, è necessaria una competenza minima di NetApp o NetApp ONTAP. Con questa soluzione, le funzioni di gestione dei dati possono essere eseguite utilizzando interfacce e strumenti semplici e familiari. Inoltre, questa soluzione utilizza componenti completamente open-source e liberi. Pertanto, se disponete già di storage NetApp nel vostro ambiente, potete implementare questa soluzione oggi stesso. Se si desidera provare questa soluzione ma non si dispone già di storage NetApp, visitare il sito http://cloud.netapp.com/["cloud.netapp.com"^]E potrai essere operativo con una soluzione di storage NetApp basata sul cloud in pochissimo tempo.
