---
sidebar: sidebar 
permalink: ai/aicp_example_notebooks_and_pipelines.html 
keywords: Jupyter Notebook, Kubeflow Pipeline, NetApp DataOps Toolkit 
summary: MLOps open source con NetApp - utilizza il toolkit NetApp DataOps con Kubeflow 
---
= USA il toolkit DataOps di NetApp con Kubeflow
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
Il https://github.com/NetApp/netapp-dataops-toolkit/tree/main/netapp_dataops_k8s["NetApp Data Science Toolkit per Kubernetes"] Utilizzabile in combinazione con Kubeflow. L'utilizzo del NetApp Data Science Toolkit con Kubeflow offre i seguenti vantaggi:

* I data scientist possono eseguire operazioni avanzate di gestione dei dati NetApp, come la creazione di snapshot e cloni, direttamente dall'interno di un notebook Jupyter.
* Le operazioni avanzate di gestione dei dati di NetApp, come la creazione di snapshot e cloni, possono essere incorporate nei workflow automatizzati utilizzando il framework Kubeflow Pipelines.


Fare riferimento a. https://github.com/NetApp/netapp-dataops-toolkit/tree/main/netapp_dataops_k8s/Examples/Kubeflow["Esempi di Kubeflow"] Sezione all'interno del repository GitHub del NetApp Data Science Toolkit per informazioni dettagliate sull'utilizzo del toolkit con Kubeflow.
