---
sidebar: sidebar 
permalink: ai/aicp_hardware_and_software_requirements.html 
keywords: Hardware, Software, Requirements, Trident, DeepOps, ONTAP, Ubuntu 
summary: MLOps open source con NetApp - architettura 
---
= Architettura
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
Questa soluzione non dipende da hardware specifico. La soluzione è compatibile con qualsiasi appliance di storage fisico, istanza software-defined o servizio cloud NetApp, supportato da Trident. Esempi: Un sistema storage NetApp AFF, Amazon FSX per NetApp ONTAP, Azure NetApp Files o un'istanza di NetApp Cloud Volumes ONTAP. Inoltre, la soluzione può essere implementata su qualsiasi cluster Kubernetes purché la versione di Kubernetes utilizzata sia supportata da Kubeflow e NetApp Astra Trident. Per un elenco delle versioni di Kubernetes supportate da Kubeflow, vedere la https://www.kubeflow.org/docs/started/getting-started/["Documentazione ufficiale del Kubeflow"^]. Per un elenco delle versioni di Kubernetes supportate da Trident, vedere https://docs.netapp.com/us-en/trident/index.html["Documentazione di Trident"^]. Per informazioni dettagliate sull'ambiente utilizzato per la convalida della soluzione, consultare le tabelle seguenti.

|===
| Componente software | Versione 


| Flusso d'aria Apache | 2.0.1 


| Helm Chart di Apache Airflow | 8.0.8 


| Kubeflow | 1,7, implementato tramite link:https://www.deploykf.org["DeployKF"] 0.1.1 


| Kubernetes | 1,26 


| NetApp Astra Trident | 23,07 
|===


== Supporto

NetApp non offre supporto Enterprise per Apache Airflow, Kubeflow o Kubernetes. Se sei interessato a una piattaforma MLOps completamente supportata, link:https://www.netapp.com/us/contact-us/index.aspx?for_cr=us["Contatta NetApp"] Informazioni sulle soluzioni MLOps completamente supportate offerte da NetApp insieme ai partner.
