---
sidebar: sidebar 
permalink: ai/aipod_nv_conclusion_add_info.html 
keywords: NetApp AI, AI, Artificial Intelligence, ML, Machine Learning, NVIDIA, NVIDIA AI Enterprise, NVIDIA BasePOD, NVIDIA DGX 
summary: NetApp FlexPod con sistemi NVIDIA DGX - dove trovare informazioni aggiuntive 
---
= NetApp FlexPod con sistemi NVIDIA DGX - conclusioni e informazioni aggiuntive
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


link:aipod_nv_validation_sizing.html["Precedente: FlexPod di NetApp con sistemi NVIDIA DGX - convalida della soluzione e linee guida al dimensionamento"]



== Conclusione

L'architettura DGX BasePOD è una piattaforma di deep learning di nuova generazione che richiede capacità di storage e di gestione dei dati altrettanto avanzate. Combinando DGX BasePOD con i sistemi NetApp AFF, l'architettura NetApp AIPod può essere implementata su quasi ogni scala, da una singola GPU in un server OEM abbinato a un sistema storage AFF A250 fino a 48 sistemi DGX H100 su un cluster AFF A900 a 24 nodi. Combinato con l'integrazione superiore del cloud e le capacità software-defined di NetApp ONTAP, AFF offre una gamma completa di pipeline di dati che spazia dall'edge al core fino al cloud per progetti DL di successo.



== Ulteriori informazioni

Per ulteriori informazioni sulle informazioni descritte in questo documento, fare riferimento ai seguenti documenti e/o siti Web:

* Software per la gestione dei dati NetApp ONTAP: Libreria di informazioni ONTAP
+
https://docs.netapp.com/us-en/ontap-family/["https://docs.netapp.com/us-en/ontap-family/"^]

* Sistemi storage NetApp AFF A900 -
+
https://www.netapp.com/data-storage/aff-a-series/aff-a900/["https://www.netapp.com/data-storage/aff-a-series/aff-a900/"]

* Informazioni RDMA NetApp ONTAP-
+
link:https://docs.netapp.com/us-en/ontap/nfs-rdma/index.html["https://docs.netapp.com/us-en/ontap/nfs-rdma/index.html"]

* NetApp DataOps Toolkit
+
https://github.com/NetApp/netapp-dataops-toolkit["https://github.com/NetApp/netapp-dataops-toolkit"^]

* NetApp Astra Trident
+
https://docs.netapp.com/us-en/netapp-solutions/containers/rh-os-n_overview_trident.html["https://docs.netapp.com/us-en/netapp-solutions/containers/rh-os-n_overview_trident.html"^]

* Architetture validate ONTAP ai- NetApp con sistemi NVIDIA DGX A100
+
https://docs.netapp.com/us-en/netapp-solutions/ai/ontap-ai-overview.html["https://docs.netapp.com/us-en/netapp-solutions/ai/ontap-ai-overview.html"^]

* NVIDIA BasePOD
+
https://www.nvidia.com/en-us/data-center/dgx-basepod/["https://www.nvidia.com/en-us/data-center/dgx-basepod/"^]

* SISTEMI NVIDIA DGX A100
+
https://www.nvidia.com/en-us/data-center/dgx-a100/["https://www.nvidia.com/en-us/data-center/dgx-a100/"^]

* Rete NVIDIA
+
https://www.nvidia.com/en-us/networking/["https://www.nvidia.com/en-us/networking/"^]

* NVIDIA ai Enterprise
+
https://www.nvidia.com/en-us/data-center/products/ai-enterprise/["https://www.nvidia.com/en-us/data-center/products/ai-enterprise/"^]





== Ringraziamenti

Questo documento è il lavoro dei team di progettazione delle soluzioni NetApp e ONTAP: David Arnette, Olga Kornievskaia, Dustin Fischer, Srikanth Kaligotla, Mohit Kumar e Rajeev Badrinath. Gli autori ringraziano inoltre NVIDIA e il team di progettazione BasePOD per il loro continuo supporto.
