---
sidebar: sidebar 
permalink: ai/aipod_nv_conclusion.html 
keywords: NetApp AI, AI, Artificial Intelligence, ML, Machine Learning, NVIDIA, NVIDIA AI Enterprise, NVIDIA BasePOD, NVIDIA DGX 
summary: Pod NetApp ai con sistemi NVIDIA DGX - conclusioni 
---
= Pod NetApp ai con sistemi NVIDIA DGX - conclusioni
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


link:aipod_nv_storage.html["Precedente: Pod NetApp ai con sistemi NVIDIA DGX - Guida al dimensionamento e alla progettazione del sistema storage."]



== Conclusione

L'architettura DGX BasePOD è una piattaforma di deep learning di nuova generazione che richiede capacità di storage e di gestione dei dati altrettanto avanzate. Combinando DGX BasePOD con i sistemi NetApp AFF, questa architettura può essere implementata su quasi ogni scala, da un singolo DGX A100 accoppiato con un sistema storage AFF A250 fino a 48 sistemi DGX A100 su un cluster AFF A800 a 24 nodi. Combinato con l'integrazione superiore del cloud e le capacità software-defined di NetApp ONTAP, AFF offre una gamma completa di pipeline di dati che spazia dall'edge al core fino al cloud per progetti DL di successo.

link:aipod_nv_additional_information.html["Pagina successiva: Pod NetApp ai con sistemi NVIDIA DGX - informazioni aggiuntive."]
