---
sidebar: sidebar 
permalink: ai/aipod_nv_conclusion_add_info.html 
keywords: NetApp AI, AI, Artificial Intelligence, ML, Machine Learning, NVIDIA, NVIDIA AI Enterprise, NVIDIA BasePOD, NVIDIA DGX 
summary: NetApp FlexPod con sistemi NVIDIA DGX - dove trovare informazioni aggiuntive 
---
= NetApp FlexPod con sistemi NVIDIA DGX - conclusioni e informazioni aggiuntive
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
Questa sezione include riferimenti per informazioni aggiuntive per NetApp APod con sistemi NVIDIA DGX.



== Conclusione

L'architettura DGX BasePOD è una piattaforma di deep learning di nuova generazione che richiede capacità di storage e di gestione dei dati altrettanto avanzate. Combinando DGX BasePOD con i sistemi NetApp AFF, l'architettura dei sistemi NetApp AIPod con DGX può essere implementata su quasi ogni scala fino a 48 sistemi DGX H100 su un cluster AFF A900 a 24 nodi. Combinato con l'integrazione superiore del cloud e le capacità software-defined di NetApp ONTAP, AFF offre una gamma completa di pipeline di dati che spazia dall'edge al core fino al cloud per progetti DL di successo.



== Ulteriori informazioni

Per ulteriori informazioni sulle informazioni descritte in questo documento, fare riferimento ai seguenti documenti e/o siti Web:

* Software per la gestione dei dati NetApp ONTAP: Libreria di informazioni ONTAP
+
https://docs.netapp.com/us-en/ontap-family/["https://docs.netapp.com/us-en/ontap-family/"^]

* Sistemi storage NetApp AFF A900 -
+
https://www.netapp.com/data-storage/aff-a-series/aff-a900/["https://www.netapp.com/data-storage/aff-a-series/aff-a900/"]

* Informazioni RDMA NetApp ONTAP-
+
link:https://docs.netapp.com/us-en/ontap/nfs-rdma/index.html["https://docs.netapp.com/us-en/ontap/nfs-rdma/index.html"]

* NetApp DataOps Toolkit
+
https://github.com/NetApp/netapp-dataops-toolkit["https://github.com/NetApp/netapp-dataops-toolkit"^]

* NetApp Astra Trident
+
link:../containers/rh-os-n_overview_trident.html["Panoramica"]

* Blog sullo storage GPUDirect di NetApp -
+
https://www.netapp.com/blog/ontap-reaches-171-gpudirect-storage/["https://www.netapp.com/blog/ontap-reaches-171-gpudirect-storage/"]

* NVIDIA DGX BasePOD
+
https://www.nvidia.com/en-us/data-center/dgx-basepod/["https://www.nvidia.com/en-us/data-center/dgx-basepod/"^]

* SISTEMI NVIDIA DGX H100
+
https://www.nvidia.com/en-us/data-center/dgx-h100/["https://www.nvidia.com/en-us/data-center/dgx-h100/"^]

* Rete NVIDIA
+
https://www.nvidia.com/en-us/networking/["https://www.nvidia.com/en-us/networking/"^]

* NVIDIA Magnum io GPUDirect Storage
+
https://docs.nvidia.com/gpudirect-storage["https://docs.nvidia.com/gpudirect-storage"]

* Comando base NVIDIA
+
https://www.nvidia.com/en-us/data-center/base-command/["https://www.nvidia.com/en-us/data-center/base-command/"]

* NVIDIA base Command Manager
+
https://www.nvidia.com/en-us/data-center/base-command/manager["https://www.nvidia.com/en-us/data-center/base-command/manager"]

* NVIDIA ai Enterprise
+
https://www.nvidia.com/en-us/data-center/products/ai-enterprise/["https://www.nvidia.com/en-us/data-center/products/ai-enterprise/"^]





== Ringraziamenti

Questo documento è il lavoro dei team di progettazione delle soluzioni NetApp e ONTAP: David Arnette, Olga Kornievskaia, Dustin Fischer, Srikanth Kaligotla, Mohit Kumar e Rajeev Badrinath. Gli autori vogliono anche ringraziare NVIDIA e il team tecnico NVIDIA DGX BasePOD per il loro costante supporto.
