---
sidebar: sidebar 
permalink: ai/aks-anf_dataset_and_model_versioning_using_netapp_dataops_toolkit.html 
keywords: toolkit, dataops, kubernetes, abstraction, python, jupyterlab 
summary: 'Il NetApp DataOps Toolkit per Kubernetes astratta le risorse di storage e i carichi di lavoro Kubernetes fino al livello di spazio di lavoro per la scienza dei dati. Queste funzionalità sono integrate in un"interfaccia semplice e facile da usare, progettata per data scientist e data engineer.' 
---
= Versione di set di dati e modelli con NetApp DataOps Toolkit
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


link:aks-anf_monitor_dask_and_rapids_with_prometheus_and_grafana.html["Precedente: Monitoraggio di Dask e RAPIDE con Prometheus e Grafana."]

[role="lead"]
Il NetApp DataOps Toolkit per Kubernetes astratta le risorse di storage e i carichi di lavoro Kubernetes fino al livello di spazio di lavoro per la scienza dei dati. Queste funzionalità sono integrate in un'interfaccia semplice e facile da usare, progettata per data scientist e data engineer. Utilizzando la forma familiare di un programma Python, il Toolkit consente a data scientist e ingegneri di eseguire il provisioning e la distruzione delle aree di lavoro di JupyterLab in pochi secondi. Queste aree di lavoro possono contenere terabyte, o persino petabyte, di capacità di storage, consentendo agli scienziati dei dati di memorizzare tutti i set di dati di training direttamente nelle aree di lavoro dei progetti. Sono finiti i tempi della gestione separata degli spazi di lavoro e dei volumi di dati.

Per ulteriori informazioni, visitare il Toolkit https://github.com/NetApp/netapp-data-science-toolkit["Repository di GitHub"^].

link:aks-anf_conclusion.html["Prossimo: Conclusione."]
