---
sidebar: sidebar 
permalink: ai/dataops-toolkit.html 
keywords:  
summary:  
---
= NetApp DataOps Toolkit
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Il NetApp DataOps Toolkit è uno strumento basato su Python che semplifica la gestione degli spazi di lavoro di sviluppo/formazione e dei server di inferenza supportati dallo storage NetApp scale-out dalle performance elevate. Le funzionalità principali includono:

* Provisioning rapido di nuove aree di lavoro JupyterLab ad alta capacità supportate da storage NetApp scale-out dalle performance elevate.
* Provisioning rapido delle nuove istanze di NVIDIA Triton Inference Server supportate dallo storage NetApp di livello Enterprise.
* È possibile clonare quasi istantaneamente spazi di lavoro JupyterLab ad alta capacità per consentire sperimentazione o iterazione rapida.
* Salva quasi istantaneamente le istantanee degli spazi di lavoro JupyterLab ad alta capacità per il backup e/o la tracciabilità/baseline.
* Provisioning quasi istantaneo, cloning e snapshot di volumi di dati a elevata capacità e performance elevate.


link:https://github.com/NetApp/netapp-dataops-toolkit["NetApp DataOps Toolkit"^]
