---
sidebar: sidebar 
permalink: ai/ddlnexus_initial_setup.html 
keywords: NetApp AI, AI, Artificial Intelligence, ML, Machine Learning, NVIDIA, Hybrid, Hybrid Cloud, Hybrid Multicloud, Cloud, AWS, Amazon, Amazon Web Services, FSx for NetApp ONTAP, FSx, NetApp ONTAP, FlexCache, SnapMirror, BlueXP 
summary: MLOps multicloud ibrido con Domino Data Lab e NetApp - Configurazione iniziale 
---
= Setup iniziale
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


link:ddlnexus_architecture.html["Precedente: Architettura."]

[role="lead"]
Questa sezione descrive le attività di configurazione iniziali che devono essere eseguite per utilizzare Domino Nexus con i servizi dati NetApp in un ambiente ibrido che incorpora un data center on-premise e AWS.



== Prerequisiti

Prima di eseguire le operazioni descritte in questa sezione, si presuppone che siano già state eseguite le seguenti operazioni:

* Hai già implementato e configurato la tua piattaforma di storage NetApp ONTAP on-premise. Per ulteriori informazioni, consultare la link:https://www.netapp.com/support-and-training/documentation/["Documentazione sui prodotti NetApp"].
* Hai già eseguito il provisioning di un'istanza di Amazon FSX per NetApp ONTAP in AWS. Per ulteriori informazioni, consultare la link:https://aws.amazon.com/fsx/netapp-ontap/["Pagina del prodotto Amazon FSX per NetApp ONTAP"].
* Hai già effettuato il provisioning di un cluster Kubernetes nel tuo data center on-premise. Per ulteriori informazioni, consultare la link:https://docs.dominodatalab.com/en/latest/admin_guide/b35e66/admin-guide/["Guida amministratore di Domino"].
* Hai già effettuato il provisioning di un cluster Amazon EKS in AWS. Per ulteriori informazioni, consultare la link:https://docs.dominodatalab.com/en/latest/admin_guide/b35e66/admin-guide/["Guida amministratore di Domino"].
* Hai installato NetApp Astra Trident nel tuo cluster Kubernetes on-premise. Inoltre, hai configurato questa istanza Trident per utilizzare la tua piattaforma di storage NetApp ONTAP on-premise durante il provisioning e la gestione delle risorse di storage. Per ulteriori informazioni, consultare la link:https://docs.netapp.com/us-en/trident/index.html["Documentazione di NetApp Astra Trident"].
* Hai installato NetApp Astra Trident nel tuo cluster Amazon EKS. Inoltre, questa istanza Trident è stata configurata per utilizzare la tua istanza di Amazon FSX per NetApp ONTAP durante il provisioning e la gestione delle risorse di storage. Per ulteriori informazioni, consultare la link:https://docs.netapp.com/us-en/trident/index.html["Documentazione di NetApp Astra Trident"].
* Devi disporre di connettività di rete bidirezionale tra il data center on-premise e il cloud privato virtuale (VPC) in AWS. Per ulteriori informazioni sulle varie opzioni di implementazione, fare riferimento alla link:https://docs.aws.amazon.com/vpc/latest/userguide/vpn-connections.html["Documentazione di Amazon Virtual Private Network (VPN)"].




== Installare Domino Enterprise ai Platform in AWS

Per installare Domino Enterprise MLOps Platform in AWS, seguire le istruzioni riportate in link:https://docs.dominodatalab.com/en/latest/admin_guide/c1eec3/deploy-domino/["Guida amministratore di Domino"]. Devi implementare Domino nello stesso cluster Amazon EKS di cui hai precedentemente eseguito il provisioning. Inoltre, NetApp Astra Trident deve essere già installato e configurato in questo cluster EKS, ed è necessario specificare una classe di storage gestita da Trident come classe di storage condiviso nel file di configurazione dell'installazione di domino.yml.


NOTE: Fare riferimento a. link:https://docs.dominodatalab.com/en/latest/admin_guide/7f4331/install-configuration-reference/#storage-classes["Guida di riferimento per l'installazione di Domino"] per informazioni dettagliate su come specificare una classe di archiviazione condivisa nel file di configurazione di installazione domino.yml.


NOTE: link:https://www.netapp.com/media/79922-tr-4952.pdf["Report tecnico TR-4952"] Guida l'implementazione di Domino in AWS con Amazon FSX per NetApp ONTAP e può essere un utile riferimento per la risoluzione di eventuali problemi che si verificano.



== Attivare Domino Nexus

Successivamente, è necessario attivare Domino Nexus. Fare riferimento a. link:https://docs.dominodatalab.com/en/latest/admin_guide/c65074/nexus-hybrid-architecture/["Guida amministratore di Domino"] per ulteriori informazioni.



== Implementare un piano dati Domino nel data center locale

Successivamente, è necessario implementare un piano dati Domino nel data center locale. Devi implementare questo piano dati nel cluster Kubernetes on-premise che hai precedentemente fornito il provisioning. Inoltre, NetApp Astra Trident deve essere già installato e configurato in questo cluster Kubernetes. Fare riferimento a. link:https://docs.dominodatalab.com/en/latest/admin_guide/5781ea/data-planes/["Guida amministratore di Domino"] per ulteriori informazioni.

link:ddlnexus_expose_netapp_vols.html["Successivo: Esporre i volumi NetApp esistenti a Domino."]
