---
sidebar: sidebar 
permalink: ai/hcaios_ontap_ai_deployment.html 
keywords: ONTAP AI, Deployment, networking, compute, storage 
summary:  
---
= Implementazione di ONTAP ai
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
L'implementazione di ONTAP ai richiede l'installazione e la configurazione dell'hardware di rete, calcolo e storage. Le istruzioni specifiche per l'implementazione dell'infrastruttura ai di ONTAP esulano dall'ambito di questo documento. Per informazioni dettagliate sulla distribuzione, vedere https://www.netapp.com/pdf.html?item=/media/7674-nva-1121-deploypdf.pdf["NVA-1121-DEPLOY: NetApp ONTAP ai, basato su NVIDIA"^].

Per la convalida di questa soluzione, è stato creato un singolo volume e montato sul sistema DGX-1. Tale punto di montaggio è stato quindi montato sui container per rendere i dati accessibili per la formazione. Per implementazioni su larga scala, NetApp Trident automatizza la creazione e il montaggio dei volumi per eliminare i costi amministrativi e consentire la gestione delle risorse da parte dell'utente finale.
