---
sidebar: sidebar 
permalink: ai/hcaios_abstract.html 
keywords: NetApp Abstract ML AI 
summary:  
---
= Astratto
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
La crescita esplosiva dei dati e la crescita esponenziale dell'apprendimento automatico (ML) e dell'intelligenza artificiale (ai) sono convergenti per creare una nuova economia con sfide di sviluppo e implementazione uniche. In genere, enormi quantità di dati vengono memorizzate in un data Lake a basso costo, dove le risorse di calcolo ai dalle performance elevate, come le GPU, non possono accedervi in modo efficiente. In questo report, presentiamo una nuova soluzione in cui i professionisti delle scienze dei dati implementano un data hub e, con un click, creano una cache di set di dati in prossimità delle risorse di calcolo, ovunque si trovino. Di conseguenza, i professionisti dell'ai possono eseguire più facilmente training su modelli dalle performance elevate grazie alla collaborazione avanzata resa possibile da un nuovo hub di versione del set di dati.
