---
sidebar: sidebar 
permalink: ai/hcaios_where_to_find_additional_information.html 
keywords: NetApp Additional Information 
summary:  
---
= Dove trovare ulteriori informazioni
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Per ulteriori informazioni sulle informazioni descritte in questo documento, consultare le seguenti risorse:

* Cnvrg.io ( https://cnvrg.io["https://cnvrg.io"^]):
+
** CORE Cnvrg (piattaforma ML gratuita)
+
https://cnvrg.io/platform/core[]

** Documenti Cnvrg
+
https://app.cnvrg.io/docs["https://app.cnvrg.io/docs"^]



* Server NVIDIA DGX-1:
+
** Server NVIDIA DGX-1
+
https://www.nvidia.com/en-us/data-center/dgx-1/[]

** NVIDIA Tesla V100 Tensor Core GPU
+
https://www.nvidia.com/en-us/data-center/tesla-v100/[]

** NVIDIA GPU CLOUD (NGC)
+
https://www.nvidia.com/en-us/gpu-cloud/[]



* Sistemi NetApp AFF:
+
** Scheda informativa su AFF
+
https://www.netapp.com/us/media/d-3582.pdf[]

** NetApp FlashAdvantage per AFF
+
https://www.netapp.com/us/media/ds-3733.pdf[]

** Documentazione di ONTAP 9.x.
+
http://mysupport.netapp.com/documentation/productlibrary/index.html?productID=62286[]

** Report tecnico di NetApp FlexGroup
+
https://www.netapp.com/us/media/tr-4557.pdf[]



* Storage persistente NetApp per container:
+
** Trident di NetApp
+
https://netapp.io/persistent-storage-provisioner-for-kubernetes/[]



* Matrice di interoperabilità NetApp:
+
** Tool di matrice di interoperabilità NetApp
+
https://mysupport.netapp.com/matrix/#welcome[]



* Networking ai ONTAP:
+
** Switch Cisco Nexus 3232C
+
https://www.cisco.com/c/en/us/products/switches/nexus-3232c-switch/index.html[]

** Switch Mellanox Spectrum serie 2000
+
http://www.mellanox.com/page/products_dyn?product_family=251&mtag=sn2000[]



* Framework E tool ML:
+
** DALI
+
https://github.com/NVIDIA/DALI[]

** TensorFlow: Un framework di apprendimento automatico open-source per tutti
+
https://www.tensorflow.org/[]

** Horovod: Framework di deep learning distribuito open-source di Uber per TensorFlow
+
https://eng.uber.com/horovod/[]

** Abilitazione delle GPU nell'ecosistema di runtime container
+
https://devblogs.nvidia.com/gpu-containers-runtime/[]

** Docker
+
https://docs.docker.com[]

** Kubernetes
+
https://kubernetes.io/docs/home/[]

** NVIDIA DeepOps
+
https://github.com/NVIDIA/deepops[]

** Kubeflow
+
http://www.kubeflow.org/[]

** Jupyter notebook Server
+
http://www.jupyter.org/[]



* Set di dati e benchmark:
+
** Set di dati per radiografia toracica NIH
+
https://nihcc.app.box.com/v/ChestXray-NIHCC[]

** Xiaosong Wang, Yifan Peng, le Lu, Zhiyong Lu, Mohammadhadi Bagheri, Ronald Summers, ChestX-ray8: Database dei raggi X del torace su scala ospedaliera e benchmark sulla classificazione e localizzazione con supervisione debole delle malattie toraciche comuni, IEEE CVPR, pp 3462-3471, 2017TR-4841-0620



