---
sidebar: sidebar 
permalink: ai/hciai_edge_use_cases.html 
keywords:  
summary:  
---
= Casi di utilizzo
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
Anche se tutte le applicazioni di oggi non sono basate sull'intelligenza artificiale, sono in evoluzione funzionalità che consentono loro di accedere agli enormi benefici dell'intelligenza artificiale. Per supportare l'adozione dell'ai, le applicazioni hanno bisogno di un'infrastruttura che fornisca loro le risorse necessarie per funzionare a un livello ottimale e supportare la loro continua evoluzione.

Per le applicazioni basate sull'ai, le ubicazioni edge fungono da principale fonte di dati. I dati disponibili possono essere utilizzati per il training se raccolti da più postazioni edge in un determinato periodo di tempo per formare un set di dati di training. Il modello addestrato può quindi essere implementato di nuovo nelle posizioni periferiche in cui sono stati raccolti i dati, consentendo un'inferenza più rapida senza la necessità di trasferire ripetutamente i dati di produzione su una piattaforma di inferenza dedicata.

La soluzione di inferenza ai di NetApp HCI, basata su nodi di calcolo NetApp H615c con GPU NVIDIA T4 e sistemi storage connessi al cloud, è stata sviluppata e verificata da NetApp e NVIDIA. NetApp HCI semplifica l'implementazione delle soluzioni di inferenza ai nei data center edge affrontando aree di ambiguità, eliminando le complessità di progettazione e finendo con le congetture. Questa soluzione offre alle organizzazioni IT un'architettura prescrittiva che:

* Consente l'inferenza ai nei data center edge
* Ottimizza il consumo delle risorse GPU
* Fornisce una piattaforma di deduzione basata su Kubernetes per flessibilità e scalabilità
* Elimina le complessità di progettazione


I data center edge gestiscono ed elaborano i dati in posizioni molto vicine al punto di generazione. Questa vicinanza aumenta l'efficienza e riduce la latenza nella gestione dei dati. Molti mercati verticali hanno realizzato i vantaggi di un data center edge e stanno adottando in maniera massicciata questo approccio distribuito all'elaborazione dei dati.

La seguente tabella elenca i mercati verticali e le applicazioni edge.

|===
| Verticale | Applicazioni 


| Medico | La diagnostica assistita dal computer assiste il personale medico nella diagnosi precoce delle malattie 


| Petrolio e gas | Ispezione autonoma di impianti di produzione remoti, video e analisi delle immagini 


| Aviazione | Assistenza per il controllo del traffico aereo e analisi dei feed video in tempo reale 


| Contenuti multimediali e di intrattenimento | Filtraggio dei contenuti audio/video per offrire contenuti adatti alle famiglie 


| Analisi del business | Riconoscimento del marchio per analizzare l'aspetto del marchio negli eventi televisivi in streaming live 


| E-Commerce | Bundle intelligente di offerte di fornitori per trovare combinazioni di merchant e warehouse ideali 


| Vendita al dettaglio | Checkout automatizzato per riconoscere gli articoli inseriti nel carrello da un cliente e facilitare il pagamento digitale 


| Città intelligente | Migliorare il flusso del traffico, ottimizzare il parcheggio e migliorare la sicurezza dei pedoni e dei ciclisti 


| Produzione | Controllo di qualità, monitoraggio della linea di assemblaggio e identificazione dei difetti 


| Servizio clienti | Automazione del servizio clienti per analizzare e valutare le richieste (telefono, e-mail e social media) 


| Agricoltura | Pianificazione intelligente delle attività e delle operazioni agricole per ottimizzare l'applicazione di fertilizzanti e erbicida 
|===


== Pubblico di destinazione

Il pubblico di riferimento per la soluzione comprende i seguenti gruppi:

* Data scientist
* Architetti IT
* Consulenti sul campo
* Servizi professionali
* Responsabili IT
* Chiunque abbia bisogno di un'infrastruttura in grado di offrire innovazione IT e solidi servizi di dati e applicazioni in sedi periferiche


link:hciai_edge_architecture.html["Avanti: Architettura"]
