---
sidebar: sidebar 
permalink: ai/mlops_fsxn_intro.html 
keywords: FSx ONTAP, FSx ONTAP, AWS S3, SageMaker, MLOps, NetApp ONTAP 
summary: Questa è la pagina introduttiva alla sezione MLOps di FSX ONTAP. 
---
= Amazon FSX per NetApp ONTAP (FSX ONTAP) per MLOps
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Questa sezione illustra l'applicazione pratica dello sviluppo di infrastrutture ai, fornendo una panoramica end-to-end della costruzione di una pipeline MLOps utilizzando FSX ONTAP. Con tre esempi completi, ti guida a soddisfare le tue esigenze MLOps tramite questa potente piattaforma per la gestione dei dati.

Questi articoli si concentrano su:

. link:./mlops_fsxn_s3_integration.html["Parte 1 - integrazione di Amazon FSX per NetApp ONTAP (FSX ONTAP) come bucket S3 privato in AWS SageMaker"]
. link:./mlops_fsxn_sagemaker_integration_training.html["Parte 2 - utilizzo di Amazon FSX per NetApp ONTAP (FSX ONTAP) come origine dati per il training sui modelli in SageMaker"]
. link:./mlops_fsxn_cictcd.html["Parte 3 - creazione di Una pipeline MLOps semplificata (ci/CT/CD)"]


Al termine di questa sezione, avrete acquisito una solida comprensione di come utilizzare FSX ONTAP per semplificare i processi MLOps.
