---
sidebar: sidebar 
permalink: ai/mlrun_where_to_find_additional_information.html 
keywords: NetApp Find Additional Information 
summary:  
---
= Dove trovare ulteriori informazioni
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
Per ulteriori informazioni sulle informazioni descritte in questo documento, consultare le seguenti risorse:

* Piano di controllo ai di NetApp:
+
** Report tecnico NetApp ai Control Plane
+
https://www.netapp.com/us/media/tr-4798.pdf["https://www.netapp.com/us/media/tr-4798.pdf"^]



* Storage persistente NetApp per container:
+
** Trident di NetApp
+
https://netapp.io/persistent-storage-provisioner-for-kubernetes/["https://netapp.io/persistent-storage-provisioner-for-kubernetes/"^]



* Framework E tool ML:
+
** TensorFlow: Un framework di apprendimento automatico open-source per tutti https://www.tensorflow.org/["https://www.tensorflow.org/"^]
** Docker
+
https://docs.docker.com["https://docs.docker.com"^]

** Kubernetes
+
https://kubernetes.io/docs/home/["https://kubernetes.io/docs/home/"^]

** Kubeflow
+
http://www.kubeflow.org/["http://www.kubeflow.org/"^]

** Jupyter notebook Server
+
http://www.jupyter.org/["http://www.jupyter.org/"^]



* Iguazio Data Science Platform
+
** Documentazione sulla piattaforma Iguazio Data Science
+
https://www.iguazio.com/docs/["https://www.iguazio.com/docs/"^]

** Funzione Nuclio senza server
+
https://nuclio.io/["https://nuclio.io/"^]

** Framework di orchestrazione della pipeline opensource MLRun
+
https://www.iguazio.com/open-source/mlrun/["https://www.iguazio.com/open-source/mlrun/"^]



* Sistemi NVIDIA DGX-1
+
** Sistemi NVIDIA DGX-1
+
https://www.nvidia.com/en-us/data-center/dgx-1/["https://www.nvidia.com/en-us/data-center/dgx-1/"^]

** NVIDIA Tesla V100 Tensor core GPU
+
https://www.nvidia.com/en-us/data-center/tesla-v100/["https://www.nvidia.com/en-us/data-center/tesla-v100/"^]

** NVIDIA GPU Cloud
+
https://www.nvidia.com/en-us/gpu-cloud/["https://www.nvidia.com/en-us/gpu-cloud/"^]



* Sistemi NetApp AFF
+
** Scheda informativa su AFF
+
https://www.netapp.com/us/media/ds-3582.pdf["https://www.netapp.com/us/media/ds-3582.pdf"^]

** NetApp Flash Advantage per AFF
+
https://www.netapp.com/us/media/ds-3733.pdf["https://www.netapp.com/us/media/ds-3733.pdf"^]

** Documentazione di ONTAP 9.x.
+
https://mysupport.netapp.com/documentation/productlibrary/index.html?productID=62286["https://mysupport.netapp.com/documentation/productlibrary/index.html?productID=62286"^]

** Report tecnico di NetApp FlexGroup
+
https://www.netapp.com/us/media/tr-4557.pdf["https://www.netapp.com/us/media/tr-4557.pdf"^]



* NetApp ONTAP ai
+
** Guida alla progettazione di reti ONTAP ai con DGX-1 e Cisco
+
https://www.netapp.com/us/media/nva-1121-design.pdf["https://www.netapp.com/us/media/nva-1121-design.pdf"^]

** Guida all'implementazione di ONTAP ai con DGX-1 e Cisco Networking
+
https://www.netapp.com/us/media/nva-1121-deploy.pdf["https://www.netapp.com/us/media/nva-1121-deploy.pdf"^]

** Guida alla progettazione di reti ONTAP ai con DGX-1 e Mellanox
+
https://www.netapp.com/us/media/nva-1138-design.pdf["https://www.netapp.com/us/media/nva-1138-design.pdf"^]



* Networking ai ONTAP
+
** Switch Cisco Nexus serie 3232C
+
https://www.cisco.com/c/en/us/products/switches/nexus-3232c-switch/index.html["https://www.cisco.com/c/en/us/products/switches/nexus-3232c-switch/index.html"^]

** Switch Ethernet Mellanox scale-out serie SN2000
+
https://www.mellanox.com/page/products_dyn?product_family=251&mtag=sn2000["https://www.mellanox.com/page/products_dyn?product_family=251&mtag=sn2000"^]




