---
sidebar: sidebar 
permalink: ai/nva-1156-design.html 
keywords:  
summary:  
---
= NVA-1156-DESIGN: NetApp EF-Series ai con sistemi NVIDIA DGX A100 e BeeGFS
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


Abdel Sadek, Tim Chau, Joe McCormick e David Arnette, NetApp

[role="lead"]
NVA-1156-DESIGN descrive un'architettura verificata di NetApp per i carichi di lavoro di machine learning (ML) e intelligenza artificiale (ai) che utilizzano i sistemi storage NetApp EF600 NVMe, il file system parallelo BeeGFS, i sistemi NVIDIA DGX A100 e gli switch IB NVIDIA Mellanox Quantum QM8700 a 200 Gbps. Questo design è dotato di InfiniBand (IB) a 200 Gbps per lo storage e il fabric di interconnessione del cluster di calcolo per offrire ai clienti un'architettura completamente basata su IB per carichi di lavoro dalle performance elevate. Questo documento include anche i risultati dei test di benchmark per l'architettura implementata.

link:https://www.netapp.com/pdf.html?item=/media/25445-nva-1156-design.pdf["NVA-1156-DESIGN: NetApp EF-Series ai con sistemi NVIDIA DGX A100 e BeeGFS"^]
