---
sidebar: sidebar 
permalink: ai/nva-1153-design.html 
keywords:  
summary:  
---
= NVA-1153-DESIGN: NetApp ONTAP ai con sistemi NVIDIA DGX A100 e switch Ethernet Mellanox Spectrum
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


David Arnette e Sung-Han Lin, NetApp

[role="lead"]
NVA-1153-DESIGN descrive un'architettura verificata NetApp per i carichi di lavoro di apprendimento automatico (ML) e intelligenza artificiale (ai) che utilizzano i sistemi storage NetApp AFF A800, i sistemi NVIDIA DGX A100 e gli switch Ethernet NVIDIA Mellanox Spectrum SN3700V 200 GB. Questo design è dotato di RDMA over Converged Ethernet (RoCE) per il fabric di interconnessione del cluster di calcolo per offrire ai clienti un'architettura completamente basata su ethernet per carichi di lavoro dalle performance elevate. Questo documento include anche i risultati dei test di benchmark per l'architettura implementata.

link:https://www.netapp.com/pdf.html?item=/media/21793-nva-1153-design.pdf["NVA-1153-DESIGN: NetApp ONTAP ai con sistemi NVIDIA DGX A100 e switch Ethernet Mellanox Spectrum"^]
