---
sidebar: sidebar 
permalink: ai/nvaie_initial_setup.html 
keywords: NetApp AI, AI, Artificial Intelligence, ML, Machine Learning, NVIDIA, NVIDIA AI Enterprise, NVAIE, VMware 
summary: NVIDIA ai Enterprise con NetApp e VMware - Configurazione iniziale 
---
= Setup iniziale
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
In questa sezione vengono descritte le attività di configurazione iniziali che devono essere eseguite per utilizzare NVIDIA ai Enterprise con NetApp e VMware.



== Prerequisiti

Prima di eseguire i passaggi descritti in questa sezione, si presuppone che siano già state implementate VMware vSphere e NetApp ONTAP. Per ulteriori informazioni sulle versioni di vSphere supportate, fare riferimento allalink:https://docs.nvidia.com/ai-enterprise/latest/product-support-matrix/index.html["Matrice di supporto dei prodotti NVIDIA ai Enterprise"]. Per ulteriori informazioni sull'implementazione di VMware vSphere con NetApp ONTAP, fare riferimento allalink:../vmware/index.html["Documentazione sulle soluzioni NetApp e VMware"].



== Installare il software host NVIDIA ai Enterprise

Per installare il software host NVIDIA ai EnEnterprise, seguire le istruzioni riportate nelle sezioni 1-4 del link:https://docs.nvidia.com/ai-enterprise/latest/quick-start-guide/index.html["NVIDIA ai Enterprise Quick Start Guide"].
