---
sidebar: sidebar 
permalink: ai/nvaie_initial_setup.html 
keywords: NetApp AI, AI, Artificial Intelligence, ML, Machine Learning, NVIDIA, NVIDIA AI Enterprise, NVAIE, VMware 
summary: NVIDIA ai Enterprise con NetApp e VMware - Configurazione iniziale 
---
= Setup iniziale
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


link:nvaie_architecture.html["Precedente: Architettura."]

[role="lead"]
In questa sezione vengono descritte le attività di configurazione iniziali che devono essere eseguite per utilizzare NVIDIA ai Enterprise con NetApp e VMware.



== Prerequisiti

Prima di eseguire i passaggi descritti in questa sezione, si presuppone che siano già state implementate VMware vSphere e NetApp ONTAP. Fare riferimento a. link:https://docs.nvidia.com/ai-enterprise/latest/product-support-matrix/index.html["Matrice di supporto dei prodotti NVIDIA ai Enterprise"] Per ulteriori informazioni sulle versioni di vSphere supportate. Fare riferimento a. link:https://docs.netapp.com/us-en/netapp-solutions/virtualization/netapp-vmware.html["Documentazione sulle soluzioni NetApp e VMware"] Per informazioni dettagliate sull'implementazione di VMware vSphere con NetApp ONTAP.



== Installare il software host NVIDIA ai Enterprise

Per installare il software host NVIDIA ai EnEnterprise, seguire le istruzioni riportate nelle sezioni 1-4 del link:https://docs.nvidia.com/ai-enterprise/latest/quick-start-guide/index.html["NVIDIA ai Enterprise Quick Start Guide"].

link:nvaie_ngc.html["Pagina successiva: Utilizzo del software NVIDIA NGC."]
