---
sidebar: sidebar 
permalink: ai/osrunai_testing_details_for_section_49.html 
keywords:  
summary:  
---
= Dettagli sui test per la Sezione 4.9
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Questa sezione contiene i dettagli dei test per la sezione link:osrunai_basic_resource_allocation_fairness.html["Equità nell'allocazione delle risorse di base"].

Inoltrare i lavori nel seguente ordine:

|===
| Progetto | N. di GPU | Totale | Commento 


| team-d | 2 | 6/8 | Il carico di lavoro del team-b/c viene messo in pausa e spostato a. `pending`. 


| team-d | 2 | 8/8 | I carichi di lavoro degli altri team (b/c) vengono interrompiti e spostati `pending`. 
|===
Vedere la seguente sequenza di comandi eseguiti:

....
$ runai submit d-2-gg -i gcr.io/run-ai-demo/quickstart -g 2 -p team-d$ runai submit d-3-gg -i gcr.io/run-ai-demo/quickstart -g 2 -p team-d
....
A questo punto, si dovrebbero avere i seguenti stati:

|===
| Progetto | GPU allocate | Carichi di lavoro in coda 


| squadra a. | 4/4 | Nessuno 


| team-b | 2/2 | Nessuno 


| team-c | 2/2 | Nessuno 


| team-d | 8/8 | Nessuno 
|===
Vedere la sezione link:osrunai_basic_resource_allocation_fairness.html["Equità nell'allocazione delle risorse di base"] per una discussione sullo scenario di test.
