---
sidebar: sidebar 
permalink: ai/osrunai_testing_details_for_section_4.10.html 
keywords:  
summary:  
---
= Dettagli sui test per la Sezione 4.10
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
Questa sezione contiene i dettagli dei test per la sezione link:osrunai_over-quota_fairness.html["Equità nell'overquota"].

Inoltrare i lavori nel seguente ordine per `team-a`, `team-b`, e. `team-c`:

|===
| Progetto | N. di GPU | Totale | Commento 


| squadra a. | 2 | 4/4 | 1 carico di lavoro in coda 


| squadra a. | 2 | 4/4 | 2 carichi di lavoro in coda 


| team-b | 2 | 2/2 | 2 carichi di lavoro in coda 


| team-c | 2 | 2/2 | 2 carichi di lavoro in coda 
|===
Vedere la seguente sequenza di comandi eseguiti:

....
$ runai submit a-3-gg -i gcr.io/run-ai-demo/quickstart -g 2 -p team-a$ runai submit a-4-gg -i gcr.io/run-ai-demo/quickstart -g 2 -p team-a$ runai submit b-5-gg -i gcr.io/run-ai-demo/quickstart -g 2 -p team-b$ runai submit c-6-gg -i gcr.io/run-ai-demo/quickstart -g 2 -p team-c
....
A questo punto, si dovrebbero avere i seguenti stati:

|===
| Progetto | GPU allocate | Carichi di lavoro in coda 


| squadra a. | 4/4 | Due carichi di lavoro che richiedono due GPU ciascuno 


| team-b | 2/2 | Due carichi di lavoro che richiedono due GPU ciascuno 


| team-c | 2/2 | Due carichi di lavoro che richiedono due GPU ciascuno 


| team-d | 8/8 | Nessuno 
|===
Quindi, eliminare tutti i carichi di lavoro per `team-d`:

....
$ runai delete -p team-d d-1-gggg d-2-gg d-3-gg
....
Vedere la sezione link:osrunai_over-quota_fairness.html["Equità nell'overquota"], per discussioni sullo scenario di test.
