---
sidebar: sidebar 
permalink: ai/rag_nemo_ingest_netapp_data.html 
keywords: RAG, Retrieval Augmented Generation, NetApp AI, AI, Artificial Intelligence, ML, Machine Learning, NVIDIA, NeMo, NIM, NIMS, Hybrid, Hybrid Cloud, Hybrid Multicloud, NetApp ONTAP, FlexCache, SnapMirror, BlueXP 
summary: Enterprise RAG con NetApp - acquisizione di dati NetApp esistenti con NEMO Retriever 
---
= Acquisizione dei dati NetApp esistenti con NEMO Retriever
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
Il microservizio NEMO Embedding, che fa parte di NVIDIA NEMO Retriever, può essere utilizzato per acquisire dati nella knowledge base/archivio vettoriale RAG. Questa sezione descrive le attività da eseguire per acquisire dati da origini dati NetApp esistenti.



== Acquisire i dati con NVIDIA Sample Chat Bot

È possibile acquisire i file esistenti utilizzando l'applicazione Web bot di esempio distribuita dall'operatore NVIDIA Enterprise RAG LLM. Il processo per l'acquisizione di file esistenti utilizzando l'applicazione Web bot della chat è descritto in questo documento link:https://netapp.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=f718b504-d89b-497e-bd25-b13400d0bfbf&start=57["video dimostrativo."]



== Acquisire i dati a livello di codice

È possibile acquisire grandi quantità di dati a livello di programmazione utilizzando il server di query RAG distribuito dall'operatore NVIDIA Enterprise RAG LLM.

L'API del server di query RAG viene esposta automaticamente tramite un servizio Kubernetes, come mostrato nell'output del seguente comando.

[source]
----
$ kubectl -n rag-sample get service chain-server
NAME           TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)    AGE
chain-server   ClusterIP   10.233.28.129   <none>        8081/TCP   59d
----
Per impostazione predefinita, il tipo di servizio è ClusterIP, quindi è possibile accedere all'endpoint API solo dall'interno del cluster Kubernetes. È possibile modificare il tipo di servizio modificando il `query.service.type` nella configurazione della pipeline del timone (ad esempio, helmpipeline_app.yaml).

È possibile accedere allo schema swagger del server API all'indirizzo `<chain_server_url>:<chain_server_api_port>/docs``.
