---
sidebar: sidebar 
permalink: ai/rag_nemo_data_protection.html 
keywords: RAG, Retrieval Augmented Generation, NetApp AI, AI, Artificial Intelligence, ML, Machine Learning, NVIDIA, NeMo, NIM, NIMS, Hybrid, Hybrid Cloud, Hybrid Multicloud, NetApp ONTAP, FlexCache, SnapMirror, BlueXP 
summary: RAG aziendale con NetApp - protezione dei dati della Knowledge base RAG 
---
= Protezione dei dati della Knowledge base RAG
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
Poiché le applicazioni RAG diventano componenti chiave di importanti flussi di lavoro organizzativi, è fondamentale proteggere gli archivi vettoriali/le knowledge base che supportano queste applicazioni RAG. È importante eseguire il backup dei database vettoriali e implementare i flussi di lavoro di disaster recovery esattamente come per qualsiasi altro database.



== Proteggete la vostra knowledge base NEMO RAG utilizzando le tecnologie NetApp

Le tecnologie NetApp, come link:https://docs.netapp.com/us-en/ontap/concepts/snapshot-copies-concept.html["Copie Snapshot"] e. link:https://docs.netapp.com/us-en/ontap/concepts/snapmirror-disaster-recovery-data-transfer-concept.html["Disaster recovery SnapMirror"], può essere utilizzato per proteggere il proprio archivio vettoriale/knowledge base. Per ulteriori informazioni sulla protezione dei dati del database vettoriale, fare riferimento alla link:https://docs.netapp.com/us-en/netapp-solutions/ai/vector-database-solution-with-netapp.html["Documentazione della soluzione di database vettoriale NetApp."]
