---
sidebar: sidebar 
permalink: ai/rag_introduction.html 
keywords: RAG, Retrieval Augmented Generation, NetApp AI, AI, Artificial Intelligence, ML, Machine Learning, NVIDIA, NeMo, NIM, NIMS, Hybrid, Hybrid Cloud, Hybrid Multicloud, NetApp ONTAP, FlexCache, SnapMirror, BlueXP 
summary: RAG Enterprise con NVIDIA NEMO e NetApp - Introduzione 
---
= Enterprise Retrieval Augmented Generation (RAG) con NetApp
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


Mike Oglesby, NetApp
Thyagarajan, NetApp

[role="lead"]
L'intelligenza artificiale generativa sta trasformando l'esperienza di ricerca aziendale. Il prodotto consente agli utenti di dati di un'azienda di scoprire asset di dati che risiedono ovunque, on-premise o cloud pubblico. Se l'intelligenza artificiale generativa viene utilizzata dagli sviluppatori per generare codice per progettare una moderna applicazione Web, oppure, per creare animazioni utilizzando la fisica del mondo reale e i dati di movimento, le organizzazioni utilizzano l'intelligenza artificiale generativa e i modelli di grandi linguaggi preformati (LLMS, Large Language Model) per creare applicazioni di intelligenza artificiale trasformative, progettare nuove funzioni di prodotto, migliorare la produttività tecnica e aumentare l'esperienza del cliente.

Tuttavia, l'intelligenza artificiale generativa e le soluzioni LLMS da sole non possono garantire il valore aziendale. Per creare un impatto aziendale tangibile, l'ai generativa deve sfruttare i dati selezionati per ottenere risultati di business di qualità. Le grandi imprese si stanno quindi orientando verso un quadro emergente ed essenziale noto come “Retrieval augmented generation” (RAG). In questa soluzione, presentiamo un'architettura per le organizzazioni che desiderano costruire un gasdotto RAG. Questa soluzione può aiutarti a liberare valore dai tuoi dati privati recuperando informazioni contestuali tramite una pipeline RAG privata.
