---
sidebar: sidebar 
permalink: ai/runai-ld_conclusion.html 
keywords: azure, lane, detection, run, ai, workloads 
summary: 'NetApp Run ai ha collaborato alla creazione di questo report tecnico per dimostrare le funzionalità uniche di Azure NetApp Files insieme alla piattaforma DI RUN ai per semplificare l"orchestrazione dei carichi di lavoro ai.' 
---
= Conclusione
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
NetApp e RUN: L'ai ha collaborato alla creazione di questo report tecnico per dimostrare le funzionalità uniche di Azure NetApp Files insieme alla piattaforma RUN: Ai per semplificare l'orchestrazione dei carichi di lavoro ai. Questo report tecnico fornisce un'architettura di riferimento per semplificare il processo di pipeline di dati e orchestrazione dei carichi di lavoro per il training di rilevamento della corsia distribuita.

In conclusione, per quanto riguarda la formazione distribuita su larga scala (soprattutto in un ambiente di cloud pubblico), il componente di orchestrazione delle risorse e storage è una parte critica della soluzione. Assicurarsi che la gestione dei dati non ostacoli mai l'elaborazione di più GPU, per cui si ottiene un utilizzo ottimale dei cicli GPU. Pertanto, rendendo il sistema il più conveniente possibile per scopi di formazione distribuita su larga scala.

Il data fabric fornito da NetApp supera la sfida consentendo a data scientist e data engineer di connettersi tra loro on-premise e nel cloud per avere dati sincroni, senza eseguire alcun intervento manuale. In altre parole, il data fabric rende più uniforme il processo di gestione del workflow ai distribuito in più sedi. Inoltre, facilita la disponibilità dei dati on-demand avvicinando i dati al calcolo ed eseguendo analisi, training e validazione, dove e quando necessario. Questa funzionalità non solo consente l'integrazione dei dati, ma anche la protezione e la sicurezza dell'intera pipeline di dati.
