---
sidebar: sidebar 
permalink: ai/runai-ld_executive_summary.html 
keywords: azure, lane, detection, training, solution, design 
summary: Da maggio 2019, Microsoft offre un servizio di portale nativo di Azure per i file service NFS e SMB aziendali basati sulla tecnologia NetApp ONTAP. 
---
= TR-4896: Formazione distribuita in Azure: Rilevamento della corsia - progettazione della soluzione
:allow-uri-read: 


Muneer Ahmad e Verron Martina, NetApp Ronen Dar, RUN:ai

[role="lead"]
Da maggio 2019, Microsoft offre un servizio di portale nativo di Azure per i file service NFS e SMB aziendali basati sulla tecnologia NetApp ONTAP. Questo sviluppo è guidato da una partnership strategica tra Microsoft e NetApp e estende ulteriormente la portata dei servizi dati ONTAP di livello mondiale ad Azure.

NetApp, un provider leader di servizi dati cloud, ha collaborato con RUN: Ai, un'azienda che virtualizza l'infrastruttura ai, per consentire una sperimentazione ai più rapida con un utilizzo completo della GPU. La partnership consente ai team di accelerare l'ai eseguendo numerosi esperimenti in parallelo, con accesso rapido ai dati e sfruttando risorse di calcolo illimitate. RUN: L'ai consente l'utilizzo completo della GPU automatizzando l'allocazione delle risorse, mentre l'architettura comprovata di Azure NetApp Files consente di eseguire ogni esperimento alla massima velocità eliminando le ostruzioni della pipeline dei dati.

NetApp e RUN: L'ai ha Unito le forze per offrire ai clienti una piattaforma a prova di futuro per il loro viaggio nell'ai in Azure. Dagli analytics al calcolo ad alte performance (HPC) alle decisioni autonome (in cui i clienti possono ottimizzare i propri investimenti IT pagando solo ciò di cui hanno bisogno, quando ne hanno bisogno), l'alleanza tra NetApp e RUN: L'ai offre una singola esperienza unificata in Azure Cloud.
