---
sidebar: sidebar 
permalink: ai/tr-4799.html 
keywords:  
summary:  
---
= TR-4799-DESIGN: Architettura di riferimento ai di NetApp ONTAP per carichi di lavoro a guida autonoma
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


David Arnette e Sung-Han Lin, NetApp

[role="lead"]
La famiglia di sistemi NVIDIA DGX è la prima piattaforma al mondo di intelligenza artificiale integrata (ai) costruita appositamente per l'ai aziendale. I sistemi storage NetApp AFF offrono performance estreme e funzionalità di gestione dei dati del cloud ibrido leader di settore. NetApp e NVIDIA hanno collaborato per creare l'architettura di riferimento ai di NetApp ONTAP per offrire ai clienti una soluzione chiavi in mano per supportare i carichi di lavoro di ai e machine learning (ML) con performance, affidabilità e supporto di livello Enterprise.

link:https://www.netapp.com/pdf.html?item=/media/8554-tr4799designpdf.pdf["TR-4799-DESIGN: Architettura di riferimento ai di NetApp ONTAP per carichi di lavoro a guida autonoma"^]
