---
sidebar: sidebar 
permalink: ai/tr-4785.html 
keywords:  
summary:  
---
= TR-4785: Implementazione dell'ai con NetApp e-Series e BeeGFS
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


Nagalakshmi Raju, Daniel Landes, Nathan Swartz, Amine Bennani, NetApp

[role="lead"]
Le applicazioni di intelligenza artificiale (ai), machine learning (ML) e deep learning (DL) implicano grandi set di dati e calcoli elevati. Per eseguire con successo questi workload, è necessaria un'infrastruttura agile che consenta di scalare perfettamente i nodi di storage e di calcolo. Questo report include le fasi per l'esecuzione di un modello di training ai in una modalità distribuita, che consente una scalabilità perfetta dei nodi di calcolo e storage. Il report include anche diverse metriche delle performance per mostrare come una soluzione che combina lo storage NetApp e-Series con il file system parallelo BeeGFS offre una soluzione semplice, flessibile e conveniente per i carichi di lavoro ai.

link:https://www.netapp.com/pdf.html?item=/media/17040-tr4785pdf.pdf["TR-4785: Implementazione dell'ai con NetApp e-Series e BeeGFS"^]
