---
sidebar: sidebar 
permalink: ai/tr-4807.html 
keywords:  
summary:  
---
= TR-4807: Architettura di riferimento ai di NetApp ONTAP per i carichi di lavoro dei servizi finanziari - progettazione della soluzione
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


Karthikeyan Nagalingam, Sung-Han Lin, NetApp Jacci Cenci, NVIDIA

[role="lead"]
Questa architettura di riferimento offre linee guida per i clienti che stanno costruendo un'infrastruttura di intelligenza artificiale utilizzando i sistemi NVIDIA DGX-1 e lo storage NetApp AFF per i casi di utilizzo del settore finanziario. Include informazioni sui flussi di lavoro di alto livello utilizzati per lo sviluppo di modelli di deep learning per i test case e i risultati dei servizi finanziari. Include anche consigli di dimensionamento per le implementazioni dei clienti.

link:https://www.netapp.com/pdf.html?item=/media/17205-tr4807pdf.pdf["TR-4807: Architettura di riferimento ai di NetApp ONTAP per i carichi di lavoro dei servizi finanziari - progettazione della soluzione"^]
