---
sidebar: sidebar 
permalink: ai/tr-4851.html 
keywords:  
summary:  
---
= TR-4851: Data Lake NetApp StorageGRID per carichi di lavoro di guida autonoma - progettazione della soluzione
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


David Arnette, NetApp

[role="lead"]
TR-4851 dimostra l'utilizzo dello storage a oggetti NetApp StorageGRID come repository di dati e sistema di gestione per l'apprendimento automatico (ML) e lo sviluppo di software di deep learning (DL). Questo documento descrive il flusso di dati e i requisiti nello sviluppo di software per veicoli autonomi e le funzionalità di StorageGRID che ottimizzano il ciclo di vita dei dati. Questa soluzione si applica a qualsiasi workflow di pipeline di dati multistadio tipico dei processi di sviluppo ML e DL.

link:https://www.netapp.com/pdf.html?item=/media/19399-tr-4851.pdf["TR-4851: Data Lake NetApp StorageGRID per carichi di lavoro di guida autonoma - progettazione della soluzione"^]
