---
sidebar: sidebar 
permalink: ai/tr-4811-link.html 
keywords:  
summary:  
---
= TR-4811: Architettura di riferimento ai di NetApp ONTAP per il settore sanitario: Imaging diagnostico - progettazione della soluzione
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


Rick Huang, Sung-Han Lin, Sathish Thyagarajan, NetApp Jacci Cenci, NVIDIA

[role="lead"]
Questa architettura di riferimento offre linee guida per i clienti che creano un'infrastruttura di intelligenza artificiale (ai) utilizzando i sistemi NVIDIA DGX-2 e lo storage NetApp AFF per i casi di utilizzo nel settore sanitario. Include informazioni sui flussi di lavoro di alto livello utilizzati per lo sviluppo di modelli di deep learning (DL) per l'imaging diagnostico medico, i casi di test validati e i risultati. Include anche consigli di dimensionamento per le implementazioni dei clienti.

link:https://www.netapp.com/pdf.html?item=/media/7395-tr4811.pdf["TR-4811: Architettura di riferimento ai di NetApp ONTAP per il settore sanitario: Imaging diagnostico - progettazione della soluzione"^]
