---
sidebar: sidebar 
permalink: cyber-vault/ontap-cyber-vault-powershell-conclusion.html 
keywords: Cyber vault, powershell, script, configuration, validation, hardening 
summary: Questa è la soluzione NetApp ONTAP per la configurazione, la protezione e la convalida di un cyber vault basato su ONTAP 
---
= Conclusioni della soluzione PowerShell relativa al cyber vault di ONTAP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media


[role="lead"]
Sfruttando l'air-gapping con solide metodologie di protezione avanzata fornite da ONTAP, NetApp ti consente di creare un ambiente di storage sicuro e isolato in grado di resistere alle minacce informatiche in evoluzione. Tutto questo si ottiene mantenendo l'agilità e l'efficienza dell'infrastruttura storage esistente. Questo accesso sicuro consente alle aziende di raggiungere i loro rigorosi obiettivi in termini di sicurezza e tempi di attività con modifiche minime al personale, ai processi e alla struttura tecnologica esistenti.

Il cyber vault di ONTAP utilizza le funzionalità native di ONTAP è un approccio semplice per una protezione aggiuntiva al fine di creare copie immutabili e indelebili dei dati. L'aggiunta del cyber-vault basato su ONTAP di NetApp alla postura di sicurezza generale consentirà di:

* Creare un ambiente separato e disconnesso dalle reti di produzione e di backup e limitare l'accesso degli utenti.

