---
sidebar: sidebar 
permalink: automation/automation_introduction.html 
summary: 'L"automazione delle soluzioni NetApp consente al cliente di automatizzare l"implementazione, la configurazione e l"esecuzione di molte attività applicative e infrastrutturate comuni.' 
keywords: netapp, solutions, automation, ansible, terraform 
---
= Automazione delle soluzioni NetApp
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
L'automazione delle soluzioni NetApp consente al cliente di automatizzare l'implementazione, la configurazione e l'esecuzione di molte attività applicative e infrastrutturate comuni.



== Introduzione

Nel fornire soluzioni per affrontare le sfide aziendali odierne, NetApp offre soluzioni con i seguenti obiettivi:

* Fornendo fasi di implementazione e configurazione validate,
* Soluzioni facili da utilizzare,
* Fornire un'implementazione della soluzione che abbia un risultato prevedibile, sia facilmente ripetuta e scalabile nell'azienda del cliente.


Per raggiungere questi obiettivi, è fondamentale semplificare l'implementazione e la configurazione dell'infrastruttura e/o delle applicazioni attraverso le nostre soluzioni attraverso l'automazione. NetApp si impegna a semplificare il consumo delle soluzioni attraverso l'automazione.

Utilizzando strumenti di automazione open-source come Red Hat Ansible, HashiCorp Terraform o Microsoft PowerShell, le soluzioni NetApp sono in grado di automatizzare l'implementazione delle applicazioni, il provisioning del cloud, la gestione della configurazione e molte altre attività IT comuni. Le soluzioni NetApp sfruttano gli elementi di automazione disponibili al pubblico, oltre a fornire l'automazione creata da NetApp, per semplificare l'implementazione complessiva di una soluzione.

Laddove sono disponibili funzionalità di automazione, il materiale collaterale della soluzione guiderà l'utente attraverso il processo di automazione della soluzione o delle fasi della soluzione attraverso gli strumenti di automazione specifici.
