---
sidebar: sidebar 
permalink: automation/getting-started.html 
summary: 'L"automazione delle soluzioni NetApp consente al cliente di automatizzare l"implementazione, la configurazione e l"esecuzione di molte attività comuni dell"infrastruttura e delle applicazioni.' 
keywords: netapp, awx, tower, ansible tower, solutions, automation, ansible, getting, started 
---
= Introduzione all'automazione delle soluzioni NetApp
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
L'automazione della soluzione NetApp offre semplicità e ripetibilità per molte delle attività comuni utilizzate dalle soluzioni NetApp.

Prima di eseguire qualsiasi automazione della soluzione, è necessario configurare l'ambiente in base alla modalità di esecuzione dell'automazione. Sono disponibili opzioni per eseguire l'automazione dalla riga di comando o tramite uno strumento come AWX o tower.

Le sezioni seguenti illustrano i passaggi necessari per configurare l'ambiente per ciascuno degli ambienti specificati.

.Configurare il nodo di controllo Ansible per le implementazioni CLI su RHEL/CentOS
[%collapsible]
====
. Requisiti per il nodo di controllo Ansible:
+
.. Una macchina RHEL/CentOS con i seguenti pacchetti installati:
+
... Pito3
... Pip3
... Ansible (versione successiva alla 2.10.0)
... Git






Se si dispone di un computer RHEL/CentOS nuovo senza i requisiti sopra indicati, seguire la procedura riportata di seguito per configurare tale computer come nodo di controllo Ansible:

. Abilitare il repository Ansible per RHEL-8/RHEL-7
+
.. Per RHEL-8 (eseguire il seguente comando come root)
+
[source, cli]
----
subscription-manager repos --enable ansible-2.9-for-rhel-8-x86_64-rpms
----
.. Per RHEL-7 (eseguire il seguente comando come root)
+
[source, cli]
----
subscription-manager repos --enable rhel-7-server-ansible-2.9-rpms
----


. Incollare il contenuto riportato di seguito nel terminale
+
[source, cli]
----
sudo yum -y install python3 >> install.log
sudo yum -y install python3-pip >> install.log
python3 -W ignore -m pip --disable-pip-version-check install ansible >> install.log
sudo yum -y install git >> install.log
----


====
.Configurare il nodo di controllo Ansible per le implementazioni CLI su Ubuntu / Debian
[%collapsible]
====
. Requisiti per il nodo di controllo Ansible:
+
.. Una macchina Ubuntu/Debian con i seguenti pacchetti installati:
+
... Pito3
... Pip3
... Ansible (versione successiva alla 2.10.0)
... Git






Se si dispone di una nuova macchina Ubuntu/Debian senza i requisiti di cui sopra, seguire la procedura riportata di seguito per impostare la macchina come nodo di controllo Ansible:

. Incollare il contenuto riportato di seguito nel terminale
+
[source, cli]
----
sudo apt-get -y install python3 >> outputlog.txt
sudo apt-get -y install python3-pip >> outputlog.txt
python3 -W ignore -m pip --disable-pip-version-check install ansible >> outputlog.txt
sudo apt-get -y install git >> outputlog.txt
----


====
.Configurazione di Ansible Tower o AWX per implementazioni tower/AWX
[%collapsible]
====
Questa sezione descrive i passaggi necessari per configurare i parametri in AWX/Ansible Tower che preparano l'ambiente per l'utilizzo delle soluzioni automatizzate di NetApp.

. Configurare l'inventario.
+
.. Accedere a Resources → Inventories → Add e fare clic su Add Inventory (Aggiungi inventario).
.. Fornire i dettagli relativi al nome e all'organizzazione e fare clic su Save (Salva).
.. Nella pagina Inventories (inventari), fare clic sulle risorse di inventario appena create.
.. Se sono presenti variabili di inventario, incollarle nel campo Variables (variabili).
.. Accedere al sottomenu Groups (gruppi) e fare clic su Add (Aggiungi).
.. Fornire il nome del gruppo, copiare le variabili del gruppo (se necessario) e fare clic su Save (Salva).
.. Fare clic sul gruppo creato, accedere al sottomenu hosts e fare clic su Add New host (Aggiungi nuovo host).
.. Fornire il nome host e l'indirizzo IP dell'host, incollare le variabili host (se necessario) e fare clic su Save (Salva).


. Creare tipi di credenziale. Per le soluzioni che includono ONTAP, Element, VMware o qualsiasi altra connessione di trasporto basata su HTTPS, è necessario configurare il tipo di credenziale in modo che corrisponda alle voci di nome utente e password.
+
.. Accedere a Administration → Credential Types (Amministrazione tipi di credenziali) e fare clic su Add (Aggiungi
.. Fornire il nome e la descrizione.
.. Incollare il seguente contenuto nella configurazione di input:




[listing]
----
fields:
- id: username
type: string
label: Username
- id: password
type: string
label: Password
secret: true
- id: vsadmin_password
type: string
label: vsadmin_password
secret: true
----
. Incollare il seguente contenuto nella configurazione dell'iniettore:


[listing]
----
extra_vars:
password: '{{ password }}'
username: '{{ username }}'
vsadmin_password: '{{ vsadmin_password }}'
----
. Configurare le credenziali.
+
.. Accedere a risorse → credenziali e fare clic su Aggiungi.
.. Inserire il nome e i dettagli dell'organizzazione.
.. Selezionare il tipo di credenziale corretto; se si desidera utilizzare l'accesso SSH standard, selezionare il tipo macchina o, in alternativa, selezionare il tipo di credenziale personalizzato creato.
.. Inserire gli altri dati corrispondenti e fare clic su Save (Salva).


. Configurare il progetto.
+
.. Accedere a risorse → progetti e fare clic su Aggiungi.
.. Inserire il nome e i dettagli dell'organizzazione.
.. Selezionare Git (Git) per il tipo di credenziale del controllo di origine.
.. Incollare l'URL del controllo di origine (o l'URL del clone git) corrispondente alla soluzione specifica.
.. Facoltativamente, se l'URL Git è controllato dall'accesso, creare e allegare la credenziale corrispondente nella credenziale di controllo del codice sorgente.
.. Fare clic su Salva.


. Configurare il modello di lavoro.
+
.. Accedere a risorse → modelli → Aggiungi e fare clic su Aggiungi modello di processo.
.. Immettere il nome e la descrizione.
.. Selezionare il tipo di lavoro; Esegui consente di configurare il sistema in base a un playbook e Check esegue un ciclo completo del playbook senza configurare effettivamente il sistema.
.. Seleziona l'inventario, il progetto e le credenziali corrispondenti per il playbook.
.. Selezionare la guida che si desidera eseguire come parte del modello di lavoro.
.. In genere, le variabili vengono incollate durante il runtime. Pertanto, per visualizzare la richiesta di popolare le variabili durante l'esecuzione, assicurarsi di selezionare la casella di controllo prompt on Launch (prompt all'avvio) corrispondente al campo Variable (variabile).
.. Fornire eventuali altri dettagli necessari e fare clic su Save (Salva).


. Avviare il modello di lavoro.
+
.. Accedere a risorse → modelli.
.. Fare clic sul modello desiderato, quindi fare clic su Launch (Avvia).
.. Se richiesto all'avvio, inserire le variabili, quindi fare nuovamente clic su Launch (Avvia).




====
Per ulteriori informazioni, visitare il sito link:https://netapp.io/2018/10/08/getting-started-with-netapp-and-ansible-install-ansible/["Introduzione all'automazione delle soluzioni NetApp e ad Ansible"]

Per richiedere l'automazione, compilare il link:https://github.com/NetAppDocs/netapp-solutions/issues/new?body=%5BRequest%20Automation%5D%0d%0a%0d%0aSolution%20Name:%20%0d%0aRequest%20Title:%20%0d%0aDescription:%0d%0aSuggestions:&title=Request%20Automation%20-%20["modulo di richiesta di automazione"].
